from __future__ import annotations

from typing import Any, List, Literal, TypedDict

from typing_extensions import NotRequired

### This file is automatically generated and surgically cleaned. Do not edit directly. ###

TapirMasterModels: TypeAlias = Any
SurfaceType: TypeAlias = Literal[
    "General", "Simple", "Matte", "Metal", "Plastic", "Glass", "Glowing", "Constant"
]
AttributeType: TypeAlias = Literal[
    "Layer",
    "Line",
    "Fill",
    "Composite",
    "Surface",
    "LayerCombination",
    "ZoneCategory",
    "Profile",
    "PenTable",
    "MEPSystem",
    "OperationProfile",
    "BuildingMaterial",
]
Guid: TypeAlias = str
PossibleStringValues: TypeAlias = list[str]


class PossibleNumericValue(TypedDict, closed=True):
    value: float
    flag: NotRequired[str]
    description: NotRequired[str]
PossibleNumericValues: TypeAlias = list[PossibleNumericValue]


class GDLParameterDetails(TypedDict, closed=True):
    name: str
    displayName: str
    index: int
    type: str
    dimension1: int
    dimension2: int
    value: Any
    valueDescription: NotRequired[str]
    isLocked: bool
    flags: list[
        Literal["Hidden", "HiddenFromScript", "Disabled", "Child", "Unique", "Fixed"]
    ]
    possibleValues: NotRequired[PossibleStringValues | PossibleNumericValues]
    canHaveCustomValue: NotRequired[bool]


class SetGDLParameterByNameDetails(TypedDict, closed=True):
    name: str
    value: Any


class SetGDLParameterByIndexDetails(TypedDict, closed=True):
    index: int
    value: Any
SetGDLParameterDetails: TypeAlias = (
    SetGDLParameterByNameDetails | SetGDLParameterByIndexDetails
)


class PolyArc(TypedDict, closed=True):
    begIndex: int
    endIndex: int
    arcAngle: float


class Coordinate2D(TypedDict, closed=True):
    x: float
    y: float


class Coordinate3D(TypedDict, closed=True):
    x: float
    y: float
    z: float


class Dimensions3D(TypedDict, closed=True):
    x: float
    y: float
    z: float


class ColorRGB(TypedDict, closed=True):
    red: float
    green: float
    blue: float


class Texture(TypedDict, closed=True):
    name: str
    rotationAngle: NotRequired[float]
    xSize: NotRequired[float]
    ySize: NotRequired[float]
    FillRectangle: NotRequired[bool]
    FitPicture: NotRequired[bool]
    mirrorX: NotRequired[bool]
    mirrorY: NotRequired[bool]
    useAlphaChannel: NotRequired[bool]
    alphaChannelChangesTransparency: NotRequired[bool]
    alphaChannelChangesSurfaceColor: NotRequired[bool]
    alphaChannelChangesAmbientColor: NotRequired[bool]
    alphaChannelChangesSpecularColor: NotRequired[bool]
    alphaChannelChangesDiffuseColor: NotRequired[bool]


class Error(TypedDict, closed=True):
    code: int
    message: str


class ErrorItem(TypedDict, closed=True):
    error: Error


class SuccessfulExecutionResult(TypedDict, closed=True):
    success: Literal[True]


class FailedExecutionResult(TypedDict, closed=True):
    success: Literal[False]
    error: Error
ExecutionResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult
ExecutionResults: TypeAlias = list[ExecutionResult]
ElementType: TypeAlias = Literal[
    "Wall",
    "Column",
    "Beam",
    "Window",
    "Door",
    "Object",
    "Lamp",
    "Slab",
    "Roof",
    "Mesh",
    "Dimension",
    "RadialDimension",
    "LevelDimension",
    "AngleDimension",
    "Text",
    "Label",
    "Zone",
    "Hatch",
    "Line",
    "PolyLine",
    "Arc",
    "Circle",
    "Spline",
    "Hotspot",
    "CutPlane",
    "Camera",
    "CamSet",
    "Group",
    "SectElem",
    "Drawing",
    "Picture",
    "Detail",
    "Elevation",
    "InteriorElevation",
    "Worksheet",
    "Hotlink",
    "CurtainWall",
    "CurtainWallSegment",
    "CurtainWallFrame",
    "CurtainWallPanel",
    "CurtainWallJunction",
    "CurtainWallAccessory",
    "Shell",
    "Skylight",
    "Morph",
    "ChangeMarker",
    "Stair",
    "Riser",
    "Tread",
    "StairStructure",
    "Railing",
    "RailingToprail",
    "RailingHandrail",
    "RailingRail",
    "RailingPost",
    "RailingInnerPost",
    "RailingBaluster",
    "RailingPanel",
    "RailingSegment",
    "RailingNode",
    "RailingBalusterSet",
    "RailingPattern",
    "RailingToprailEnd",
    "RailingHandrailEnd",
    "RailingRailEnd",
    "RailingToprailConnection",
    "RailingHandrailConnection",
    "RailingRailConnection",
    "RailingEndFinish",
    "BeamSegment",
    "ColumnSegment",
    "Opening",
    "Unknown",
]
ElementFilter: TypeAlias = Literal[
    "IsEditable",
    "IsVisibleByLayer",
    "IsVisibleByRenovation",
    "IsVisibleByStructureDisplay",
    "IsVisibleIn3D",
    "OnActualFloor",
    "OnActualLayout",
    "InMyWorkspace",
    "IsIndependent",
    "InCroppedView",
    "HasAccessRight",
    "IsOverriddenByRenovation",
]
WindowType: TypeAlias = Literal[
    "FloorPlan",
    "Section",
    "Details",
    "3DModel",
    "Layout",
    "Drawing",
    "CustomText",
    "CustomDraw",
    "MasterLayout",
    "Elevation",
    "InteriorElevation",
    "Worksheet",
    "Report",
    "3DDocument",
    "External3D",
    "Movie3D",
    "MovieRendering",
    "Rendering",
    "ModelCompare",
    "Interactive Schedule",
    "Unknown",
]
LengthType: TypeAlias = Literal[
    "Meter",
    "Decimeter",
    "Centimeter",
    "Millimeter",
    "FootFracInch",
    "FootDecInch",
    "DecFoot",
    "FracInch",
    "DecInch",
]
AreaType: TypeAlias = Literal[
    "SquareMeter", "SquareCentimeter", "SquareMillimeter", "SquareFoot", "SquareInch"
]
VolumeType: TypeAlias = Literal[
    "CubicMeter",
    "Liter",
    "CubicCentimeter",
    "CubicMillimeter",
    "CubicFoot",
    "CubicInch",
    "CubicYard",
    "Gallon",
]
AngleType: TypeAlias = Literal[
    "DecimalDegree", "DegreeMinSec", "Grad", "Radian", "Surveyors"
]
AccuracyType: TypeAlias = Literal[
    "Off", "ShowSmall5", "ShowSmall25", "ShowSmall1", "ShowSmall01", "InchCaseFractions"
]


class IssueId(TypedDict, closed=True):
    guid: Guid


class IssueIdArrayItem(TypedDict, closed=True):
    issueId: IssueId
Issues: TypeAlias = list[IssueIdArrayItem]
IssueElementType: TypeAlias = Literal[
    "Creation", "Highlight", "Deletion", "Modification"
]
IssueCommentStatus: TypeAlias = Literal["Error", "Warning", "Info", "Unknown"]


class PropertyGroupId(TypedDict, closed=True):
    guid: Guid


class PropertyGroupIdArrayItem(TypedDict, closed=True):
    propertyGroupId: PropertyGroupId


class PropertyId(TypedDict, closed=True):
    guid: Guid


class PropertyIdArrayItem(TypedDict, closed=True):
    propertyId: PropertyId
PropertyIds: TypeAlias = list[PropertyIdArrayItem]


class PropertyDetails(TypedDict, closed=True):
    propertyId: PropertyId
    propertyType: Literal["StaticBuiltIn", "DynamicBuiltIn", "Custom"]
    propertyGroupName: str
    propertyName: str
    propertyCollectionType: Literal[
        "Undefined",
        "Single",
        "List",
        "SingleChoiceEnumeration",
        "MultipleChoiceEnumeration",
    ]
    propertyValueType: Literal[
        "Undefined", "Integer", "Real", "String", "Boolean", "Guid"
    ]
    propertyMeasureType: Literal[
        "Undefined", "Default", "Length", "Area", "Volume", "Angle"
    ]
    propertyIsEditable: bool


class PropertyValue(TypedDict, closed=True):
    value: str


class PropertyValueArrayItem(TypedDict, closed=True):
    propertyValue: PropertyValue
PropertyValueOrErrorItem: TypeAlias = PropertyValueArrayItem | ErrorItem
PropertyValues: TypeAlias = list[PropertyValueOrErrorItem]


class PropertyValuesArrayItem(TypedDict, closed=True):
    propertyValues: PropertyValues
PropertyValuesOrError: TypeAlias = PropertyValuesArrayItem | ErrorItem
PropertyValuesOrErrorArray: TypeAlias = list[PropertyValuesOrError]
PropertyIdOrError: TypeAlias = PropertyIdArrayItem | ErrorItem
PropertyIdOrErrorArray: TypeAlias = list[PropertyIdOrError]
PropertyDataType: TypeAlias = Literal[
    "number",
    "integer",
    "string",
    "boolean",
    "length",
    "area",
    "volume",
    "angle",
    "numberList",
    "integerList",
    "stringList",
    "booleanList",
    "lengthList",
    "areaList",
    "volumeList",
    "angleList",
    "singleEnum",
    "multiEnum",
]


class DisplayValueEnumId(TypedDict, closed=True):
    type: Literal["displayValue"]
    displayValue: str


class NonLocalizedValueEnumId(TypedDict, closed=True):
    type: Literal["nonLocalizedValue"]
    nonLocalizedValue: str
EnumValueId: TypeAlias = DisplayValueEnumId | NonLocalizedValueEnumId


class EnumValueIdArrayItem(TypedDict, closed=True):
    enumValueId: EnumValueId
EnumValueIds: TypeAlias = list[EnumValueIdArrayItem]


class UserUndefinedPropertyValue(TypedDict, closed=True):
    type: PropertyDataType
    status: Literal["userUndefined"]


class NotAvailablePropertyValue(TypedDict, closed=True):
    type: PropertyDataType
    status: Literal["notAvailable"]


class NormalNumberPropertyValue(TypedDict, closed=True):
    type: Literal["number"]
    status: Literal["normal"]
    value: float


class NormalIntegerPropertyValue(TypedDict, closed=True):
    type: Literal["integer"]
    status: Literal["normal"]
    value: int


class NormalStringPropertyValue(TypedDict, closed=True):
    type: Literal["string"]
    status: Literal["normal"]
    value: str


class NormalBooleanPropertyValue(TypedDict, closed=True):
    type: Literal["boolean"]
    status: Literal["normal"]
    value: bool


class NormalLengthPropertyValue(TypedDict, closed=True):
    type: Literal["length"]
    status: Literal["normal"]
    value: float


class NormalAreaPropertyValue(TypedDict, closed=True):
    type: Literal["area"]
    status: Literal["normal"]
    value: float


class NormalVolumePropertyValue(TypedDict, closed=True):
    type: Literal["volume"]
    status: Literal["normal"]
    value: float


class NormalAnglePropertyValue(TypedDict, closed=True):
    type: Literal["angle"]
    status: Literal["normal"]
    value: float


class NormalNumberListPropertyValue(TypedDict, closed=True):
    type: Literal["numberList"]
    status: Literal["normal"]
    value: list[float]


class NormalIntegerListPropertyValue(TypedDict, closed=True):
    type: Literal["integerList"]
    status: Literal["normal"]
    value: list[int]


class NormalStringListPropertyValue(TypedDict, closed=True):
    type: Literal["stringList"]
    status: Literal["normal"]
    value: list[str]


class NormalBooleanListPropertyValue(TypedDict, closed=True):
    type: Literal["booleanList"]
    status: Literal["normal"]
    value: list[bool]


class NormalLengthListPropertyValue(TypedDict, closed=True):
    type: Literal["lengthList"]
    status: Literal["normal"]
    value: list[float]


class NormalAreaListPropertyValue(TypedDict, closed=True):
    type: Literal["areaList"]
    status: Literal["normal"]
    value: list[float]


class NormalVolumeListPropertyValue(TypedDict, closed=True):
    type: Literal["volumeList"]
    status: Literal["normal"]
    value: list[float]


class NormalAngleListPropertyValue(TypedDict, closed=True):
    type: Literal["angleList"]
    status: Literal["normal"]
    value: list[float]


class NormalSingleEnumPropertyValue(TypedDict, closed=True):
    type: Literal["singleEnum"]
    status: Literal["normal"]
    value: EnumValueId


class NormalMultiEnumPropertyValue(TypedDict, closed=True):
    type: Literal["multiEnum"]
    status: Literal["normal"]
    value: EnumValueIds


class ExpressionDefaultValue(TypedDict, closed=True):
    expressions: list[str]


class ClassificationSystemId(TypedDict, closed=True):
    guid: Guid


class ClassificationSystemIdArrayItem(TypedDict, closed=True):
    classificationSystemId: ClassificationSystemId
ClassificationSystemIds: TypeAlias = list[ClassificationSystemIdArrayItem]


class ClassificationItemId(TypedDict, closed=True):
    guid: Guid


class ClassificationItemIdArrayItem(TypedDict, closed=True):
    classificationItemId: ClassificationItemId


class ClassificationId(TypedDict, closed=True):
    classificationSystemId: ClassificationSystemId
    classificationItemId: NotRequired[ClassificationItemId]


class ClassificationIdArrayItem(TypedDict, closed=True):
    classificationId: ClassificationId
ClassificationIdOrError: TypeAlias = ClassificationIdArrayItem | ErrorItem
ClassificationIdsOrErrors: TypeAlias = list[ClassificationIdOrError]


class ElementClassificationItemArray(TypedDict, closed=True):
    classificationIds: ClassificationIdsOrErrors
ElementClassificationOrError: TypeAlias = ElementClassificationItemArray | ErrorItem
ElementClassificationsOrErrors: TypeAlias = list[ElementClassificationOrError]


class BoundingBox3D(TypedDict, closed=True):
    xMin: float
    yMin: float
    zMin: float
    xMax: float
    yMax: float
    zMax: float


class BoundingBox3DArrayItem(TypedDict, closed=True):
    boundingBox3D: BoundingBox3D
BoundingBox3DOrError: TypeAlias = BoundingBox3DArrayItem | ErrorItem
BoundingBoxes3D: TypeAlias = list[BoundingBox3DOrError]


class LibPartUnId(TypedDict, closed=True):
    guid: Guid


class LibPartDetails(TypedDict, closed=True):
    name: str
    parentUnID: LibPartUnId
    ownUnID: LibPartUnId


class NavigatorItemId(TypedDict, closed=True):
    guid: Guid


class DatabaseId(TypedDict, closed=True):
    guid: Guid


class Zoom(TypedDict, closed=True):
    xMin: float
    yMin: float
    xMax: float
    yMax: float


class ViewSettings(TypedDict, closed=True):
    modelViewOptions: NotRequired[str]
    layerCombination: NotRequired[str]
    dimensionStyle: NotRequired[str]
    penSetName: NotRequired[str]
    graphicOverrideCombination: NotRequired[str]
    drawingScale: NotRequired[int]
    saveZoom: NotRequired[bool]
    ignoreSavedZoom: NotRequired[bool]
    zoom: NotRequired[Zoom]
ViewSettingsOrError: TypeAlias = ViewSettings | ErrorItem


class ViewTransformations(TypedDict, closed=True):
    zoom: Zoom
    rotation: float
ViewTransformationsOrError: TypeAlias = ViewTransformations | ErrorItem


class Hole2D(TypedDict, closed=True):
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]
Holes2D: TypeAlias = list[Hole2D]


class Hole3D(TypedDict, closed=True):
    polygonCoordinates: list[Coordinate3D]
    polygonArcs: NotRequired[list[PolyArc]]
Holes3D: TypeAlias = list[Hole3D]


class BeamDetails(TypedDict, closed=True):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    level: float
    offset: float
    slantAngle: float
    arcAngle: float
    verticalCurveHeight: float


class ColumnDetails(TypedDict, closed=True):
    origin: Coordinate2D
    zCoordinate: float
    height: float
    bottomOffset: float


class PolylineDetails(TypedDict, closed=True):
    coordinates: list[Coordinate2D]
    arcs: NotRequired[list[PolyArc]]
    zCoordinate: float


class CurtainWallDetails(TypedDict, closed=True):
    height: NotRequired[float]
    angle: NotRequired[float]


class CurtainWallSegmentDetails(TypedDict, closed=True):
    begCoordinate: Coordinate3D
    endCoordinate: Coordinate3D
    extrusionVector: Coordinate3D
    gridOrigin: Coordinate3D
    gridAngle: float
    arcOrigin: NotRequired[Coordinate3D]
    isNegativeArc: NotRequired[bool]
CurtainWallFrameType: TypeAlias = Literal[
    "Deleted", "Division", "Corner", "Boundary", "Custom"
]


class PanelConnectionHole(TypedDict, closed=True):
    d: float
    w: float


class FrameContour(TypedDict, closed=True):
    a1: float
    a2: float
    b1: float
    b2: float


class CurtainWallFrameDetails(TypedDict, closed=True):
    begCoordinate: Coordinate3D
    endCoordinate: Coordinate3D
    orientationVector: Coordinate3D
    panelConnectionHole: PanelConnectionHole
    frameContour: FrameContour
    segmentIndex: float
    className: str
    type: CurtainWallFrameType
MeshSkirtType: TypeAlias = Literal[
    "SurfaceOnlyWithoutSkirt", "WithSkirt", "SolidBodyWithSkirt"
]


class Subline(TypedDict, closed=True):
    coordinates: list[Coordinate3D]


class MeshDetails(TypedDict, closed=True):
    level: float
    skirtType: MeshSkirtType
    skirtLevel: float
    polygonCoordinates: list[Coordinate3D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes3D]
    sublines: NotRequired[list[Subline]]


class NotYetSupportedElementTypeDetails(TypedDict, closed=True):
    error: str


class RevisionIssueId(TypedDict, closed=True):
    guid: Guid


class DocumentRevisionId(TypedDict, closed=True):
    guid: Guid


class RevisionCustomSchemeDatum(TypedDict, closed=True):
    customSchemeKey: Guid
    customSchemeValue: str
RevisionCustomSchemeData: TypeAlias = list[RevisionCustomSchemeDatum]


class DocumentRevisionReference(TypedDict, closed=True):
    revisionId: DocumentRevisionId
DocumentRevisionReferences: TypeAlias = list[DocumentRevisionReference]


class RevisionIssue(TypedDict, closed=True):
    revisionIssueId: RevisionIssueId
    id: str
    description: str
    issueTime: str
    issuedByUser: str
    overrideRevisionIDOfAllIncludedLayouts: bool
    createNewRevisionInAllIncludedLayouts: bool
    markersVisibleSinceIndex: NotRequired[int]
    isIssued: bool
    documentRevisions: NotRequired[DocumentRevisionReferences]
    customSchemeData: NotRequired[RevisionCustomSchemeData]


class RevisionChange(TypedDict, closed=True):
    id: str
    description: str
    lastModifiedTime: str
    modifiedByUser: str
    isIssued: bool
    firstRevisionIssueId: NotRequired[RevisionIssueId]
    isArchived: bool
    customSchemeData: NotRequired[RevisionCustomSchemeData]


class LayoutInfo(TypedDict, closed=True):
    id: str
    databaseId: DatabaseId
    name: str
    masterLayoutName: str
    width: float
    height: float
    subsetId: str
    subsetName: str
    ownerUser: str
    customSchemeData: NotRequired[RevisionCustomSchemeData]


class Change(TypedDict, closed=True):
    id: str


class DocumentRevision(TypedDict, closed=True):
    revisionId: DocumentRevisionId
    id: str
    finalId: str
    ownerUser: str
    status: Literal["Actual", "Issued"]
    changes: NotRequired[list[Change]]
    layoutInfo: LayoutInfo


class RevisionChangesArrayItem(TypedDict, closed=True):
    revisionChanges: NotRequired[list[RevisionChange]]
RevisionChangesOfEntities: TypeAlias = RevisionChangesArrayItem | ErrorItem


class StoryParameters(TypedDict, closed=True):
    index: int
    floorId: int
    dispOnSections: bool
    level: float
    name: str
StoriesParameters: TypeAlias = list[StoryParameters]


class StorySettings(TypedDict, closed=True):
    dispOnSections: bool
    level: float
    name: str
StoriesSettings: TypeAlias = list[StorySettings]


class AutomaticZoneGeometry(TypedDict, closed=True):
    referencePosition: Coordinate2D


class ManualZoneGeometry(TypedDict, closed=True):
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]
ZoneCreationGeometry: TypeAlias = AutomaticZoneGeometry | ManualZoneGeometry


class WallSettings(TypedDict, closed=True):
    begCoordinate: NotRequired[Coordinate2D]
    endCoordinate: NotRequired[Coordinate2D]
    height: NotRequired[float]
    bottomOffset: NotRequired[float]
    offset: NotRequired[float]
    begThickness: NotRequired[float]
    endThickness: NotRequired[float]
TypeSpecificSettings: TypeAlias = WallSettings


class PropertyGroup(TypedDict, closed=True):
    name: str
    description: NotRequired[str]


class PropertyGroupArrayItem(TypedDict, closed=True):
    propertyGroup: PropertyGroup


class EnumValue(TypedDict, closed=True):
    enumValueId: NotRequired[EnumValueId]
    displayValue: str
    nonLocalizedValue: NotRequired[str]


class PossibleEnumValue(TypedDict, closed=True):
    enumValue: EnumValue


class Group(TypedDict, closed=True):
    propertyGroupId: NotRequired[PropertyGroupId]
    name: NotRequired[str]
Favorites: TypeAlias = list[str]


class BuildingMaterialPhysicalProperties(TypedDict, closed=True):
    thermalConductivity: float
    density: float
    heatCapacity: float
    embodiedEnergy: float
    embodiedCarbon: float


class ProjectInfoField(TypedDict, closed=True):
    projectInfoId: str
    projectInfoName: str
    projectInfoValue: str
LibraryPartType: TypeAlias = Literal[
    "Window",
    "Door",
    "Object",
    "Lamp",
    "Room",
    "Property",
    "PlanSign",
    "Label",
    "Macro",
    "Pict",
    "ListScheme",
    "Skylight",
    "OpeningSymbol",
]


class FavoritesWrapper(TypedDict, closed=True):
    favorites: Favorites
FavoritesOrError: TypeAlias = FavoritesWrapper | ErrorItem


class GroupId(TypedDict, closed=True):
    guid: Guid


class GroupIdArrayItem(TypedDict, closed=True):
    groupId: GroupId
GroupIdOrError: TypeAlias = GroupIdArrayItem | ErrorItem


class GetAddOnVersionResult(TypedDict, closed=True):
    version: str


class GetArchicadLocationResult(TypedDict, closed=True):
    archicadLocation: str
QuitArchicadResult: TypeAlias = ExecutionResult


class GetCurrentWindowTypeResult(TypedDict, closed=True):
    currentWindowType: WindowType


class ChangeWindowParameters(TypedDict, closed=True):
    windowType: WindowType
    databaseId: NotRequired[DatabaseId]
ChangeWindowResult: TypeAlias = ExecutionResult


class GetProjectInfoResult(TypedDict, closed=True):
    isUntitled: bool
    isTeamwork: bool
    projectLocation: NotRequired[str]
    projectPath: NotRequired[str]
    projectName: NotRequired[str]


class SetProjectInfoFieldParameters(TypedDict, closed=True):
    projectInfoId: str
    projectInfoValue: str


class GetStoriesResult(TypedDict, closed=True):
    firstStory: int
    lastStory: int
    actStory: int
    skipNullFloor: bool
    stories: StoriesParameters


class SetStoriesParameters(TypedDict, closed=True):
    stories: StoriesSettings
SetStoriesResult: TypeAlias = ExecutionResult


class OpenProjectParameters(TypedDict, closed=True):
    projectFilePath: str
OpenProjectResult: TypeAlias = ExecutionResult
CloseProjectResult: TypeAlias = ExecutionResult
SaveProjectResult: TypeAlias = ExecutionResult


class Length(TypedDict, closed=True):
    unit: LengthType
    accuracy: AccuracyType
    decimals: int
    roundInch: NotRequired[int]


class Area(TypedDict, closed=True):
    unit: AreaType
    accuracy: AccuracyType
    decimals: int


class Volume(TypedDict, closed=True):
    unit: VolumeType
    accuracy: AccuracyType
    decimals: int


class Angle(TypedDict, closed=True):
    unit: AngleType
    decimals: int
    accuracy: int


class GetCalculationUnitsResult(TypedDict, closed=True):
    length: Length
    area: Area
    volume: Volume
    angle: Angle
SetGeoLocationResult: TypeAlias = ExecutionResult


class IFCFileOperationParameters(TypedDict, closed=True):
    method: Literal["save", "merge", "open"]
    ifcFilePath: str
    fileType: NotRequired[Literal["ifc", "ifcxml", "ifczip", "ifcxmlzip"]]
IFCFileOperationResult: TypeAlias = ExecutionResult


class PrintViewParameters(TypedDict, closed=True):
    grid: NotRequired[bool]
    fixText: NotRequired[bool]
    scale: NotRequired[int]
    printArea: NotRequired[Literal["currentView", "entireDrawing", "marquee"]]
PrintViewResult: TypeAlias = ExecutionResult


class ChangeSelectionOfElementsResult(TypedDict, closed=True):
    executionResultsOfAddToSelection: ExecutionResults
    executionResultsOfRemoveFromSelection: ExecutionResults


class Details(TypedDict, closed=True):
    floorIndex: NotRequired[float]
    layerIndex: NotRequired[float]
    drawIndex: NotRequired[float]
    typeSpecificDetails: NotRequired[TypeSpecificSettings]


class SetDetailsOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class Get3DBoundingBoxesResult(TypedDict, closed=True):
    boundingBoxes3D: BoundingBoxes3D


class Settings(TypedDict, closed=True):
    volumeTolerance: float
    performSurfaceCheck: bool
    surfaceTolerance: float
HighlightElementsResult: TypeAlias = ExecutionResult


class MoveVector(TypedDict, closed=True):
    x: float
    y: float
    z: float


class MoveElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults
DeleteElementsResult: TypeAlias = ExecutionResult


class SetGDLParametersOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetClassificationsOfElementsResult(TypedDict, closed=True):
    elementClassifications: ElementClassificationsOrErrors


class SetClassificationsOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class Level(TypedDict, closed=True):
    levelHeight: float
    levelAngle: float


class ModifyWallsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyBeamsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifySlabsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyColumnsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyWindowsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyDoorsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyMorphsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyRoofsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetElementPreviewImageResult(TypedDict, closed=True):
    previewImage: str


class GetRoomImageResult(TypedDict, closed=True):
    roomImage: str


class SetElementNotificationClientParameters(TypedDict, closed=True):
    host: NotRequired[str]
    port: int
    notifyOnNewElement: NotRequired[bool]
    notifyOnModificationOfAnElement: NotRequired[bool]
    notifyOnReservationChanges: NotRequired[bool]
SetElementNotificationClientResult: TypeAlias = ExecutionResult


class RemoveElementNotificationClientParameters(TypedDict, closed=True):
    host: NotRequired[str]
    port: int
RemoveElementNotificationClientResult: TypeAlias = ExecutionResult


class CreateGroupsResult(TypedDict, closed=True):
    groupGuids: list[GroupIdOrError]


class GetFavoritesByTypeParameters(TypedDict, closed=True):
    elementType: ElementType
GetFavoritesByTypeResult: TypeAlias = FavoritesOrError


class GetFavoritePreviewImageParameters(TypedDict, closed=True):
    favorite: str
    imageType: NotRequired[Literal["2D", "Section", "3D"]]
    format: NotRequired[Literal["png", "jpg"]]
    width: NotRequired[int]
    height: NotRequired[int]


class GetFavoritePreviewImageResult(TypedDict, closed=True):
    previewImage: str


class ApplyFavoritesToElementDefaultsParameters(TypedDict, closed=True):
    favorites: Favorites


class ApplyFavoritesToElementDefaultsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class CreateFavoritesFromElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetAllPropertiesResult(TypedDict, closed=True):
    properties: list[PropertyDetails]


class GetPropertyValuesOfElementsResult(TypedDict, closed=True):
    propertyValuesForElements: PropertyValuesOrErrorArray


class SetPropertyValuesOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetPropertyValuesOfAttributesResult(TypedDict, closed=True):
    propertyValuesForAttributes: PropertyValuesOrErrorArray


class SetPropertyValuesOfAttributesResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class CreatePropertyGroupsParameters(TypedDict, closed=True):
    propertyGroups: list[PropertyGroupArrayItem]


class CreatePropertyGroupsResult(TypedDict, closed=True):
    propertyGroupIds: list[PropertyGroupIdArrayItem]


class DeletePropertyGroupsParameters(TypedDict, closed=True):
    propertyGroupIds: list[PropertyGroupIdArrayItem]


class DeletePropertyGroupsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class CreatePropertyDefinitionsResult(TypedDict, closed=True):
    propertyIds: PropertyIdOrErrorArray


class DeletePropertyDefinitionsParameters(TypedDict, closed=True):
    propertyIds: list[PropertyIdArrayItem]


class DeletePropertyDefinitionsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetAttributesByTypeParameters(TypedDict, closed=True):
    attributeType: AttributeType


class Library(TypedDict, closed=True):
    name: str
    path: str
    type: str
    available: NotRequired[bool]
    readOnly: NotRequired[bool]
    twServerUrl: NotRequired[str]
    urlWebLibrary: NotRequired[str]


class GetLibrariesResult(TypedDict, closed=True):
    libraries: list[Library]
ReloadLibrariesResult: TypeAlias = ExecutionResult


class AddFilesToEmbeddedLibraryResult(TypedDict, closed=True):
    executionResults: ExecutionResults
TeamworkSendResult: TypeAlias = ExecutionResult
TeamworkReceiveResult: TypeAlias = ExecutionResult


class User(TypedDict, closed=True):
    userId: float
    userName: str
ReleaseElementsResult: TypeAlias = ExecutionResult
UpdateDrawingsResult: TypeAlias = ExecutionResult


class DetailsDatum(TypedDict, closed=True):
    name: str
    referenceId: str


class CreateDetailsParameters(TypedDict, closed=True):
    detailsData: list[DetailsDatum]


class WorksheetsDatum(TypedDict, closed=True):
    name: str
    referenceId: str


class CreateWorksheetsParameters(TypedDict, closed=True):
    worksheetsData: list[WorksheetsDatum]


class LayoutsDatum(TypedDict, closed=True):
    masterLayoutName: str
    layoutName: str


class CreateLayoutsParameters(TypedDict, closed=True):
    layoutsData: list[LayoutsDatum]


class SubsetsDatum(TypedDict, closed=True):
    name: str
    parentNavigatorItemId: NotRequired[NavigatorItemId]
    ownPrefix: NotRequired[str]
    customNumber: NotRequired[str]


class CreateSubsetsParameters(TypedDict, closed=True):
    subsetsData: list[SubsetsDatum]


class CreateSubsetsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class DrawingsDatum(TypedDict, closed=True):
    navigatorItemId: NavigatorItemId
    layoutDatabaseId: NotRequired[DatabaseId]
    name: str
    position: Coordinate2D
    scale: NotRequired[float]


class CreateDrawingsParameters(TypedDict, closed=True):
    drawingsData: list[DrawingsDatum]


class ModelViewOption(TypedDict, closed=True):
    name: str


class GetModelViewOptionsResult(TypedDict, closed=True):
    modelViewOptions: list[ModelViewOption]


class GetViewSettingsResult(TypedDict, closed=True):
    viewSettings: list[ViewSettingsOrError]


class NavigatorItemIdsWithViewSetting(TypedDict, closed=True):
    navigatorItemId: NavigatorItemId
    viewSettings: ViewSettings


class SetViewSettingsParameters(TypedDict, closed=True):
    navigatorItemIdsWithViewSettings: list[NavigatorItemIdsWithViewSetting]


class SetViewSettingsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetView2DTransformationsResult(TypedDict, closed=True):
    transformations: list[ViewTransformationsOrError]


class CutPlane(TypedDict, closed=True):
    pa: float
    pb: float
    pc: float
    pd: float


class Set3DCutPlanesParameters(TypedDict, closed=True):
    cutPlanes: NotRequired[list[CutPlane]]
Set3DCutPlanesResult: TypeAlias = ExecutionResult
FitInWindowResult: TypeAlias = ExecutionResult


class CreateIssueParameters(TypedDict, closed=True):
    name: str
    parentIssueId: NotRequired[IssueId]
    tagText: NotRequired[str]


class CreateIssueResult(TypedDict, closed=True):
    issueId: IssueId


class DeleteIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    acceptAllElements: NotRequired[bool]
DeleteIssueResult: TypeAlias = ExecutionResult


class AddCommentToIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    author: NotRequired[str]
    status: NotRequired[IssueCommentStatus]
    text: str
AddCommentToIssueResult: TypeAlias = ExecutionResult


class GetCommentsFromIssueParameters(TypedDict, closed=True):
    issueId: IssueId


class Comment(TypedDict, closed=True):
    guid: Guid
    author: str
    text: str
    status: IssueCommentStatus
    creaTime: int


class GetCommentsFromIssueResult(TypedDict, closed=True):
    comments: list[Comment]
AttachElementsToIssueResult: TypeAlias = ExecutionResult
DetachElementsFromIssueResult: TypeAlias = ExecutionResult


class GetElementsAttachedToIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    type: IssueElementType


class ExportIssuesToBCFParameters(TypedDict, closed=True):
    issues: NotRequired[Issues]
    exportPath: str
    useExternalId: bool
    alignBySurveyPoint: bool
ExportIssuesToBCFResult: TypeAlias = ExecutionResult


class ImportIssuesFromBCFParameters(TypedDict, closed=True):
    importPath: str
    alignBySurveyPoint: bool
ImportIssuesFromBCFResult: TypeAlias = ExecutionResult


class GetRevisionIssuesResult(TypedDict, closed=True):
    revisionIssues: list[RevisionIssue]


class GetRevisionChangesResult(TypedDict, closed=True):
    revisionChanges: list[RevisionChange]


class GetDocumentRevisionsResult(TypedDict, closed=True):
    documentRevisions: list[DocumentRevision]


class GetCurrentRevisionChangesOfLayoutsResult(TypedDict, closed=True):
    currentRevisionChangesOfLayouts: RevisionChangesOfEntities


class GetRevisionChangesOfElementsResult(TypedDict, closed=True):
    revisionChangesOfElements: RevisionChangesOfEntities


class GenerateDocumentationParameters(TypedDict, closed=True):
    destinationFolder: str
GenerateDocumentationResult: TypeAlias = ExecutionResult


class Coordinates(TypedDict, closed=True):
    x: float
    y: float
    z: float


class ColumnData(TypedDict, closed=True):
    coordinates: Coordinates
    height: NotRequired[float]
    axisRotationAngle: NotRequired[float]


class SlabData(TypedDict, closed=True):
    level: float
    thickness: NotRequired[float]
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]


class PolylineData(TypedDict, closed=True):
    floorInd: NotRequired[float]
    layerIndex: NotRequired[int]
    linePenIndex: NotRequired[int]
    lineTypeIndex: NotRequired[int]
    penWeightMm: NotRequired[float]
    coordinates: list[Coordinate2D]
    arcs: NotRequired[list[PolyArc]]


class ObjectData(TypedDict, closed=True):
    libraryPartName: str
    coordinates: Coordinate3D
    dimensions: NotRequired[Dimensions3D]


class MeshData(TypedDict, closed=True):
    floorIndex: NotRequired[int]
    level: NotRequired[float]
    skirtType: NotRequired[MeshSkirtType]
    skirtLevel: NotRequired[float]
    polygonCoordinates: list[Coordinate3D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes3D]
    sublines: NotRequired[list[Subline]]


class BeamData(TypedDict, closed=True):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    offset: NotRequired[float]
    slantAngle: NotRequired[float]
    arcAngle: NotRequired[float]
    verticalCurveHeight: NotRequired[float]


class ProjectLocation(TypedDict, closed=True):
    longitude: float
    latitude: float
    altitude: float
    north: float


class SurveyPointPosition(TypedDict, closed=True):
    eastings: float
    northings: float
    elevation: float


class GeoReferencingParameters(TypedDict, closed=True):
    crsName: str
    description: str
    geodeticDatum: str
    verticalDatum: str
    mapProjection: str
    mapZone: str


class SurveyPoint(TypedDict, closed=True):
    position: SurveyPointPosition
    geoReferencingParameters: GeoReferencingParameters


class ElementId(TypedDict, closed=True):
    guid: Guid


class AttributeId(TypedDict, closed=True):
    guid: Guid


class GuidId(TypedDict, closed=True):
    guid: Guid


class DesignOptionIdArrayItem(TypedDict, closed=True):
    designOptionId: GuidId


class LayersOfLayerCombinationItem(TypedDict, closed=True):
    attributeId: AttributeId
    isHidden: bool
    isLocked: bool
    isWireframe: bool
    intersectionGroupNr: int
LayersOfLayerCombination: TypeAlias = list[LayersOfLayerCombinationItem]


class LayerCombinationAttributeDetails(TypedDict, closed=True):
    attributeId: AttributeId
    attributeIndex: NotRequired[int]
    name: str
    layers: LayersOfLayerCombination


class LayerCombinationAttribute(TypedDict, closed=True):
    layerCombination: LayerCombinationAttributeDetails
LayerCombinationAttributeOrError: TypeAlias = LayerCombinationAttribute | ErrorItem
SetGDLParameterArray: TypeAlias = list[SetGDLParameterDetails]
GDLParameterArray: TypeAlias = list[GDLParameterDetails]


class GDLParameterList(TypedDict, closed=True):
    parameters: GDLParameterArray


class ElementPropertyValue(TypedDict, closed=True):
    elementId: ElementId
    propertyId: PropertyId
    propertyValue: PropertyValue
ElementPropertyValues: TypeAlias = list[ElementPropertyValue]


class AttributePropertyValue(TypedDict, closed=True):
    attributeId: AttributeId
    propertyId: PropertyId
    propertyValue: PropertyValue
AttributePropertyValues: TypeAlias = list[AttributePropertyValue]
NormalOrUserUndefinedPropertyValue: TypeAlias = (
    NormalNumberPropertyValue
    | NormalIntegerPropertyValue
    | NormalStringPropertyValue
    | NormalBooleanPropertyValue
    | NormalLengthPropertyValue
    | NormalAreaPropertyValue
    | NormalVolumePropertyValue
    | NormalAnglePropertyValue
    | NormalNumberListPropertyValue
    | NormalIntegerListPropertyValue
    | NormalStringListPropertyValue
    | NormalBooleanListPropertyValue
    | NormalLengthListPropertyValue
    | NormalAreaListPropertyValue
    | NormalVolumeListPropertyValue
    | NormalAngleListPropertyValue
    | NormalSingleEnumPropertyValue
    | NormalMultiEnumPropertyValue
    | UserUndefinedPropertyValue
)
PropertyValueDetails: TypeAlias = (
    NormalOrUserUndefinedPropertyValue | NotAvailablePropertyValue
)


class BasicDefaultValue(TypedDict, closed=True):
    basicDefaultValue: PropertyValueDetails
PropertyDefaultValue: TypeAlias = BasicDefaultValue | ExpressionDefaultValue


class ElementClassification(TypedDict, closed=True):
    elementId: ElementId
    classificationId: ClassificationId
ElementClassifications: TypeAlias = list[ElementClassification]


class NavigatorItemIdArrayItem(TypedDict, closed=True):
    navigatorItemId: NavigatorItemId


class DatabaseIdArrayItem(TypedDict, closed=True):
    databaseId: DatabaseId


class WallDetails(TypedDict, closed=True):
    geometryType: Literal["Straight", "Trapezoid", "Polygonal"]
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    height: float
    bottomOffset: float
    offset: float
    arcAngle: NotRequired[float]
    begThickness: NotRequired[float]
    endThickness: NotRequired[float]
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]
    structureType: NotRequired[Literal["Basic", "Composite", "Profile"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    profileId: NotRequired[AttributeId]


class SlabDetails(TypedDict, closed=True):
    thickness: float
    level: float
    offsetFromTop: float
    zCoordinate: float
    polygonOutline: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: Holes2D
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]


class LinkData(TypedDict, closed=True):
    referredView: NotRequired[ElementId]
    referredDrawing: NotRequired[ElementId]
    referredPMViewPoint: NotRequired[ElementId]


class DetailWorksheetDetails(TypedDict, closed=True):
    basePoint: Coordinate2D
    angle: float
    markerId: ElementId
    detailName: str
    detailIdStr: str
    isHorizontalMarker: bool
    isWindowOpened: bool
    clipPolygon: list[Coordinate2D]
    linkData: LinkData


class LibPartBasedElementDetails(TypedDict, closed=True):
    libPart: LibPartDetails
    ownerElementId: NotRequired[ElementId]
    ownerElementType: NotRequired[ElementType]


class ObjectDetails(TypedDict, closed=True):
    libPart: LibPartDetails
    ownerElementId: NotRequired[ElementId]
    ownerElementType: NotRequired[ElementType]
    origin: Coordinate3D
    dimensions: Coordinate3D
    angle: float


class ZoneDetails(TypedDict, closed=True):
    name: str
    numberStr: str
    categoryAttributeId: AttributeId
    stampPosition: Coordinate2D
    isManual: bool
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]
    zCoordinate: float


class PropertyDefinition(TypedDict, closed=True):
    name: str
    description: str
    type: PropertyDataType
    isEditable: bool
    defaultValue: NotRequired[PropertyDefaultValue]
    possibleEnumValues: NotRequired[list[PossibleEnumValue]]
    availability: list[ClassificationItemIdArrayItem]
    group: Group


class PropertyDefinitionArrayItem(TypedDict, closed=True):
    propertyDefinition: PropertyDefinition


class ZoneBoundary(TypedDict, closed=True):
    connectedElementId: ElementId
    isExternal: bool
    neighbouringZoneElementId: ElementId
    area: float
    polygonOutline: list[Coordinate3D]


class ZoneBoundariesWrapper(TypedDict, closed=True):
    zoneBoundaries: list[ZoneBoundary]
ZoneBoundariesOrError: TypeAlias = ZoneBoundariesWrapper | ErrorItem


class BuildingMaterialPhysicalPropertiesArrayItem(TypedDict, closed=True):
    properties: BuildingMaterialPhysicalProperties
ProjectInfoFields: TypeAlias = list[ProjectInfoField]


class LibraryFileAddition(TypedDict, closed=True):
    inputPath: str
    outputPath: str
    type: NotRequired[LibraryPartType]


class AttributeHeader(TypedDict, closed=True):
    attributeId: AttributeId
    index: float
    name: str
AttributeHeaders: TypeAlias = list[AttributeHeader]


class AttributeHeadersWrapper(TypedDict, closed=True):
    attributes: AttributeHeaders
AttributeHeadersOrError: TypeAlias = AttributeHeadersWrapper | ErrorItem


class GetProjectInfoFieldsResult(TypedDict, closed=True):
    fields: ProjectInfoFields


class GetGeoLocationResult(TypedDict, closed=True):
    projectLocation: ProjectLocation
    surveyPoint: SurveyPoint


class SetGeoLocationParameters(TypedDict, closed=True):
    projectLocation: NotRequired[ProjectLocation]
    surveyPoint: NotRequired[SurveyPoint]


class ElementsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    details: Details


class SetDetailsOfElementsParameters(TypedDict, closed=True):
    elementsWithDetails: list[ElementsWithDetail]


class GetZoneBoundariesParameters(TypedDict, closed=True):
    zoneElementId: ElementId
GetZoneBoundariesResult: TypeAlias = ZoneBoundariesOrError


class Collision(TypedDict, closed=True):
    elementId1: ElementId
    elementId2: ElementId
    hasBodyCollision: bool
    hasClearenceCollision: bool


class GetCollisionsResult(TypedDict, closed=True):
    collisions: list[Collision]


class ElementsWithMoveVector(TypedDict, closed=True):
    elementId: ElementId
    moveVector: MoveVector
    copy: NotRequired[bool]


class MoveElementsParameters(TypedDict, closed=True):
    elementsWithMoveVectors: list[ElementsWithMoveVector]


class GetGDLParametersOfElementsResult(TypedDict, closed=True):
    gdlParametersOfElements: list[GDLParameterList]


class ElementsWithGDLParameter(TypedDict, closed=True):
    elementId: ElementId
    gdlParameters: SetGDLParameterArray


class SetGDLParametersOfElementsParameters(TypedDict, closed=True):
    elementsWithGDLParameters: list[ElementsWithGDLParameter]


class SetClassificationsOfElementsParameters(TypedDict, closed=True):
    elementClassifications: ElementClassifications


class CreateColumnsParameters(TypedDict, closed=True):
    columnsData: list[ColumnData]


class CreateBeamsParameters(TypedDict, closed=True):
    beamsData: list[BeamData]


class CreateSlabsParameters(TypedDict, closed=True):
    slabsData: list[SlabData]


class WindowsDatum(TypedDict, closed=True):
    ownerWallId: ElementId
    centerOffset: float
    sillHeight: NotRequired[float]
    width: NotRequired[float]
    height: NotRequired[float]


class CreateWindowsParameters(TypedDict, closed=True):
    windowsData: list[WindowsDatum]


class DoorsDatum(TypedDict, closed=True):
    ownerWallId: ElementId
    centerOffset: float
    sillHeight: NotRequired[float]
    width: NotRequired[float]
    height: NotRequired[float]


class CreateDoorsParameters(TypedDict, closed=True):
    doorsData: list[DoorsDatum]


class OpeningsDatum(TypedDict, closed=True):
    ownerElementId: ElementId
    basePoint: Coordinate3D
    width: NotRequired[float]
    height: NotRequired[float]


class CreateOpeningsParameters(TypedDict, closed=True):
    openingsData: list[OpeningsDatum]


class MorphsDatum(TypedDict, closed=True):
    basePoint: Coordinate3D
    size: Dimensions3D
    buildingMaterialId: NotRequired[AttributeId]


class CreateMorphsParameters(TypedDict, closed=True):
    morphsData: list[MorphsDatum]


class RoofsDatum(TypedDict, closed=True):
    level: float
    thickness: NotRequired[float]
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]
    eavesOverhang: NotRequired[float]
    levels: NotRequired[list[Level]]
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]


class CreateRoofsParameters(TypedDict, closed=True):
    roofsData: list[RoofsDatum]


class WitnessPoint(TypedDict, closed=True):
    elementId: ElementId
    line: NotRequired[bool]
    inIndex: NotRequired[int]
    special: NotRequired[int]
    nodeType: NotRequired[int]
    nodeStatus: NotRequired[int]
    nodeId: NotRequired[float]


class DimensionsDatum(TypedDict, closed=True):
    referencePoint: Coordinate2D
    direction: Coordinate2D
    floorIndex: NotRequired[float]
    witnessPoints: list[WitnessPoint]


class CreateAssociativeDimensionsParameters(TypedDict, closed=True):
    dimensionsData: list[DimensionsDatum]


class DimensionsDatum1(TypedDict, closed=True):
    sectionElementId: ElementId
    referencePoint: Coordinate2D
    preset: Literal[
        "WallCompositeFaces",
        "WallSkinBorders",
        "SlabCompositeFaces",
        "SlabSkinBorders",
        "BeamOrColumnRefLineEndPoints",
        "BeamOrColumnBoundingBoxCorners",
        "DoorWindowWallHoleCorners",
        "DoorWindowModelHotspots",
    ]
    direction: NotRequired[Coordinate2D]
    skinBorderIndices: NotRequired[list[int]]
    beginPlane: NotRequired[bool]
    totalSizePlane: NotRequired[bool]
    placeOnTop: NotRequired[bool]


class CreateAssociativeDimensionsOnSectionParameters(TypedDict, closed=True):
    dimensionsData: list[DimensionsDatum1]


class DimensionsDatum2(TypedDict, closed=True):
    wallId: ElementId
    referencePoint: Coordinate2D
    direction: Coordinate2D


class CreateWallThicknessDimensionsParameters(TypedDict, closed=True):
    dimensionsData: list[DimensionsDatum2]


class CreatePolylinesParameters(TypedDict, closed=True):
    polylinesData: list[PolylineData]


class CreateObjectsParameters(TypedDict, closed=True):
    objectsData: list[ObjectData]


class CreateMeshesParameters(TypedDict, closed=True):
    meshesData: list[MeshData]


class WallsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    begCoordinate: NotRequired[Coordinate2D]
    endCoordinate: NotRequired[Coordinate2D]
    height: NotRequired[float]
    thickness: NotRequired[float]
    bottomOffset: NotRequired[float]
    offset: NotRequired[float]
    structureType: NotRequired[Literal["Basic", "Composite", "Profile"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    profileId: NotRequired[AttributeId]


class ModifyWallsParameters(TypedDict, closed=True):
    wallsWithDetails: list[WallsWithDetail]


class BeamsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    begCoordinate: NotRequired[Coordinate2D]
    endCoordinate: NotRequired[Coordinate2D]
    level: NotRequired[float]
    offset: NotRequired[float]
    slantAngle: NotRequired[float]
    arcAngle: NotRequired[float]
    verticalCurveHeight: NotRequired[float]


class ModifyBeamsParameters(TypedDict, closed=True):
    beamsWithDetails: list[BeamsWithDetail]


class SlabsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    zCoordinate: NotRequired[float]
    thickness: NotRequired[float]
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]


class ModifySlabsParameters(TypedDict, closed=True):
    slabsWithDetails: list[SlabsWithDetail]


class ColumnsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    origin: NotRequired[Coordinate2D]
    zCoordinate: NotRequired[float]
    height: NotRequired[float]
    bottomOffset: NotRequired[float]
    axisRotationAngle: NotRequired[float]


class ModifyColumnsParameters(TypedDict, closed=True):
    columnsWithDetails: list[ColumnsWithDetail]


class WindowsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    width: NotRequired[float]
    height: NotRequired[float]
    sillHeight: NotRequired[float]
    centerOffset: NotRequired[float]


class ModifyWindowsParameters(TypedDict, closed=True):
    windowsWithDetails: list[WindowsWithDetail]


class DoorsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    width: NotRequired[float]
    height: NotRequired[float]
    sillHeight: NotRequired[float]
    centerOffset: NotRequired[float]


class ModifyDoorsParameters(TypedDict, closed=True):
    doorsWithDetails: list[DoorsWithDetail]


class MorphsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    translation: NotRequired[Coordinate3D]
    rotationDegreesZ: NotRequired[float]
    buildingMaterialId: NotRequired[AttributeId]


class ModifyMorphsParameters(TypedDict, closed=True):
    morphsWithDetails: list[MorphsWithDetail]


class RoofsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    level: NotRequired[float]
    thickness: NotRequired[float]
    eavesOverhang: NotRequired[float]
    levels: NotRequired[list[Level]]
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]


class ModifyRoofsParameters(TypedDict, closed=True):
    roofsWithDetails: list[RoofsWithDetail]


class GetElementPreviewImageParameters(TypedDict, closed=True):
    elementId: ElementId
    imageType: NotRequired[Literal["2D", "Section", "3D"]]
    format: NotRequired[Literal["png", "jpg"]]
    width: NotRequired[int]
    height: NotRequired[int]


class GetRoomImageParameters(TypedDict, closed=True):
    zoneId: ElementId
    format: NotRequired[Literal["png", "jpg"]]
    width: NotRequired[int]
    height: NotRequired[int]
    offset: NotRequired[float]
    scale: NotRequired[float]
    backgroundColor: NotRequired[ColorRGB]


class FavoritesFromElement(TypedDict, closed=True):
    elementId: ElementId
    favorite: str


class CreateFavoritesFromElementsParameters(TypedDict, closed=True):
    favoritesFromElements: list[FavoritesFromElement]


class SetPropertyValuesOfElementsParameters(TypedDict, closed=True):
    elementPropertyValues: ElementPropertyValues


class SetPropertyValuesOfAttributesParameters(TypedDict, closed=True):
    attributePropertyValues: AttributePropertyValues


class CreatePropertyDefinitionsParameters(TypedDict, closed=True):
    propertyDefinitions: list[PropertyDefinitionArrayItem]
GetAttributesByTypeResult: TypeAlias = AttributeHeadersOrError


class LayerDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    isHidden: NotRequired[bool]
    isLocked: NotRequired[bool]
    isWireframe: NotRequired[bool]
    intersectionGroupNr: NotRequired[int]


class CreateLayersParameters(TypedDict, closed=True):
    layerDataArray: list[LayerDataArrayItem]
    overwriteExisting: NotRequired[bool]


class LayerCombinationDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    layers: LayersOfLayerCombination


class CreateLayerCombinationsParameters(TypedDict, closed=True):
    layerCombinationDataArray: list[LayerCombinationDataArrayItem]
    overwriteExisting: NotRequired[bool]


class BuildingMaterialDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    id: NotRequired[str]
    manufacturer: NotRequired[str]
    description: NotRequired[str]
    connPriority: NotRequired[int]
    cutFillIndex: NotRequired[int]
    cutFillPen: NotRequired[int]
    cutFillBackgroundPen: NotRequired[int]
    cutSurfaceIndex: NotRequired[int]
    thermalConductivity: NotRequired[float]
    density: NotRequired[float]
    heatCapacity: NotRequired[float]
    embodiedEnergy: NotRequired[float]
    embodiedCarbon: NotRequired[float]


class CreateBuildingMaterialsParameters(TypedDict, closed=True):
    buildingMaterialDataArray: list[BuildingMaterialDataArrayItem]
    overwriteExisting: NotRequired[bool]


class GetLayerCombinationsResult(TypedDict, closed=True):
    layerCombinations: list[LayerCombinationAttributeOrError]


class Conflict(TypedDict, closed=True):
    elementId: ElementId
    user: User


class ReserveElementsResult(TypedDict, closed=True):
    executionResult: ExecutionResult
    conflicts: NotRequired[list[Conflict]]


class Issue(TypedDict, closed=True):
    issueId: IssueId
    name: str
    parentIssueId: IssueId
    creaTime: int
    modiTime: int
    tagText: str
    tagTextElementId: ElementId
    isTagTextElemVisible: bool


class GetIssuesResult(TypedDict, closed=True):
    issues: list[Issue]


class DesignOption(TypedDict, closed=True):
    designOptionId: GuidId
    name: str
    id: str
    ownerSetName: str


class GetDesignOptionsResult(TypedDict, closed=True):
    designOptions: list[DesignOption]


class DesignOptionSet(TypedDict, closed=True):
    designOptionSetId: GuidId
    name: str
    designOptions: list[DesignOptionIdArrayItem]


class GetDesignOptionSetsResult(TypedDict, closed=True):
    designOptionSets: list[DesignOptionSet]


class DesignOptionCombination(TypedDict, closed=True):
    designOptionCombinationId: GuidId
    name: str
    activeDesignOptions: NotRequired[list[DesignOptionIdArrayItem]]


class GetDesignOptionCombinationsResult(TypedDict, closed=True):
    designOptionCombinations: list[DesignOptionCombination]


class ZoneData(TypedDict, closed=True):
    floorIndex: NotRequired[float]
    name: str
    numberStr: str
    categoryAttributeId: NotRequired[AttributeId]
    stampPosition: NotRequired[Coordinate2D]
    geometry: ZoneCreationGeometry


class WallData(TypedDict, closed=True):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    height: float
    thickness: float
    offset: NotRequired[float]
    structureType: NotRequired[Literal["Basic", "Composite", "Profile"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    profileId: NotRequired[AttributeId]


class LabelData(TypedDict, closed=True):
    parentElementId: NotRequired[ElementId]
    text: NotRequired[str]
    begCoordinate: NotRequired[Coordinate2D]
    floorInd: NotRequired[float]


class ElementIdArrayItem(TypedDict, closed=True):
    elementId: ElementId


class AttributeIdArrayItem(TypedDict, closed=True):
    attributeId: AttributeId
NavigatorItemIds: TypeAlias = list[NavigatorItemIdArrayItem]
Databases: TypeAlias = list[DatabaseIdArrayItem]


class CurtainWallPanelDetails(TypedDict, closed=True):
    polygonCoordinates: list[Coordinate3D]
    isHidden: bool
    segmentIndex: float
    className: str
    frames: list[ElementIdArrayItem]
TypeSpecificDetails: TypeAlias = (
    WallDetails
    | BeamDetails
    | SlabDetails
    | ColumnDetails
    | DetailWorksheetDetails
    | LibPartBasedElementDetails
    | PolylineDetails
    | ZoneDetails
    | CurtainWallDetails
    | CurtainWallSegmentDetails
    | CurtainWallPanelDetails
    | CurtainWallFrameDetails
    | MeshDetails
    | NotYetSupportedElementTypeDetails
)
BuildingMaterialPhysicalPropertiesList: TypeAlias = list[
    BuildingMaterialPhysicalPropertiesArrayItem
]
LibraryFileAdditions: TypeAlias = list[LibraryFileAddition]
ElementOrGroupId: TypeAlias = ElementIdArrayItem | GroupIdArrayItem
ElementOrGroupIds: TypeAlias = list[ElementOrGroupId]


class ElementGroupParameters(TypedDict, closed=True):
    elements: ElementOrGroupIds
    parentGroupId: NotRequired[GroupId]


class GetElementsByTypeParameters(TypedDict, closed=True):
    elementType: ElementType
    filters: NotRequired[list[ElementFilter]]
    databases: NotRequired[Databases]


class GetAllElementsParameters(TypedDict, closed=True):
    filters: NotRequired[list[ElementFilter]]
    databases: NotRequired[Databases]


class DetailsOfElement(TypedDict, closed=True):
    type: ElementType
    id: str
    floorIndex: float
    layerIndex: float
    drawIndex: float
    details: TypeSpecificDetails


class GetDetailsOfElementsResult(TypedDict, closed=True):
    detailsOfElements: list[DetailsOfElement]


class CreateWallsParameters(TypedDict, closed=True):
    wallsData: list[WallData]


class CreateZonesParameters(TypedDict, closed=True):
    zonesData: list[ZoneData]


class CreateLabelsParameters(TypedDict, closed=True):
    labelsData: list[LabelData]


class CreateGroupsParameters(TypedDict, closed=True):
    elementGroups: list[ElementGroupParameters]


class Skin(TypedDict, closed=True):
    type: str
    buildingMaterialId: AttributeIdArrayItem
    framePen: int
    thickness: float


class Separator(TypedDict, closed=True):
    lineTypeId: AttributeIdArrayItem
    linePen: int


class CompositeDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    useWith: NotRequired[list[str]]
    skins: list[Skin]
    separators: list[Separator]


class CreateCompositesParameters(TypedDict, closed=True):
    compositeDataArray: list[CompositeDataArrayItem]
    overwriteExisting: NotRequired[bool]


class SurfaceDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    materialType: SurfaceType
    ambientReflection: float
    diffuseReflection: float
    specularReflection: float
    transparency: float
    shine: float
    transparencyAttenuation: float
    emissionAttenuation: float
    surfaceColor: ColorRGB
    specularColor: ColorRGB
    emissionColor: ColorRGB
    fillId: NotRequired[AttributeIdArrayItem]
    texture: NotRequired[Texture]


class CreateSurfacesParameters(TypedDict, closed=True):
    surfaceDataArray: list[SurfaceDataArrayItem]
    overwriteExisting: NotRequired[bool]


class GetBuildingMaterialPhysicalPropertiesResult(TypedDict, closed=True):
    properties: BuildingMaterialPhysicalPropertiesList


class AddFilesToEmbeddedLibraryParameters(TypedDict, closed=True):
    files: LibraryFileAdditions


class PublishPublisherSetParameters(TypedDict, closed=True):
    publisherSetName: str
    outputPath: NotRequired[str]
    selectedNavigatorItemIds: NotRequired[NavigatorItemIds]


class GetDatabaseIdFromNavigatorItemIdParameters(TypedDict, closed=True):
    navigatorItemIds: NavigatorItemIds


class GetDatabaseIdFromNavigatorItemIdResult(TypedDict, closed=True):
    databases: Databases


class CreateDetailsResult(TypedDict, closed=True):
    databases: Databases


class CreateWorksheetsResult(TypedDict, closed=True):
    databases: Databases


class CreateLayoutsResult(TypedDict, closed=True):
    databases: Databases


class GetViewSettingsParameters(TypedDict, closed=True):
    navigatorItemIds: NavigatorItemIds


class GetView2DTransformationsParameters(TypedDict, closed=True):
    databases: NotRequired[Databases]


class GetCurrentRevisionChangesOfLayoutsParameters(TypedDict, closed=True):
    layoutDatabaseIds: Databases
Elements: TypeAlias = list[ElementIdArrayItem]
AttributeIds: TypeAlias = list[AttributeIdArrayItem]


class ElementsWithExecutionResults(TypedDict, closed=True):
    elements: Elements
    executionResultForDatabases: NotRequired[ExecutionResults]
ElementsWithExecutionResultsOrError: TypeAlias = (
    ElementsWithExecutionResults | ErrorItem
)


class ConnectedElement(TypedDict, closed=True):
    elements: Elements


class ConnectedElementsWrapper(TypedDict, closed=True):
    connectedElements: list[ConnectedElement]
ConnectedElementsOrError: TypeAlias = ConnectedElementsWrapper | ErrorItem


class GetSelectedElementsResult(TypedDict, closed=True):
    elements: Elements
GetElementsByTypeResult: TypeAlias = ElementsWithExecutionResultsOrError
GetAllElementsResult: TypeAlias = ElementsWithExecutionResultsOrError


class ChangeSelectionOfElementsParameters(TypedDict, closed=True):
    addElementsToSelection: NotRequired[Elements]
    removeElementsFromSelection: NotRequired[Elements]


class FilterElementsParameters(TypedDict, closed=True):
    elements: Elements
    filters: NotRequired[list[ElementFilter]]


class FilterElementsResult(TypedDict, closed=True):
    elements: Elements


class GetDetailsOfElementsParameters(TypedDict, closed=True):
    elements: Elements


class Get3DBoundingBoxesParameters(TypedDict, closed=True):
    elements: Elements


class GetSubelementsOfHierarchicalElementsParameters(TypedDict, closed=True):
    elements: Elements


class Subelement(TypedDict, closed=True):
    cWallSegments: NotRequired[Elements]
    cWallFrames: NotRequired[Elements]
    cWallPanels: NotRequired[Elements]
    cWallJunctions: NotRequired[Elements]
    cWallAccessories: NotRequired[Elements]
    stairRisers: NotRequired[Elements]
    stairTreads: NotRequired[Elements]
    stairStructures: NotRequired[Elements]
    railingNodes: NotRequired[Elements]
    railingSegments: NotRequired[Elements]
    railingPosts: NotRequired[Elements]
    railingRailEnds: NotRequired[Elements]
    railingRailConnections: NotRequired[Elements]
    railingHandrailEnds: NotRequired[Elements]
    railingHandrailConnections: NotRequired[Elements]
    railingToprailEnds: NotRequired[Elements]
    railingToprailConnections: NotRequired[Elements]
    railingRails: NotRequired[Elements]
    railingToprails: NotRequired[Elements]
    railingHandrails: NotRequired[Elements]
    railingPatterns: NotRequired[Elements]
    railingInnerPosts: NotRequired[Elements]
    railingPanels: NotRequired[Elements]
    railingBalusterSets: NotRequired[Elements]
    railingBalusters: NotRequired[Elements]
    beamSegments: NotRequired[Elements]
    columnSegments: NotRequired[Elements]


class GetSubelementsOfHierarchicalElementsResult(TypedDict, closed=True):
    subelements: list[Subelement]


class GetConnectedElementsParameters(TypedDict, closed=True):
    elements: Elements
    connectedElementType: ElementType
GetConnectedElementsResult: TypeAlias = ConnectedElementsOrError


class GetCollisionsParameters(TypedDict, closed=True):
    elementsGroup1: Elements
    elementsGroup2: Elements
    settings: NotRequired[Settings]


class HighlightElementsParameters(TypedDict, closed=True):
    elements: Elements
    highlightedColors: list[list[int]]
    wireframe3D: NotRequired[bool]
    nonHighlightedColor: NotRequired[list[int]]


class DeleteElementsParameters(TypedDict, closed=True):
    elements: Elements


class GetGDLParametersOfElementsParameters(TypedDict, closed=True):
    elements: Elements


class GetClassificationsOfElementsParameters(TypedDict, closed=True):
    elements: Elements
    classificationSystemIds: ClassificationSystemIds


class CreateColumnsResult(TypedDict, closed=True):
    elements: Elements


class CreateWallsResult(TypedDict, closed=True):
    elements: Elements


class CreateBeamsResult(TypedDict, closed=True):
    elements: Elements


class CreateSlabsResult(TypedDict, closed=True):
    elements: Elements


class CreateWindowsResult(TypedDict, closed=True):
    elements: Elements


class CreateDoorsResult(TypedDict, closed=True):
    elements: Elements


class CreateOpeningsResult(TypedDict, closed=True):
    elements: Elements


class CreateMorphsResult(TypedDict, closed=True):
    elements: Elements


class CreateRoofsResult(TypedDict, closed=True):
    elements: Elements


class CreateAssociativeDimensionsResult(TypedDict, closed=True):
    elements: Elements


class CreateAssociativeDimensionsOnSectionResult(TypedDict, closed=True):
    elements: Elements


class CreateWallThicknessDimensionsResult(TypedDict, closed=True):
    elements: Elements


class CreateZonesResult(TypedDict, closed=True):
    elements: Elements


class CreatePolylinesResult(TypedDict, closed=True):
    elements: Elements


class CreateObjectsResult(TypedDict, closed=True):
    elements: Elements


class CreateMeshesResult(TypedDict, closed=True):
    elements: Elements


class CreateLabelsResult(TypedDict, closed=True):
    elements: Elements


class GetPropertyValuesOfElementsParameters(TypedDict, closed=True):
    elements: Elements
    properties: PropertyIds


class GetPropertyValuesOfAttributesParameters(TypedDict, closed=True):
    attributeIds: AttributeIds
    properties: PropertyIds


class CreateLayersResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateLayerCombinationsResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateBuildingMaterialsResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateCompositesResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateSurfacesResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class GetBuildingMaterialPhysicalPropertiesParameters(TypedDict, closed=True):
    attributeIds: AttributeIds


class GetLayerCombinationsParameters(TypedDict, closed=True):
    attributes: AttributeIds


class ReserveElementsParameters(TypedDict, closed=True):
    elements: Elements


class ReleaseElementsParameters(TypedDict, closed=True):
    elements: Elements


class UpdateDrawingsParameters(TypedDict, closed=True):
    elements: Elements


class CreateDrawingsResult(TypedDict, closed=True):
    elements: Elements


class FitInWindowParameters(TypedDict, closed=True):
    elements: NotRequired[Elements]


class AttachElementsToIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    elements: Elements
    type: IssueElementType


class DetachElementsFromIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    elements: Elements


class GetElementsAttachedToIssueResult(TypedDict, closed=True):
    elements: Elements


class GetRevisionChangesOfElementsParameters(TypedDict, closed=True):
    elements: Elements
Hotlinks: TypeAlias = list["Hotlink"]


class Hotlink(TypedDict, closed=True):
    location: str
    children: NotRequired[Hotlinks]


class GetHotlinksResult(TypedDict, closed=True):
    hotlinks: Hotlinks
