from __future__ import annotations
from typing import Annotated, Any, List, Literal, TypeAlias
from uuid import UUID
from enum import Enum
from pydantic import Field

from multiconn_archicad.models.base import APIModel

### This file is automatically generated and split. Do not edit directly. ###


class SurfaceType(Enum):
    General = "General"
    Simple = "Simple"
    Matte = "Matte"
    Metal = "Metal"
    Plastic = "Plastic"
    Glass = "Glass"
    Glowing = "Glowing"
    Constant = "Constant"


class AttributeType(Enum):
    Layer = "Layer"
    Line = "Line"
    Fill = "Fill"
    Composite = "Composite"
    Surface = "Surface"
    LayerCombination = "LayerCombination"
    ZoneCategory = "ZoneCategory"
    Profile = "Profile"
    PenTable = "PenTable"
    MEPSystem = "MEPSystem"
    OperationProfile = "OperationProfile"
    BuildingMaterial = "BuildingMaterial"


class PossibleNumericValue(APIModel):
    value: Annotated[float, Field(description="The numeric value.")]
    flag: Annotated[str | None, Field(description="The flag.")] = None
    description: Annotated[str | None, Field(description="The description of the value.")] = None


class Flag(Enum):
    Hidden = "Hidden"
    HiddenFromScript = "HiddenFromScript"
    Disabled = "Disabled"
    Child = "Child"
    Unique = "Unique"
    Fixed = "Fixed"


class GDLParameterDetails(APIModel):
    name: Annotated[str, Field(description="The name of the parameter.")]
    displayName: Annotated[str, Field(description="The display name of the parameter.")]
    index: Annotated[int, Field(description="The index of the parameter.")]
    type: Annotated[str, Field(description="The type of the parameter.")]
    dimension1: Annotated[int, Field(description="The 1st dimension of array (in case of array value).")]
    dimension2: Annotated[int, Field(description="The 2nd dimension of array (in case of array value).")]
    value: Annotated[Any, Field(description="The value of the parameter.")]
    valueDescription: Annotated[str | None, Field(description="The value description for numeric parameter.")] = None
    isLocked: Annotated[
        bool,
        Field(description="The parameter is locked; i.e. the user cannot modify it"),
    ]
    flags: Annotated[list[Flag], Field(description="The flags of the parameter.")]
    possibleValues: list[str] | list[PossibleNumericValue] | None = None
    canHaveCustomValue: Annotated[bool | None, Field(description="The parameter can have a custom value.")] = None


class SetGDLParameterByNameDetails(APIModel):
    name: Annotated[str, Field(description="The name of the parameter.")]
    value: Annotated[Any, Field(description="The value of the parameter.")]


class SetGDLParameterByIndexDetails(APIModel):
    index: Annotated[int, Field(description="The index of the parameter.")]
    value: Annotated[Any, Field(description="The value of the parameter.")]


class PolyArc(APIModel):
    begIndex: Annotated[int, Field(description="Node index of one end point of the arc.")]
    endIndex: Annotated[int, Field(description="Node index of the other end point of the arc.")]
    arcAngle: Annotated[
        float,
        Field(
            description="Angle of the arc; it is positive, if the arc is on the right-hand side of the straight segment."
        ),
    ]


class Coordinate2D(APIModel):
    x: Annotated[float, Field(description="X value of the coordinate.")]
    y: Annotated[float, Field(description="Y value of the coordinate.")]


class Coordinate3D(APIModel):
    x: Annotated[float, Field(description="X value of the coordinate.")]
    y: Annotated[float, Field(description="Y value of the coordinate.")]
    z: Annotated[float, Field(description="Z value of the coordinate.")]


class Dimensions3D(APIModel):
    x: Annotated[float, Field(description="X dimension.")]
    y: Annotated[float, Field(description="Y dimension.")]
    z: Annotated[float, Field(description="Z dimension.")]


class ColorRGB(APIModel):
    red: Annotated[float, Field(description="Red value between 0.0 and 1.0")]
    green: Annotated[float, Field(description="Green value between 0.0 and 1.0")]
    blue: Annotated[float, Field(description="Blue value between 0.0 and 1.0")]


class Texture(APIModel):
    name: Annotated[
        str,
        Field(description="The filename of the texture in the library (without extension)."),
    ]
    rotationAngle: Annotated[float | None, Field(description="Rotation angle in radians.")] = None
    xSize: Annotated[
        float | None,
        Field(description="X size of the picture in model space, by default 1."),
    ] = None
    ySize: Annotated[
        float | None,
        Field(description="Y size of the picture in model space, by default 1."),
    ] = None
    FillRectangle: Annotated[
        bool | None,
        Field(
            description="True, if fit the rectangle with the picture in a central position, using the natural aspect ratio of the picture."
        ),
    ] = None
    FitPicture: Annotated[
        bool | None,
        Field(
            description="True, if fit the picture in the middle of the rectangle, using the natural aspect ratio of the picture."
        ),
    ] = None
    mirrorX: Annotated[
        bool | None,
        Field(description="True, if the texture is mirrored in X direction."),
    ] = None
    mirrorY: Annotated[
        bool | None,
        Field(description="True, if the texture is mirrored in Y direction."),
    ] = None
    useAlphaChannel: Annotated[
        bool | None,
        Field(description="True, if the alpha channel of the texture is used."),
    ] = None
    alphaChannelChangesTransparency: Annotated[
        bool | None,
        Field(description="True, if the alpha channel of the texture changes the transparency."),
    ] = None
    alphaChannelChangesSurfaceColor: Annotated[
        bool | None,
        Field(description="True, if the alpha channel of the texture changes the surface color."),
    ] = None
    alphaChannelChangesAmbientColor: Annotated[
        bool | None,
        Field(description="True, if the alpha channel of the texture changes the ambient color."),
    ] = None
    alphaChannelChangesSpecularColor: Annotated[
        bool | None,
        Field(description="True, if the alpha channel of the texture changes the specular color."),
    ] = None
    alphaChannelChangesDiffuseColor: Annotated[
        bool | None,
        Field(description="True, if the alpha channel of the texture changes the diffuse color."),
    ] = None


class Error(APIModel):
    code: Annotated[int, Field(description="The code of the error.")]
    message: Annotated[str, Field(description="The error message.")]


class ErrorItem(APIModel):
    error: Error


class SuccessfulExecutionResult(APIModel):
    success: Literal[True] = True


class FailedExecutionResult(APIModel):
    success: Literal[False] = False
    error: Annotated[Error, Field(description="The details of an execution failure.")]


class ElementType(Enum):
    Wall = "Wall"
    Column = "Column"
    Beam = "Beam"
    Window = "Window"
    Door = "Door"
    Object = "Object"
    Lamp = "Lamp"
    Slab = "Slab"
    Roof = "Roof"
    Mesh = "Mesh"
    Dimension = "Dimension"
    RadialDimension = "RadialDimension"
    LevelDimension = "LevelDimension"
    AngleDimension = "AngleDimension"
    Text = "Text"
    Label = "Label"
    Zone = "Zone"
    Hatch = "Hatch"
    Line = "Line"
    PolyLine = "PolyLine"
    Arc = "Arc"
    Circle = "Circle"
    Spline = "Spline"
    Hotspot = "Hotspot"
    CutPlane = "CutPlane"
    Camera = "Camera"
    CamSet = "CamSet"
    Group = "Group"
    SectElem = "SectElem"
    Drawing = "Drawing"
    Picture = "Picture"
    Detail = "Detail"
    Elevation = "Elevation"
    InteriorElevation = "InteriorElevation"
    Worksheet = "Worksheet"
    Hotlink = "Hotlink"
    CurtainWall = "CurtainWall"
    CurtainWallSegment = "CurtainWallSegment"
    CurtainWallFrame = "CurtainWallFrame"
    CurtainWallPanel = "CurtainWallPanel"
    CurtainWallJunction = "CurtainWallJunction"
    CurtainWallAccessory = "CurtainWallAccessory"
    Shell = "Shell"
    Skylight = "Skylight"
    Morph = "Morph"
    ChangeMarker = "ChangeMarker"
    Stair = "Stair"
    Riser = "Riser"
    Tread = "Tread"
    StairStructure = "StairStructure"
    Railing = "Railing"
    RailingToprail = "RailingToprail"
    RailingHandrail = "RailingHandrail"
    RailingRail = "RailingRail"
    RailingPost = "RailingPost"
    RailingInnerPost = "RailingInnerPost"
    RailingBaluster = "RailingBaluster"
    RailingPanel = "RailingPanel"
    RailingSegment = "RailingSegment"
    RailingNode = "RailingNode"
    RailingBalusterSet = "RailingBalusterSet"
    RailingPattern = "RailingPattern"
    RailingToprailEnd = "RailingToprailEnd"
    RailingHandrailEnd = "RailingHandrailEnd"
    RailingRailEnd = "RailingRailEnd"
    RailingToprailConnection = "RailingToprailConnection"
    RailingHandrailConnection = "RailingHandrailConnection"
    RailingRailConnection = "RailingRailConnection"
    RailingEndFinish = "RailingEndFinish"
    BeamSegment = "BeamSegment"
    ColumnSegment = "ColumnSegment"
    Opening = "Opening"
    Unknown = "Unknown"


class ElementFilter(Enum):
    IsEditable = "IsEditable"
    IsVisibleByLayer = "IsVisibleByLayer"
    IsVisibleByRenovation = "IsVisibleByRenovation"
    IsVisibleByStructureDisplay = "IsVisibleByStructureDisplay"
    IsVisibleIn3D = "IsVisibleIn3D"
    OnActualFloor = "OnActualFloor"
    OnActualLayout = "OnActualLayout"
    InMyWorkspace = "InMyWorkspace"
    IsIndependent = "IsIndependent"
    InCroppedView = "InCroppedView"
    HasAccessRight = "HasAccessRight"
    IsOverriddenByRenovation = "IsOverriddenByRenovation"


class WindowType(Enum):
    FloorPlan = "FloorPlan"
    Section = "Section"
    Details = "Details"
    field_3DModel = "3DModel"
    Layout = "Layout"
    Drawing = "Drawing"
    CustomText = "CustomText"
    CustomDraw = "CustomDraw"
    MasterLayout = "MasterLayout"
    Elevation = "Elevation"
    InteriorElevation = "InteriorElevation"
    Worksheet = "Worksheet"
    Report = "Report"
    field_3DDocument = "3DDocument"
    External3D = "External3D"
    Movie3D = "Movie3D"
    MovieRendering = "MovieRendering"
    Rendering = "Rendering"
    ModelCompare = "ModelCompare"
    Interactive_Schedule = "Interactive Schedule"
    Unknown = "Unknown"


class LengthType(Enum):
    Meter = "Meter"
    Decimeter = "Decimeter"
    Centimeter = "Centimeter"
    Millimeter = "Millimeter"
    FootFracInch = "FootFracInch"
    FootDecInch = "FootDecInch"
    DecFoot = "DecFoot"
    FracInch = "FracInch"
    DecInch = "DecInch"


class AreaType(Enum):
    SquareMeter = "SquareMeter"
    SquareCentimeter = "SquareCentimeter"
    SquareMillimeter = "SquareMillimeter"
    SquareFoot = "SquareFoot"
    SquareInch = "SquareInch"


class VolumeType(Enum):
    CubicMeter = "CubicMeter"
    Liter = "Liter"
    CubicCentimeter = "CubicCentimeter"
    CubicMillimeter = "CubicMillimeter"
    CubicFoot = "CubicFoot"
    CubicInch = "CubicInch"
    CubicYard = "CubicYard"
    Gallon = "Gallon"


class AngleType(Enum):
    DecimalDegree = "DecimalDegree"
    DegreeMinSec = "DegreeMinSec"
    Grad = "Grad"
    Radian = "Radian"
    Surveyors = "Surveyors"


class AccuracyType(Enum):
    Off = "Off"
    ShowSmall5 = "ShowSmall5"
    ShowSmall25 = "ShowSmall25"
    ShowSmall1 = "ShowSmall1"
    ShowSmall01 = "ShowSmall01"
    InchCaseFractions = "InchCaseFractions"


class IssueId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class IssueIdArrayItem(APIModel):
    issueId: IssueId


class IssueElementType(Enum):
    Creation = "Creation"
    Highlight = "Highlight"
    Deletion = "Deletion"
    Modification = "Modification"


class IssueCommentStatus(Enum):
    Error = "Error"
    Warning = "Warning"
    Info = "Info"
    Unknown = "Unknown"


class PropertyGroupId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class PropertyGroupIdArrayItem(APIModel):
    propertyGroupId: PropertyGroupId


class PropertyId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class PropertyIdArrayItem(APIModel):
    propertyId: PropertyId


class PropertyType(Enum):
    StaticBuiltIn = "StaticBuiltIn"
    DynamicBuiltIn = "DynamicBuiltIn"
    Custom = "Custom"


class PropertyCollectionType(Enum):
    Undefined = "Undefined"
    Single = "Single"
    List = "List"
    SingleChoiceEnumeration = "SingleChoiceEnumeration"
    MultipleChoiceEnumeration = "MultipleChoiceEnumeration"


class PropertyValueType(Enum):
    Undefined = "Undefined"
    Integer = "Integer"
    Real = "Real"
    String = "String"
    Boolean = "Boolean"
    Guid = "Guid"


class PropertyMeasureType(Enum):
    Undefined = "Undefined"
    Default = "Default"
    Length = "Length"
    Area = "Area"
    Volume = "Volume"
    Angle = "Angle"


class PropertyDetails(APIModel):
    propertyId: PropertyId
    propertyType: PropertyType
    propertyGroupName: str
    propertyName: str
    propertyCollectionType: PropertyCollectionType
    propertyValueType: PropertyValueType
    propertyMeasureType: PropertyMeasureType
    propertyIsEditable: bool


class PropertyValue(APIModel):
    value: str


class PropertyValueArrayItem(APIModel):
    propertyValue: PropertyValue


class PropertyValuesArrayItem(APIModel):
    propertyValues: Annotated[
        list[PropertyValueArrayItem | ErrorItem],
        Field(description="A list of property values."),
    ]


class PropertyDataType(Enum):
    number = "number"
    integer = "integer"
    string = "string"
    boolean = "boolean"
    length = "length"
    area = "area"
    volume = "volume"
    angle = "angle"
    numberList = "numberList"
    integerList = "integerList"
    stringList = "stringList"
    booleanList = "booleanList"
    lengthList = "lengthList"
    areaList = "areaList"
    volumeList = "volumeList"
    angleList = "angleList"
    singleEnum = "singleEnum"
    multiEnum = "multiEnum"


class DisplayValueEnumId(APIModel):
    type: Literal["displayValue"] = "displayValue"
    displayValue: str


class NonLocalizedValueEnumId(APIModel):
    type: Literal["nonLocalizedValue"] = "nonLocalizedValue"
    nonLocalizedValue: str


class EnumValueIdArrayItem(APIModel):
    enumValueId: Annotated[
        DisplayValueEnumId | NonLocalizedValueEnumId,
        Field(description="The identifier of a property enumeration value."),
    ]


class UserUndefinedPropertyValue(APIModel):
    type: PropertyDataType
    status: Literal["userUndefined"] = "userUndefined"


class NotAvailablePropertyValue(APIModel):
    type: PropertyDataType
    status: Literal["notAvailable"] = "notAvailable"


class NormalNumberPropertyValue(APIModel):
    type: Literal["number"] = "number"
    status: Literal["normal"] = "normal"
    value: float


class NormalIntegerPropertyValue(APIModel):
    type: Literal["integer"] = "integer"
    status: Literal["normal"] = "normal"
    value: int


class NormalStringPropertyValue(APIModel):
    type: Literal["string"] = "string"
    status: Literal["normal"] = "normal"
    value: str


class NormalBooleanPropertyValue(APIModel):
    type: Literal["boolean"] = "boolean"
    status: Literal["normal"] = "normal"
    value: bool


class NormalLengthPropertyValue(APIModel):
    type: Literal["length"] = "length"
    status: Literal["normal"] = "normal"
    value: float


class NormalAreaPropertyValue(APIModel):
    type: Literal["area"] = "area"
    status: Literal["normal"] = "normal"
    value: float


class NormalVolumePropertyValue(APIModel):
    type: Literal["volume"] = "volume"
    status: Literal["normal"] = "normal"
    value: float


class NormalAnglePropertyValue(APIModel):
    type: Literal["angle"] = "angle"
    status: Literal["normal"] = "normal"
    value: float


class NormalNumberListPropertyValue(APIModel):
    type: Literal["numberList"] = "numberList"
    status: Literal["normal"] = "normal"
    value: list[float]


class NormalIntegerListPropertyValue(APIModel):
    type: Literal["integerList"] = "integerList"
    status: Literal["normal"] = "normal"
    value: list[int]


class NormalStringListPropertyValue(APIModel):
    type: Literal["stringList"] = "stringList"
    status: Literal["normal"] = "normal"
    value: list[str]


class NormalBooleanListPropertyValue(APIModel):
    type: Literal["booleanList"] = "booleanList"
    status: Literal["normal"] = "normal"
    value: list[bool]


class NormalLengthListPropertyValue(APIModel):
    type: Literal["lengthList"] = "lengthList"
    status: Literal["normal"] = "normal"
    value: list[float]


class NormalAreaListPropertyValue(APIModel):
    type: Literal["areaList"] = "areaList"
    status: Literal["normal"] = "normal"
    value: list[float]


class NormalVolumeListPropertyValue(APIModel):
    type: Literal["volumeList"] = "volumeList"
    status: Literal["normal"] = "normal"
    value: list[float]


class NormalAngleListPropertyValue(APIModel):
    type: Literal["angleList"] = "angleList"
    status: Literal["normal"] = "normal"
    value: list[float]


class NormalSingleEnumPropertyValue(APIModel):
    type: Literal["singleEnum"] = "singleEnum"
    status: Literal["normal"] = "normal"
    value: Annotated[
        DisplayValueEnumId | NonLocalizedValueEnumId,
        Field(description="The identifier of a property enumeration value."),
    ]


class NormalMultiEnumPropertyValue(APIModel):
    type: Literal["multiEnum"] = "multiEnum"
    status: Literal["normal"] = "normal"
    value: Annotated[
        list[EnumValueIdArrayItem],
        Field(description="A list of enumeration identifiers."),
    ]


class ExpressionDefaultValue(APIModel):
    expressions: list[str]


class ClassificationSystemId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class ClassificationSystemIdArrayItem(APIModel):
    classificationSystemId: ClassificationSystemId


class ClassificationItemId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class ClassificationItemIdArrayItem(APIModel):
    classificationItemId: ClassificationItemId


class ClassificationId(APIModel):
    classificationSystemId: ClassificationSystemId
    classificationItemId: Annotated[
        ClassificationItemId | None,
        Field(
            description="The element's classification in the given system. If no value is specified here, the element is Unclassified in this system."
        ),
    ] = None


class ClassificationIdArrayItem(APIModel):
    classificationId: ClassificationId


class ElementClassificationItemArray(APIModel):
    classificationIds: Annotated[
        list[ClassificationIdArrayItem | ErrorItem],
        Field(description="A list of element classification identifiers or errors."),
    ]


class BoundingBox3D(APIModel):
    xMin: Annotated[float, Field(description="The minimum X value of the bounding box.")]
    yMin: Annotated[float, Field(description="The minimum Y value of the bounding box.")]
    zMin: Annotated[float, Field(description="The minimum Z value of the bounding box.")]
    xMax: Annotated[float, Field(description="The maximum X value of the bounding box.")]
    yMax: Annotated[float, Field(description="The maximum Y value of the bounding box.")]
    zMax: Annotated[float, Field(description="The maximum Z value of the bounding box.")]


class BoundingBox3DArrayItem(APIModel):
    boundingBox3D: BoundingBox3D


class LibPartUnId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class LibPartDetails(APIModel):
    name: str
    parentUnID: LibPartUnId
    ownUnID: LibPartUnId


class NavigatorItemId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class DatabaseId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class Zoom(APIModel):
    xMin: float
    yMin: float
    xMax: float
    yMax: float


class ViewSettings(APIModel):
    modelViewOptions: Annotated[
        str | None,
        Field(description="The name of the model view options. If empty, the view has custom model view options."),
    ] = None
    layerCombination: Annotated[
        str | None,
        Field(description="The name of the layer combination. If empty, the view has custom layer combination."),
    ] = None
    dimensionStyle: Annotated[
        str | None,
        Field(description="The name of the dimension style. If empty, the view has custom dimension style."),
    ] = None
    penSetName: Annotated[
        str | None,
        Field(description="The name of the pen set. If empty, the view has custom pen set."),
    ] = None
    graphicOverrideCombination: Annotated[
        str | None,
        Field(
            description="The name of the graphic override combination. If empty, the view has custom graphic override combination."
        ),
    ] = None
    drawingScale: Annotated[
        int | None,
        Field(description="The drawing scale stored on the view, if enabled."),
    ] = None
    saveZoom: Annotated[bool | None, Field(description="Whether the zoom box is stored in the view.")] = None
    ignoreSavedZoom: Annotated[
        bool | None,
        Field(description="Whether changing to the view should ignore its stored zoom."),
    ] = None
    zoom: Annotated[
        Zoom | None,
        Field(description="Stored zoom box in model coordinates. Used only when saveZoom is true."),
    ] = None


class Zoom1(APIModel):
    xMin: Annotated[float, Field(description="The minimum X value of the zoom box.")]
    yMin: Annotated[float, Field(description="The minimum Y value of the zoom box.")]
    xMax: Annotated[float, Field(description="The maximum X value of the zoom box.")]
    yMax: Annotated[float, Field(description="The maximum Y value of the zoom box.")]


class ViewTransformations(APIModel):
    zoom: Annotated[
        Zoom1,
        Field(description="The actual zoom parameters, rectangular region of the model."),
    ]
    rotation: Annotated[float, Field(description="The orientation in radian.")]


class Hole2D(APIModel):
    polygonOutline: Annotated[
        list[Coordinate2D] | None,
        Field(description="The 2D coordinates of the edge of the hole.", min_length=3),
    ] = None
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the hole.")] = None


class Hole3D(APIModel):
    polygonCoordinates: Annotated[
        list[Coordinate3D],
        Field(description="The 3D coordinates of the polygon of the hole.", min_length=3),
    ]
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the hole.")] = None


class GeometryType(Enum):
    Straight = "Straight"
    Trapezoid = "Trapezoid"
    Polygonal = "Polygonal"


class StructureType(Enum):
    Basic = "Basic"
    Composite = "Composite"
    Profile = "Profile"


class BeamDetails(APIModel):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    level: Annotated[float, Field(description="base height of the beam relative to the floor level")]
    offset: Annotated[float, Field(description="beam ref.line offset from the center")]
    slantAngle: Annotated[float, Field(description="The slant angle of the beam in radians.")]
    arcAngle: Annotated[
        float,
        Field(description="The arc angle of the (horizontally) curved beam in radians."),
    ]
    verticalCurveHeight: Annotated[float, Field(description="The height of the vertical curve of the beam.")]


class StructureType1(Enum):
    Basic = "Basic"
    Composite = "Composite"


class ColumnDetails(APIModel):
    origin: Coordinate2D
    zCoordinate: float
    height: Annotated[float, Field(description="height relative to bottom")]
    bottomOffset: Annotated[float, Field(description="base level of the column relative to the floor level")]


class PolylineDetails(APIModel):
    coordinates: list[Coordinate2D]
    arcs: Annotated[list[PolyArc] | None, Field(description="The arcs of the polyline.")] = None
    zCoordinate: float


class CurtainWallDetails(APIModel):
    height: float | None = None
    angle: Annotated[
        float | None,
        Field(description="The rotation angle of the curtain wall in radians."),
    ] = None


class CurtainWallSegmentDetails(APIModel):
    begCoordinate: Coordinate3D
    endCoordinate: Coordinate3D
    extrusionVector: Coordinate3D
    gridOrigin: Coordinate3D
    gridAngle: Annotated[float, Field(description="The angle of the grid in radians.")]
    arcOrigin: Coordinate3D | None = None
    isNegativeArc: Annotated[bool | None, Field(description="Indicates if the arc is negative.")] = None


class CurtainWallFrameType(Enum):
    Deleted = "Deleted"
    Division = "Division"
    Corner = "Corner"
    Boundary = "Boundary"
    Custom = "Custom"


class PanelConnectionHole(APIModel):
    d: Annotated[float, Field(description="Depth of the panel connection hole.")]
    w: Annotated[float, Field(description="Width of the panel connection hole.")]


class FrameContour(APIModel):
    a1: Annotated[float, Field(description="Width1 of the frame contour.")]
    a2: Annotated[float, Field(description="Width2 of the frame contour.")]
    b1: Annotated[float, Field(description="Length1 of the frame contour.")]
    b2: Annotated[float, Field(description="Length2 of the frame contour.")]


class CurtainWallFrameDetails(APIModel):
    begCoordinate: Coordinate3D
    endCoordinate: Coordinate3D
    orientationVector: Coordinate3D
    panelConnectionHole: Annotated[
        PanelConnectionHole,
        Field(description="The parameters of the panel connection hole."),
    ]
    frameContour: Annotated[FrameContour, Field(description="The parameters of the frame contour.")]
    segmentIndex: Annotated[
        float,
        Field(description="The index of the curtain wall segment to which this frame belongs."),
    ]
    className: str
    type: CurtainWallFrameType


class MeshSkirtType(Enum):
    SurfaceOnlyWithoutSkirt = "SurfaceOnlyWithoutSkirt"
    WithSkirt = "WithSkirt"
    SolidBodyWithSkirt = "SolidBodyWithSkirt"


class Subline(APIModel):
    coordinates: Annotated[
        list[Coordinate3D],
        Field(description="The 3D coordinates of the leveling subline of the mesh."),
    ]


class MeshDetails(APIModel):
    level: Annotated[float, Field(description="The Z reference level of coordinates.")]
    skirtType: MeshSkirtType
    skirtLevel: Annotated[float, Field(description="The height of the skirt.")]
    polygonCoordinates: Annotated[
        list[Coordinate3D],
        Field(
            description="The 3D coordinates of the outline polygon of the mesh.",
            min_length=3,
        ),
    ]
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the mesh.")] = None
    holes: Annotated[
        list[Hole3D] | None,
        Field(description="A list of 3D holes in an element defined by closed polylines"),
    ] = None
    sublines: Annotated[
        list[Subline] | None,
        Field(
            description="The leveling sublines inside the polygon of the mesh.",
            min_length=1,
        ),
    ] = None


class NotYetSupportedElementTypeDetails(APIModel):
    error: str


class RevisionIssueId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class DocumentRevisionId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class RevisionCustomSchemeDatum(APIModel):
    customSchemeKey: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]
    customSchemeValue: str


class DocumentRevisionReference(APIModel):
    revisionId: DocumentRevisionId


class RevisionIssue(APIModel):
    revisionIssueId: RevisionIssueId
    id: str
    description: str
    issueTime: str
    issuedByUser: str
    overrideRevisionIDOfAllIncludedLayouts: bool
    createNewRevisionInAllIncludedLayouts: bool
    markersVisibleSinceIndex: int | None = None
    isIssued: bool
    documentRevisions: Annotated[
        list[DocumentRevisionReference] | None,
        Field(description="All document revisions belong to the current issue."),
    ] = None
    customSchemeData: list[RevisionCustomSchemeDatum] | None = None


class RevisionChange(APIModel):
    id: str
    description: str
    lastModifiedTime: str
    modifiedByUser: str
    isIssued: bool
    firstRevisionIssueId: Annotated[
        RevisionIssueId | None,
        Field(description="The identifier of the first issue in which the given change is issued."),
    ] = None
    isArchived: bool
    customSchemeData: list[RevisionCustomSchemeDatum] | None = None


class LayoutInfo(APIModel):
    id: str
    databaseId: DatabaseId
    name: str
    masterLayoutName: str
    width: float
    height: float
    subsetId: str
    subsetName: str
    ownerUser: str
    customSchemeData: list[RevisionCustomSchemeDatum] | None = None


class Status(Enum):
    Actual = "Actual"
    Issued = "Issued"


class Change(APIModel):
    id: str


class DocumentRevision(APIModel):
    revisionId: DocumentRevisionId
    id: str
    finalId: str
    ownerUser: str
    status: Status
    changes: Annotated[
        list[Change] | None,
        Field(description="All changes belonging to the given document revision."),
    ] = None
    layoutInfo: LayoutInfo


class RevisionChangesArrayItem(APIModel):
    revisionChanges: list[RevisionChange] | None = None


class StoryParameters(APIModel):
    index: Annotated[int, Field(description="The story index.")]
    floorId: Annotated[int, Field(description="Unique ID of the story.")]
    dispOnSections: Annotated[
        bool,
        Field(description="Story level lines should appear on sections and elevations."),
    ]
    level: Annotated[float, Field(description="The story level.")]
    name: Annotated[str, Field(description="The name of the story.")]


class StorySettings(APIModel):
    dispOnSections: Annotated[
        bool,
        Field(description="Story level lines should appear on sections and elevations."),
    ]
    level: Annotated[float, Field(description="The story level.")]
    name: Annotated[str, Field(description="The name of the story.")]


class AutomaticZoneGeometry(APIModel):
    referencePosition: Annotated[Coordinate2D, Field(description="Reference point to automatically find zone.")]


class ManualZoneGeometry(APIModel):
    polygonCoordinates: Annotated[
        list[Coordinate2D],
        Field(description="The 2D coordinates of the edge of the zone.", min_length=3),
    ]
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the zone.")] = None
    holes: Annotated[
        list[Hole2D] | None,
        Field(description="A list of 2D holes in an element defined by closed polylines"),
    ] = None


class WallSettings(APIModel):
    begCoordinate: Coordinate2D | None = None
    endCoordinate: Coordinate2D | None = None
    height: Annotated[float | None, Field(description="height relative to bottom")] = None
    bottomOffset: Annotated[
        float | None,
        Field(description="base level of the wall relative to the floor level"),
    ] = None
    offset: Annotated[float | None, Field(description="wall's base line's offset from ref. line")] = None
    begThickness: Annotated[
        float | None,
        Field(description="Thickness at the beginning in case of trapezoid wall"),
    ] = None
    endThickness: Annotated[
        float | None,
        Field(description="Thickness at the end in case of trapezoid wall"),
    ] = None


TypeSpecificSettings: TypeAlias = WallSettings


class PropertyGroup(APIModel):
    name: str
    description: str | None = None


class PropertyGroupArrayItem(APIModel):
    propertyGroup: PropertyGroup


class EnumValue(APIModel):
    enumValueId: Annotated[
        DisplayValueEnumId | NonLocalizedValueEnumId | None,
        Field(description="The identifier of a property enumeration value."),
    ] = None
    displayValue: Annotated[str, Field(description="Displayed value of the enumeration.")]
    nonLocalizedValue: Annotated[
        str | None,
        Field(description="Nonlocalized value of the enumeration if there is one."),
    ] = None


class PossibleEnumValue(APIModel):
    enumValue: Annotated[EnumValue, Field(description="The description of an enumeration value.")]


class Group(APIModel):
    propertyGroupId: PropertyGroupId | None = None
    name: str | None = None


class BuildingMaterialPhysicalProperties(APIModel):
    thermalConductivity: Annotated[float, Field(description="Thermal Conductivity.")]
    density: Annotated[float, Field(description="Density.")]
    heatCapacity: Annotated[float, Field(description="Heat Capacity.")]
    embodiedEnergy: Annotated[float, Field(description="Embodied Energy.")]
    embodiedCarbon: Annotated[float, Field(description="Embodied Carbon.")]


class ProjectInfoField(APIModel):
    projectInfoId: Annotated[str, Field(description="The id of the project info field.")]
    projectInfoName: Annotated[str, Field(description="The name of the project info field visible on UI.")]
    projectInfoValue: Annotated[str, Field(description="The value of the project info field.")]


class LibraryPartType(Enum):
    Window = "Window"
    Door = "Door"
    Object = "Object"
    Lamp = "Lamp"
    Room = "Room"
    Property = "Property"
    PlanSign = "PlanSign"
    Label = "Label"
    Macro = "Macro"
    Pict = "Pict"
    ListScheme = "ListScheme"
    Skylight = "Skylight"
    OpeningSymbol = "OpeningSymbol"


class FavoritesWrapper(APIModel):
    favorites: Annotated[list[str], Field(description="A list of favorite names")]


class GroupId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class GroupIdArrayItem(APIModel):
    groupId: GroupId


class Length(APIModel):
    unit: LengthType
    accuracy: AccuracyType
    decimals: Annotated[int, Field(description="Number of decimals to display for length values.")]
    roundInch: Annotated[int | None, Field(description="Fractional inches.")] = None


class Area(APIModel):
    unit: AreaType
    accuracy: AccuracyType
    decimals: Annotated[int, Field(description="Number of decimals to display for area values.")]


class Volume(APIModel):
    unit: VolumeType
    accuracy: AccuracyType
    decimals: Annotated[int, Field(description="Number of decimals to display for volume values.")]


class Angle(APIModel):
    unit: AngleType
    decimals: Annotated[int, Field(description="Number of decimals to display for angle values.")]
    accuracy: Annotated[int, Field(description="Accuracy for angle values.")]


class Method(Enum):
    save = "save"
    merge = "merge"
    open = "open"


class FileType(Enum):
    ifc = "ifc"
    ifcxml = "ifcxml"
    ifczip = "ifczip"
    ifcxmlzip = "ifcxmlzip"


class PrintArea(Enum):
    currentView = "currentView"
    entireDrawing = "entireDrawing"
    marquee = "marquee"


class Details(APIModel):
    floorIndex: float | None = None
    layerIndex: float | None = None
    drawIndex: float | None = None
    typeSpecificDetails: TypeSpecificSettings | None = None


class Settings(APIModel):
    volumeTolerance: Annotated[
        float,
        Field(
            description="Intersection body volume greater then this value will be considered as a collision. Default value is 0.001."
        ),
    ]
    performSurfaceCheck: Annotated[
        bool,
        Field(
            description="Enables surface collision check. If disabled the surfaceTolerance value will be ignored. By default it's false."
        ),
    ]
    surfaceTolerance: Annotated[
        float,
        Field(
            description="Intersection body surface area greater then this value will be considered as a collision. Default value is 0.001."
        ),
    ]


HighlightedColor: TypeAlias = list[int]


class MoveVector(APIModel):
    x: Annotated[float, Field(description="X value of the vector.")]
    y: Annotated[float, Field(description="Y value of the vector.")]
    z: Annotated[float, Field(description="Z value of the vector.")]


class Level(APIModel):
    levelHeight: float
    levelAngle: Annotated[float, Field(gt=0.0)]


class Preset(Enum):
    WallCompositeFaces = "WallCompositeFaces"
    WallSkinBorders = "WallSkinBorders"
    SlabCompositeFaces = "SlabCompositeFaces"
    SlabSkinBorders = "SlabSkinBorders"
    BeamOrColumnRefLineEndPoints = "BeamOrColumnRefLineEndPoints"
    BeamOrColumnBoundingBoxCorners = "BeamOrColumnBoundingBoxCorners"
    DoorWindowWallHoleCorners = "DoorWindowWallHoleCorners"
    DoorWindowModelHotspots = "DoorWindowModelHotspots"


class StructureType3(Enum):
    Basic = "Basic"
    Composite = "Composite"
    Profile = "Profile"


class StructureType4(Enum):
    Basic = "Basic"
    Composite = "Composite"


class ImageType(Enum):
    field_2D = "2D"
    Section = "Section"
    field_3D = "3D"


class Format(Enum):
    png = "png"
    jpg = "jpg"


class Library(APIModel):
    name: Annotated[str, Field(description="Library name.")]
    path: Annotated[str, Field(description="A filesystem path to library location.")]
    type: Annotated[str, Field(description="Library type.")]
    available: Annotated[bool | None, Field(description="Is library not missing.")] = None
    readOnly: Annotated[bool | None, Field(description="Is library not writable.")] = None
    twServerUrl: Annotated[
        str | None,
        Field(description="URL address of the TeamWork server hosting the library."),
    ] = None
    urlWebLibrary: Annotated[str | None, Field(description="URL of the downloaded Internet library.")] = None


class User(APIModel):
    userId: float
    userName: str


class DetailsDatum(APIModel):
    name: Annotated[str, Field(min_length=1)]
    referenceId: Annotated[str, Field(min_length=1)]


class WorksheetsDatum(APIModel):
    name: Annotated[str, Field(min_length=1)]
    referenceId: Annotated[str, Field(min_length=1)]


class LayoutsDatum(APIModel):
    masterLayoutName: Annotated[str, Field(min_length=1)]
    layoutName: Annotated[str, Field(min_length=1)]


class SubsetsDatum(APIModel):
    name: Annotated[str, Field(min_length=1)]
    parentNavigatorItemId: NavigatorItemId | None = None
    ownPrefix: str | None = None
    customNumber: str | None = None


class DrawingsDatum(APIModel):
    navigatorItemId: NavigatorItemId
    layoutDatabaseId: DatabaseId | None = None
    name: Annotated[str, Field(min_length=1)]
    position: Coordinate2D
    scale: Annotated[float | None, Field(gt=0.0)] = None


class ModelViewOption(APIModel):
    name: str


class NavigatorItemIdsWithViewSetting(APIModel):
    navigatorItemId: NavigatorItemId
    viewSettings: ViewSettings


class CutPlane(APIModel):
    pa: Annotated[
        float,
        Field(
            description="Coefficient of x in the plane equation. The x coordinate of the normal vector of the plane."
        ),
    ]
    pb: Annotated[
        float,
        Field(
            description="Coefficient of y in the plane equation. The y coordinate of the normal vector of the plane."
        ),
    ]
    pc: Annotated[
        float,
        Field(
            description="Coefficient of z in the plane equation. The z coordinate of the normal vector of the plane."
        ),
    ]
    pd: Annotated[
        float,
        Field(
            description="Constant term in the plane equation. The distance of the plane from the origin along the normal vector."
        ),
    ]


class Comment(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="Comment identifier",
        ),
    ]
    author: Annotated[str, Field(description="Comment author")]
    text: Annotated[str, Field(description="Comment text")]
    status: IssueCommentStatus
    creaTime: Annotated[int, Field(description="Comment creation time")]


class Coordinates(APIModel):
    x: Annotated[float, Field(description="X value of the coordinate.")]
    y: Annotated[float, Field(description="Y value of the coordinate.")]
    z: Annotated[float, Field(description="Z value of the coordinate.")]


class ColumnData(APIModel):
    coordinates: Annotated[Coordinates, Field(description="3D coordinate.")]
    height: Annotated[float | None, Field(description="Optional column height.", gt=0.0)] = None
    axisRotationAngle: Annotated[float | None, Field(description="Optional column rotation angle in radians.")] = None


class SlabData(APIModel):
    level: Annotated[
        float,
        Field(description="The Z coordinate value of the reference line of the slab."),
    ]
    thickness: Annotated[float | None, Field(description="Optional slab thickness.", gt=0.0)] = None
    polygonCoordinates: Annotated[
        list[Coordinate2D],
        Field(description="The 2D coordinates of the edge of the slab.", min_length=3),
    ]
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the slab.")] = None
    holes: Annotated[
        list[Hole2D] | None,
        Field(description="A list of 2D holes in an element defined by closed polylines"),
    ] = None


class PolylineData(APIModel):
    floorInd: Annotated[
        float | None,
        Field(description="The identifier of the floor. Optional parameter, by default the current floor is used."),
    ] = None
    layerIndex: Annotated[
        int | None,
        Field(
            description="Layer attribute index to place the polyline on. Optional parameter, by default the current layer is used."
        ),
    ] = None
    linePenIndex: Annotated[
        int | None,
        Field(description="Pen index of the polyline contour. Optional parameter, by default the current pen is used."),
    ] = None
    lineTypeIndex: Annotated[
        int | None,
        Field(
            description="Line type attribute index of the polyline contour. Optional parameter, by default the current line type is used."
        ),
    ] = None
    penWeightMm: Annotated[float | None, Field(description="Optional pen weight override in mm.")] = None
    coordinates: Annotated[
        list[Coordinate2D],
        Field(description="The 2D coordinates of the polyline.", min_length=2),
    ]
    arcs: Annotated[list[PolyArc] | None, Field(description="The arcs of the polyline.")] = None


class ObjectData(APIModel):
    libraryPartName: Annotated[str, Field(description="The name of the library part to use.")]
    coordinates: Coordinate3D
    dimensions: Dimensions3D | None = None


class MeshData(APIModel):
    floorIndex: int | None = None
    level: Annotated[float | None, Field(description="The Z reference level of coordinates.")] = None
    skirtType: MeshSkirtType | None = None
    skirtLevel: Annotated[float | None, Field(description="The height of the skirt.")] = None
    polygonCoordinates: Annotated[
        list[Coordinate3D],
        Field(
            description="The 3D coordinates of the outline polygon of the mesh.",
            min_length=3,
        ),
    ]
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the mesh.")] = None
    holes: Annotated[
        list[Hole3D] | None,
        Field(description="A list of 3D holes in an element defined by closed polylines"),
    ] = None
    sublines: Annotated[
        list[Subline] | None,
        Field(
            description="The leveling sublines inside the polygon of the mesh.",
            min_length=1,
        ),
    ] = None


class BeamData(APIModel):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    offset: float | None = None
    slantAngle: float | None = None
    arcAngle: float | None = None
    verticalCurveHeight: float | None = None


class StructureType6(Enum):
    Basic = "Basic"
    Composite = "Composite"
    Profile = "Profile"


class ProjectLocation(APIModel):
    longitude: Annotated[float, Field(description="longitude in degrees")]
    latitude: Annotated[float, Field(description="latitude in degrees")]
    altitude: Annotated[float, Field(description="altitude in meters")]
    north: Annotated[float, Field(description="north direction in radians")]


class SurveyPointPosition(APIModel):
    eastings: Annotated[
        float,
        Field(
            description="Location along the easting of the coordinate system of the target map coordinate reference system."
        ),
    ]
    northings: Annotated[
        float,
        Field(
            description="Location along the northing of the coordinate system of the target map coordinate reference system."
        ),
    ]
    elevation: Annotated[
        float,
        Field(description="Orthogonal height relative to the vertical datum specified."),
    ]


class GeoReferencingParameters(APIModel):
    crsName: Annotated[
        str,
        Field(description="Name by which the coordinate reference system is identified."),
    ]
    description: Annotated[
        str,
        Field(description="Informal description of this coordinate reference system."),
    ]
    geodeticDatum: Annotated[str, Field(description="Name by which this datum is identified.")]
    verticalDatum: Annotated[str, Field(description="Name by which the vertical datum is identified.")]
    mapProjection: Annotated[str, Field(description="Name by which the map projection is identified.")]
    mapZone: Annotated[
        str,
        Field(description="Name by which the map zone, relating to the MapProjection, is identified."),
    ]


class SurveyPoint(APIModel):
    position: SurveyPointPosition
    geoReferencingParameters: GeoReferencingParameters


class ElementId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class AttributeId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class GuidId(APIModel):
    guid: Annotated[
        UUID,
        Field(
            description="A Globally Unique Identifier (or Universally Unique Identifier) in its string representation as defined in RFC 4122.",
        ),
    ]


class DesignOptionIdArrayItem(APIModel):
    designOptionId: GuidId


class LayersOfLayerCombinationItem(APIModel):
    attributeId: Annotated[AttributeId, Field(description="The identifier of the Layer attribute.")]
    isHidden: Annotated[bool, Field(description="Visibility of the Layer in the Layer Combination.")]
    isLocked: Annotated[bool, Field(description="Lock state of the Layer in the Layer Combination.")]
    isWireframe: Annotated[
        bool,
        Field(description="Is wireframe mode forced for the Layer in the Layer Combination."),
    ]
    intersectionGroupNr: Annotated[
        int,
        Field(
            description="Intersection group of the Layer in the Layer Combination. Elements on layers having the same group will be intersected."
        ),
    ]


class LayerCombinationAttributeDetails(APIModel):
    attributeId: Annotated[
        AttributeId,
        Field(description="The identifier of the layer combination attribute."),
    ]
    attributeIndex: Annotated[
        int | None,
        Field(description="The index identifier of the layer combination attribute."),
    ] = None
    name: Annotated[str, Field(description="The name of the layer combination.")]
    layers: Annotated[
        list[LayersOfLayerCombinationItem],
        Field(description="List of Layers included in the Layer Combination."),
    ]


class LayerCombinationAttribute(APIModel):
    layerCombination: LayerCombinationAttributeDetails


class GDLParameterList(APIModel):
    parameters: Annotated[list[GDLParameterDetails], Field(description="The list of GDL parameters.")]


class ElementPropertyValue(APIModel):
    elementId: ElementId
    propertyId: PropertyId
    propertyValue: PropertyValue


class AttributePropertyValue(APIModel):
    attributeId: AttributeId
    propertyId: PropertyId
    propertyValue: PropertyValue


class BasicDefaultValue(APIModel):
    basicDefaultValue: Annotated[
        NotAvailablePropertyValue
        | NormalNumberPropertyValue
        | NormalIntegerPropertyValue
        | NormalStringPropertyValue
        | NormalBooleanPropertyValue
        | NormalLengthPropertyValue
        | NormalAreaPropertyValue
        | NormalVolumePropertyValue
        | NormalAnglePropertyValue
        | NormalNumberListPropertyValue
        | NormalIntegerListPropertyValue
        | NormalStringListPropertyValue
        | NormalBooleanListPropertyValue
        | NormalLengthListPropertyValue
        | NormalAreaListPropertyValue
        | NormalVolumeListPropertyValue
        | NormalAngleListPropertyValue
        | NormalSingleEnumPropertyValue
        | NormalMultiEnumPropertyValue
        | UserUndefinedPropertyValue,
        Field(description="A normal, userUndefined, notAvailable or notEvaluated property value."),
    ]


class ElementClassification(APIModel):
    elementId: ElementId
    classificationId: ClassificationId


class NavigatorItemIdArrayItem(APIModel):
    navigatorItemId: NavigatorItemId


class DatabaseIdArrayItem(APIModel):
    databaseId: DatabaseId


class WallDetails(APIModel):
    geometryType: GeometryType
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    height: Annotated[float, Field(description="height relative to bottom")]
    bottomOffset: Annotated[float, Field(description="base level of the wall relative to the floor level")]
    offset: Annotated[float, Field(description="wall's base line's offset from ref. line")]
    arcAngle: Annotated[float | None, Field(description="The arc angle of the curved wall in radians.")] = None
    begThickness: Annotated[
        float | None,
        Field(description="Thickness at the beginning in case of trapezoid wall"),
    ] = None
    endThickness: Annotated[
        float | None,
        Field(description="Thickness at the end in case of trapezoid wall"),
    ] = None
    polygonOutline: Annotated[
        list[Coordinate2D] | None,
        Field(description="Polygon outline in case of polygonal wall"),
    ] = None
    polygonArcs: Annotated[
        list[PolyArc] | None,
        Field(description="Polygon arcs in case of polygonal wall"),
    ] = None
    structureType: StructureType | None = None
    buildingMaterialId: AttributeId | None = None
    compositeId: AttributeId | None = None
    profileId: AttributeId | None = None


class SlabDetails(APIModel):
    thickness: Annotated[float, Field(description="Thickness of the slab.")]
    level: Annotated[
        float,
        Field(description="Distance of the reference level of the slab from the floor level."),
    ]
    offsetFromTop: Annotated[
        float,
        Field(description="Vertical distance between the reference level and the top of the slab."),
    ]
    zCoordinate: float
    polygonOutline: Annotated[list[Coordinate2D], Field(description="Polygon outline of the slab.")]
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the slab.")] = None
    holes: Annotated[
        list[Hole2D],
        Field(description="A list of 2D holes in an element defined by closed polylines"),
    ]
    structureType: StructureType1 | None = None
    buildingMaterialId: AttributeId | None = None
    compositeId: AttributeId | None = None


class LinkData(APIModel):
    referredView: Annotated[
        ElementId | None,
        Field(description="Guid of the referred view. Only if the marker refers to a view."),
    ] = None
    referredDrawing: Annotated[
        ElementId | None,
        Field(description="Guid of the referred drawing. Only if the marker refers to a drawing."),
    ] = None
    referredPMViewPoint: Annotated[
        ElementId | None,
        Field(description="Guid of the referred view point. Only if the marker refers to a view point."),
    ] = None


class DetailWorksheetDetails(APIModel):
    basePoint: Annotated[Coordinate2D, Field(description="Coordinate of the base point")]
    angle: Annotated[float, Field(description="The rotation angle (radian) of the marker symbol")]
    markerId: Annotated[ElementId, Field(description="Guid of the marker symbol")]
    detailName: Annotated[str, Field(description="Name of the detail/worksheet")]
    detailIdStr: Annotated[str, Field(description="Reference ID of the detail/worksheet")]
    isHorizontalMarker: Annotated[bool, Field(description="Marker symbol is always horizontal?")]
    isWindowOpened: Annotated[bool, Field(description="Side (detail/worksheet) window is opened?")]
    clipPolygon: Annotated[
        list[Coordinate2D],
        Field(description="The clip polygon of the detail/worksheet"),
    ]
    linkData: Annotated[LinkData, Field(description="The marker link data")]


class LibPartBasedElementDetails(APIModel):
    libPart: LibPartDetails
    ownerElementId: ElementId | None = None
    ownerElementType: ElementType | None = None


class ObjectDetails(APIModel):
    libPart: LibPartDetails
    ownerElementId: ElementId | None = None
    ownerElementType: ElementType | None = None
    origin: Coordinate3D
    dimensions: Coordinate3D
    angle: float


class ZoneDetails(APIModel):
    name: Annotated[str, Field(description="Name of the zone.")]
    numberStr: Annotated[str, Field(description="Zone number.")]
    categoryAttributeId: Annotated[AttributeId, Field(description="The identifier of the zone category attribute.")]
    stampPosition: Annotated[Coordinate2D, Field(description="Position of the origin of the zone stamp.")]
    isManual: Annotated[bool, Field(description="Is the coordinates of the zone manually placed?")]
    polygonCoordinates: Annotated[
        list[Coordinate2D],
        Field(description="The 2D coordinates of the edge of the zone.", min_length=3),
    ]
    polygonArcs: Annotated[list[PolyArc] | None, Field(description="Polygon outline arcs of the zone.")] = None
    holes: Annotated[
        list[Hole2D] | None,
        Field(description="A list of 2D holes in an element defined by closed polylines"),
    ] = None
    zCoordinate: float


class PropertyDefinition(APIModel):
    name: str
    description: str
    type: PropertyDataType
    isEditable: bool
    defaultValue: BasicDefaultValue | ExpressionDefaultValue | None = None
    possibleEnumValues: Annotated[
        list[PossibleEnumValue] | None,
        Field(description="The possible enum values of the property when the property type is enumeration."),
    ] = None
    availability: Annotated[
        list[ClassificationItemIdArrayItem],
        Field(description="The identifiers of classification items the new property is available for."),
    ]
    group: Annotated[
        Group,
        Field(description="The property group defined by name or id. If both fields exists the id will be used."),
    ]


class PropertyDefinitionArrayItem(APIModel):
    propertyDefinition: PropertyDefinition


class ZoneBoundary(APIModel):
    connectedElementId: Annotated[ElementId, Field(description="The unique identifier of the connected element.")]
    isExternal: Annotated[bool, Field(description="True if the boundary is an external one.")]
    neighbouringZoneElementId: Annotated[
        ElementId,
        Field(
            description="Returns the unique identifier of the other Zone the element connects to if the boundary is internal. Please note that this boundary does not represent the boundary of the element with the other Zone."
        ),
    ]
    area: Annotated[float, Field(description="The area of the polygon of the boundary.")]
    polygonOutline: Annotated[list[Coordinate3D], Field(description="The outline polygon of the boundary.")]


class ZoneBoundariesWrapper(APIModel):
    zoneBoundaries: list[ZoneBoundary]


class BuildingMaterialPhysicalPropertiesArrayItem(APIModel):
    properties: BuildingMaterialPhysicalProperties


class LibraryFileAddition(APIModel):
    inputPath: Annotated[str, Field(description="The path to the input file.")]
    outputPath: Annotated[
        str,
        Field(description="The relative path to the new file inside embedded library."),
    ]
    type: Annotated[
        LibraryPartType | None,
        Field(description="The type of the library part. By default 'Pict'."),
    ] = None


class AttributeHeader(APIModel):
    attributeId: AttributeId
    index: Annotated[float, Field(description="Index of the attribute.")]
    name: Annotated[str, Field(description="Name of the attribute.")]


class AttributeHeadersWrapper(APIModel):
    attributes: Annotated[list[AttributeHeader], Field(description="Details of attributes.")]


class ElementsWithDetail(APIModel):
    elementId: ElementId
    details: Annotated[Details, Field(description="Details of an element.")]


class Collision(APIModel):
    elementId1: ElementId
    elementId2: ElementId
    hasBodyCollision: bool
    hasClearenceCollision: bool


class ElementsWithMoveVector(APIModel):
    elementId: ElementId
    moveVector: Annotated[MoveVector, Field(description="Move vector of a 3D point.")]
    copy_: Annotated[
        bool | None,
        Field(
            alias="copy",
            description="Optional parameter. If true, then a copy of the element will be moved. By default it's false.",
        ),
    ] = None


class ElementsWithGDLParameter(APIModel):
    elementId: ElementId
    gdlParameters: Annotated[
        list[SetGDLParameterByNameDetails | SetGDLParameterByIndexDetails],
        Field(description="The list of GDL parameters."),
    ]


class WindowsDatum(APIModel):
    ownerWallId: ElementId
    centerOffset: Annotated[float, Field(ge=0.0)]
    sillHeight: float | None = None
    width: Annotated[float | None, Field(gt=0.0)] = None
    height: Annotated[float | None, Field(gt=0.0)] = None


class DoorsDatum(APIModel):
    ownerWallId: ElementId
    centerOffset: Annotated[float, Field(ge=0.0)]
    sillHeight: float | None = None
    width: Annotated[float | None, Field(gt=0.0)] = None
    height: Annotated[float | None, Field(gt=0.0)] = None


class OpeningsDatum(APIModel):
    ownerElementId: ElementId
    basePoint: Coordinate3D
    width: Annotated[float | None, Field(gt=0.0)] = None
    height: Annotated[float | None, Field(gt=0.0)] = None


class MorphsDatum(APIModel):
    basePoint: Coordinate3D
    size: Dimensions3D
    buildingMaterialId: AttributeId | None = None


class RoofsDatum(APIModel):
    level: float
    thickness: Annotated[float | None, Field(gt=0.0)] = None
    polygonCoordinates: Annotated[list[Coordinate2D], Field(min_length=3)]
    polygonArcs: list[PolyArc] | None = None
    holes: Annotated[
        list[Hole2D] | None,
        Field(description="A list of 2D holes in an element defined by closed polylines"),
    ] = None
    eavesOverhang: float | None = None
    levels: Annotated[list[Level] | None, Field(max_length=16, min_length=1)] = None
    structureType: StructureType1 | None = None
    buildingMaterialId: AttributeId | None = None
    compositeId: AttributeId | None = None


class WitnessPoint(APIModel):
    elementId: ElementId
    line: bool | None = None
    inIndex: int | None = None
    special: int | None = None
    nodeType: int | None = None
    nodeStatus: int | None = None
    nodeId: Annotated[float | None, Field(ge=0.0)] = None


class DimensionsDatum(APIModel):
    referencePoint: Coordinate2D
    direction: Coordinate2D
    floorIndex: float | None = None
    witnessPoints: Annotated[list[WitnessPoint], Field(min_length=2)]


class DimensionsDatum1(APIModel):
    sectionElementId: ElementId
    referencePoint: Coordinate2D
    preset: Preset
    direction: Coordinate2D | None = None
    skinBorderIndices: Annotated[list[int] | None, Field(min_length=1)] = None
    beginPlane: bool | None = None
    totalSizePlane: bool | None = None
    placeOnTop: bool | None = None


class DimensionsDatum2(APIModel):
    wallId: ElementId
    referencePoint: Coordinate2D
    direction: Coordinate2D


class WallsWithDetail(APIModel):
    elementId: ElementId
    begCoordinate: Coordinate2D | None = None
    endCoordinate: Coordinate2D | None = None
    height: Annotated[float | None, Field(gt=0.0)] = None
    thickness: Annotated[float | None, Field(gt=0.0)] = None
    bottomOffset: float | None = None
    offset: float | None = None
    structureType: StructureType3 | None = None
    buildingMaterialId: AttributeId | None = None
    compositeId: AttributeId | None = None
    profileId: AttributeId | None = None


class BeamsWithDetail(APIModel):
    elementId: ElementId
    begCoordinate: Coordinate2D | None = None
    endCoordinate: Coordinate2D | None = None
    level: float | None = None
    offset: float | None = None
    slantAngle: float | None = None
    arcAngle: float | None = None
    verticalCurveHeight: float | None = None


class SlabsWithDetail(APIModel):
    elementId: ElementId
    zCoordinate: float | None = None
    thickness: Annotated[float | None, Field(gt=0.0)] = None
    structureType: StructureType4 | None = None
    buildingMaterialId: AttributeId | None = None
    compositeId: AttributeId | None = None
    polygonOutline: Annotated[list[Coordinate2D] | None, Field(min_length=3)] = None
    polygonArcs: list[PolyArc] | None = None
    holes: Annotated[
        list[Hole2D] | None,
        Field(description="A list of 2D holes in an element defined by closed polylines"),
    ] = None


class ColumnsWithDetail(APIModel):
    elementId: ElementId
    origin: Coordinate2D | None = None
    zCoordinate: float | None = None
    height: Annotated[float | None, Field(gt=0.0)] = None
    bottomOffset: float | None = None
    axisRotationAngle: float | None = None


class WindowsWithDetail(APIModel):
    elementId: ElementId
    width: Annotated[float | None, Field(gt=0.0)] = None
    height: Annotated[float | None, Field(gt=0.0)] = None
    sillHeight: float | None = None
    centerOffset: Annotated[float | None, Field(ge=0.0)] = None


class DoorsWithDetail(APIModel):
    elementId: ElementId
    width: Annotated[float | None, Field(gt=0.0)] = None
    height: Annotated[float | None, Field(gt=0.0)] = None
    sillHeight: float | None = None
    centerOffset: Annotated[float | None, Field(ge=0.0)] = None


class MorphsWithDetail(APIModel):
    elementId: ElementId
    translation: Coordinate3D | None = None
    rotationDegreesZ: float | None = None
    buildingMaterialId: AttributeId | None = None


class RoofsWithDetail(APIModel):
    elementId: ElementId
    level: float | None = None
    thickness: Annotated[float | None, Field(gt=0.0)] = None
    eavesOverhang: float | None = None
    levels: Annotated[list[Level] | None, Field(max_length=16, min_length=1)] = None
    structureType: StructureType4 | None = None
    buildingMaterialId: AttributeId | None = None
    compositeId: AttributeId | None = None
    polygonOutline: Annotated[list[Coordinate2D] | None, Field(min_length=3)] = None
    polygonArcs: list[PolyArc] | None = None
    holes: Annotated[
        list[Hole2D] | None,
        Field(description="A list of 2D holes in an element defined by closed polylines"),
    ] = None


class FavoritesFromElement(APIModel):
    elementId: ElementId
    favorite: str


class LayerDataArrayItem(APIModel):
    attributeId: Annotated[
        AttributeId | None,
        Field(description="Indentifier of the existing Layer to overwrite, ignored if overwriteExisting is false."),
    ] = None
    index: Annotated[
        str | None,
        Field(description="Index of the existing Layer to overwrite, ignored if overwriteExisting is false."),
    ] = None
    name: Annotated[
        str,
        Field(
            description="Name. If overwriteExisting is true, then the existing Layer with the given name will be overwritten."
        ),
    ]
    isHidden: Annotated[bool | None, Field(description="Hide/Show.")] = None
    isLocked: Annotated[bool | None, Field(description="Lock/Unlock.")] = None
    isWireframe: Annotated[bool | None, Field(description="Force the model to wireframe.")] = None
    intersectionGroupNr: Annotated[
        int | None,
        Field(description="Intersection group. Elements on layers having the same group will be intersected."),
    ] = None


class LayerCombinationDataArrayItem(APIModel):
    attributeId: Annotated[
        AttributeId | None,
        Field(
            description="Indentifier of the existing Layer Combination to overwrite, ignored if overwriteExisting is false."
        ),
    ] = None
    index: Annotated[
        str | None,
        Field(
            description="Index of the existing Layer Combination to overwrite, ignored if overwriteExisting is false."
        ),
    ] = None
    name: Annotated[
        str,
        Field(
            description="Name. If overwriteExisting is true, then the existing Layer Combination with the given name will be overwritten."
        ),
    ]
    layers: Annotated[
        list[LayersOfLayerCombinationItem],
        Field(description="List of Layers included in the Layer Combination."),
    ]


class BuildingMaterialDataArrayItem(APIModel):
    attributeId: Annotated[
        AttributeId | None,
        Field(
            description="Indentifier of the existing Building Material to overwrite, ignored if overwriteExisting is false."
        ),
    ] = None
    index: Annotated[
        str | None,
        Field(
            description="Index of the existing Building Material to overwrite, ignored if overwriteExisting is false."
        ),
    ] = None
    name: Annotated[
        str,
        Field(
            description="Name. If overwriteExisting is true, then the existing Building Material with the given name will be overwritten."
        ),
    ]
    id: Annotated[str | None, Field(description="Identifier.")] = None
    manufacturer: Annotated[str | None, Field(description="Manufacturer.")] = None
    description: Annotated[str | None, Field(description="Decription.")] = None
    connPriority: Annotated[int | None, Field(description="Intersection priority.")] = None
    cutFillIndex: Annotated[int | None, Field(description="Index of the Cut Fill.")] = None
    cutFillPen: Annotated[int | None, Field(description="Cut Fill Foreground Pen.")] = None
    cutFillBackgroundPen: Annotated[int | None, Field(description="Cut Fill Background Pen.")] = None
    cutSurfaceIndex: Annotated[int | None, Field(description="Index of the Cut Surface.")] = None
    thermalConductivity: Annotated[float | None, Field(description="Thermal Conductivity.")] = None
    density: Annotated[float | None, Field(description="Density.")] = None
    heatCapacity: Annotated[float | None, Field(description="Heat Capacity.")] = None
    embodiedEnergy: Annotated[float | None, Field(description="Embodied Energy.")] = None
    embodiedCarbon: Annotated[float | None, Field(description="Embodied Carbon.")] = None


class Conflict(APIModel):
    elementId: ElementId
    user: User


class Issue(APIModel):
    issueId: IssueId
    name: Annotated[str, Field(description="Issue name")]
    parentIssueId: IssueId
    creaTime: Annotated[int, Field(description="Issue creation time")]
    modiTime: Annotated[int, Field(description="Issue modification time")]
    tagText: Annotated[str, Field(description="Issue tag text - labels")]
    tagTextElementId: ElementId
    isTagTextElemVisible: Annotated[bool, Field(description="The visibility of the attached tag text element")]


class DesignOption(APIModel):
    designOptionId: Annotated[GuidId, Field(description="The guid identifier of the design option.")]
    name: Annotated[str, Field(description="The name of the design option.")]
    id: Annotated[str, Field(description="The string id of the design option.")]
    ownerSetName: Annotated[str, Field(description="The name of the owner design option set.")]


class DesignOptionSet(APIModel):
    designOptionSetId: Annotated[GuidId, Field(description="The guid identifier of the design option set.")]
    name: Annotated[str, Field(description="The name of the design option set.")]
    designOptions: Annotated[
        list[DesignOptionIdArrayItem],
        Field(description="The list of design options in the set."),
    ]


class DesignOptionCombination(APIModel):
    designOptionCombinationId: Annotated[
        GuidId,
        Field(description="The guid identifier of the design option combination."),
    ]
    name: Annotated[str, Field(description="The name of the design option combination.")]
    activeDesignOptions: Annotated[
        list[DesignOptionIdArrayItem] | None,
        Field(description="The list of active design options in the combination. Available from Archicad 29."),
    ] = None


class ZoneData(APIModel):
    floorIndex: float | None = None
    name: Annotated[str, Field(description="Name of the zone.")]
    numberStr: Annotated[str, Field(description="Zone number.")]
    categoryAttributeId: Annotated[
        AttributeId | None,
        Field(description="The identifier of the zone category attribute."),
    ] = None
    stampPosition: Annotated[
        Coordinate2D | None,
        Field(description="Position of the origin of the zone stamp."),
    ] = None
    geometry: Annotated[
        AutomaticZoneGeometry | ManualZoneGeometry,
        Field(description="Defines the geometry of a zone. Used as input for creating zones."),
    ]


class WallData(APIModel):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    height: Annotated[float, Field(gt=0.0)]
    thickness: Annotated[float, Field(gt=0.0)]
    offset: float | None = None
    structureType: StructureType6 | None = None
    buildingMaterialId: AttributeId | None = None
    compositeId: AttributeId | None = None
    profileId: AttributeId | None = None


class LabelData(APIModel):
    parentElementId: Annotated[
        ElementId | None,
        Field(description="The parent element if the label is an associative label."),
    ] = None
    text: Annotated[str | None, Field(description="The text content if the label is a text label.")] = None
    begCoordinate: Annotated[
        Coordinate2D | None,
        Field(
            description="The begin coordinate of leader line. Optional parameter, but either begCoordinate or parentElementId must be provided."
        ),
    ] = None
    floorInd: Annotated[
        float | None,
        Field(
            description="The identifier of the floor. Optional parameter, by default the current floor or the floor of the parent element is used."
        ),
    ] = None


class ElementIdArrayItem(APIModel):
    elementId: ElementId


class AttributeIdArrayItem(APIModel):
    attributeId: AttributeId


class CurtainWallPanelDetails(APIModel):
    polygonCoordinates: Annotated[
        list[Coordinate3D],
        Field(description="The 3D coordinates of the panel polygon.", min_length=3),
    ]
    isHidden: Annotated[
        bool,
        Field(description="Indicates if the panel is hidden (deleted panels remain in the database)."),
    ]
    segmentIndex: Annotated[
        float,
        Field(description="The index of the curtain wall segment to which this panel belongs."),
    ]
    className: str
    frames: Annotated[
        list[ElementIdArrayItem],
        Field(description="The surrounding frames.", min_length=3),
    ]


class ElementGroupParameters(APIModel):
    elements: Annotated[
        list[ElementIdArrayItem | GroupIdArrayItem],
        Field(description="The elements or child groups to be grouped.", min_length=2),
    ]
    parentGroupId: Annotated[
        GroupId | None,
        Field(description="Optional parent group ID to nest this group under."),
    ] = None


class DetailsOfElement(APIModel):
    type: ElementType
    id: str
    floorIndex: float
    layerIndex: float
    drawIndex: float
    details: Annotated[
        WallDetails
        | BeamDetails
        | SlabDetails
        | ColumnDetails
        | DetailWorksheetDetails
        | LibPartBasedElementDetails
        | PolylineDetails
        | ZoneDetails
        | CurtainWallDetails
        | CurtainWallSegmentDetails
        | CurtainWallPanelDetails
        | CurtainWallFrameDetails
        | MeshDetails
        | NotYetSupportedElementTypeDetails,
        Field(
            description="Represents the complete type-specific details of an element. Used as output from GET requests"
        ),
    ]


class Skin(APIModel):
    type: Annotated[str, Field(description="Skin type (Core, Finish, or Other)")]
    buildingMaterialId: AttributeIdArrayItem
    framePen: Annotated[int, Field(description="Skin frame pen index.")]
    thickness: Annotated[float, Field(description="Skin thickness (in meters).")]


class Separator(APIModel):
    lineTypeId: AttributeIdArrayItem
    linePen: Annotated[int, Field(description="Separator line pen index.")]


class CompositeDataArrayItem(APIModel):
    attributeId: Annotated[
        AttributeId | None,
        Field(description="Indentifier of the existing Composite to overwrite, ignored if overwriteExisting is false."),
    ] = None
    index: Annotated[
        str | None,
        Field(description="Index of the existing Composite to overwrite, ignored if overwriteExisting is false."),
    ] = None
    name: Annotated[
        str,
        Field(
            description="Name. If overwriteExisting is true, then the existing Composite with the given name will be overwritten."
        ),
    ]
    useWith: Annotated[
        list[str] | None,
        Field(description="Array of types the composite can used with."),
    ] = None
    skins: Annotated[list[Skin], Field(description="Array of skin data.")]
    separators: Annotated[
        list[Separator],
        Field(description="Array of skin separator data. The number of items must be the number of skins plus one."),
    ]


class SurfaceDataArrayItem(APIModel):
    attributeId: Annotated[
        AttributeId | None,
        Field(description="Indentifier of the existing Surface to overwrite, ignored if overwriteExisting is false."),
    ] = None
    index: Annotated[
        str | None,
        Field(description="Index of the existing surface to overwrite, ignored if overwriteExisting is false."),
    ] = None
    name: Annotated[
        str,
        Field(
            description="Name. If overwriteExisting is true, then the existing surface with the given name will be overwritten."
        ),
    ]
    materialType: SurfaceType
    ambientReflection: Annotated[float, Field(description="Ambient percentage [0..100].")]
    diffuseReflection: Annotated[float, Field(description="Diffuse percentage [0..100].")]
    specularReflection: Annotated[float, Field(description="Specular percentage [0..100].")]
    transparency: Annotated[float, Field(description="Transparency percentage [0..100].")]
    shine: Annotated[float, Field(description="The shininess factor multiplied by 100 [0..10000].")]
    transparencyAttenuation: Annotated[
        float,
        Field(description="Transparency attenuation multiplied by 100 [0..10000]."),
    ]
    emissionAttenuation: Annotated[float, Field(description="Emission attenuation multiplied by 100 [0..10000].")]
    surfaceColor: ColorRGB
    specularColor: ColorRGB
    emissionColor: ColorRGB
    fillId: AttributeIdArrayItem | None = None
    texture: Texture | None = None


class ElementsWithExecutionResults(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]
    executionResultForDatabases: Annotated[
        list[SuccessfulExecutionResult | FailedExecutionResult] | None,
        Field(description="A list of execution results."),
    ] = None


class ConnectedElement(APIModel):
    elements: Annotated[list[ElementIdArrayItem], Field(description="A list of elements.")]


class ConnectedElementsWrapper(APIModel):
    connectedElements: list[ConnectedElement]


class Subelement(APIModel):
    cWallSegments: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    cWallFrames: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    cWallPanels: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    cWallJunctions: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    cWallAccessories: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    stairRisers: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    stairTreads: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    stairStructures: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingNodes: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingSegments: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingPosts: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingRailEnds: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingRailConnections: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingHandrailEnds: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingHandrailConnections: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = (
        None
    )
    railingToprailEnds: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingToprailConnections: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = (
        None
    )
    railingRails: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingToprails: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingHandrails: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingPatterns: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingInnerPosts: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingPanels: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingBalusterSets: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    railingBalusters: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    beamSegments: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None
    columnSegments: Annotated[list[ElementIdArrayItem] | None, Field(description="A list of elements.")] = None


class Hotlink(APIModel):
    location: Annotated[str, Field(description="The path of the hotlink file.")]
    children: Annotated[
        list[Hotlink] | None,
        Field(description="The children of the hotlink node if it has any."),
    ] = None


Hotlink.model_rebuild()
