from __future__ import annotations
from typing import Literal, TypedDict
from typing_extensions import NotRequired

### This file is automatically generated and split. Do not edit directly. ###


from .types import (
    Angle,
    Area,
    AttributeIdArrayItem,
    BeamData,
    BeamsWithDetail,
    BuildingMaterialDataArrayItem,
    Collision,
    ColorRGB,
    ColumnData,
    ColumnsWithDetail,
    Comment,
    CompositeDataArrayItem,
    Conflict,
    CutPlane,
    DatabaseId,
    DesignOption,
    DesignOptionCombination,
    DesignOptionSet,
    DetailsDatum,
    DetailsOfElement,
    DimensionsDatum,
    DimensionsDatum1,
    DimensionsDatum2,
    DocumentRevision,
    DoorsDatum,
    DoorsWithDetail,
    DrawingsDatum,
    ElementGroupParameters,
    ElementId,
    ElementIdArrayItem,
    ElementsWithDetail,
    ElementsWithGDLParameter,
    ElementsWithMoveVector,
    FavoritesFromElement,
    GDLParameterList,
    Issue,
    IssueId,
    LabelData,
    LayerCombinationDataArrayItem,
    LayerDataArrayItem,
    LayoutsDatum,
    Length,
    Library,
    MeshData,
    ModelViewOption,
    MorphsDatum,
    MorphsWithDetail,
    NavigatorItemIdsWithViewSetting,
    ObjectData,
    OpeningsDatum,
    PolylineData,
    ProjectLocation,
    PropertyDefinitionArrayItem,
    PropertyDetails,
    PropertyGroupArrayItem,
    PropertyGroupIdArrayItem,
    PropertyIdArrayItem,
    RevisionChange,
    RevisionIssue,
    RoofsDatum,
    RoofsWithDetail,
    Settings,
    SlabData,
    SlabsWithDetail,
    Subelement,
    SubsetsDatum,
    SurfaceDataArrayItem,
    SurveyPoint,
    Volume,
    WallData,
    WallsWithDetail,
    WindowsDatum,
    WindowsWithDetail,
    WorksheetsDatum,
    ZoneData,
)


class GetAddOnVersionResult(TypedDict, closed=True):
    version: str


class GetArchicadLocationResult(TypedDict, closed=True):
    archicadLocation: str


QuitArchicadResult: TypeAlias = ExecutionResult


class GetCurrentWindowTypeResult(TypedDict, closed=True):
    currentWindowType: WindowType


class ChangeWindowParameters(TypedDict, closed=True):
    windowType: WindowType
    databaseId: NotRequired[DatabaseId]


ChangeWindowResult: TypeAlias = ExecutionResult


class GetProjectInfoResult(TypedDict, closed=True):
    isUntitled: bool
    isTeamwork: bool
    projectLocation: NotRequired[str]
    projectPath: NotRequired[str]
    projectName: NotRequired[str]


class SetProjectInfoFieldParameters(TypedDict, closed=True):
    projectInfoId: str
    projectInfoValue: str


class GetStoriesResult(TypedDict, closed=True):
    firstStory: int
    lastStory: int
    actStory: int
    skipNullFloor: bool
    stories: StoriesParameters


class SetStoriesParameters(TypedDict, closed=True):
    stories: StoriesSettings


SetStoriesResult: TypeAlias = ExecutionResult


class OpenProjectParameters(TypedDict, closed=True):
    projectFilePath: str


OpenProjectResult: TypeAlias = ExecutionResult
CloseProjectResult: TypeAlias = ExecutionResult
SaveProjectResult: TypeAlias = ExecutionResult


class GetCalculationUnitsResult(TypedDict, closed=True):
    length: Length
    area: Area
    volume: Volume
    angle: Angle


SetGeoLocationResult: TypeAlias = ExecutionResult


class IFCFileOperationParameters(TypedDict, closed=True):
    method: Literal["save", "merge", "open"]
    ifcFilePath: str
    fileType: NotRequired[Literal["ifc", "ifcxml", "ifczip", "ifcxmlzip"]]


IFCFileOperationResult: TypeAlias = ExecutionResult


class PrintViewParameters(TypedDict, closed=True):
    grid: NotRequired[bool]
    fixText: NotRequired[bool]
    scale: NotRequired[int]
    printArea: NotRequired[Literal["currentView", "entireDrawing", "marquee"]]


PrintViewResult: TypeAlias = ExecutionResult


class ChangeSelectionOfElementsResult(TypedDict, closed=True):
    executionResultsOfAddToSelection: ExecutionResults
    executionResultsOfRemoveFromSelection: ExecutionResults


class SetDetailsOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class Get3DBoundingBoxesResult(TypedDict, closed=True):
    boundingBoxes3D: BoundingBoxes3D


class MoveElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


DeleteElementsResult: TypeAlias = ExecutionResult


class SetGDLParametersOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetClassificationsOfElementsResult(TypedDict, closed=True):
    elementClassifications: ElementClassificationsOrErrors


class SetClassificationsOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyWallsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyBeamsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifySlabsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyColumnsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyWindowsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyDoorsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyMorphsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class ModifyRoofsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetElementPreviewImageResult(TypedDict, closed=True):
    previewImage: str


class GetRoomImageResult(TypedDict, closed=True):
    roomImage: str


class SetElementNotificationClientParameters(TypedDict, closed=True):
    host: NotRequired[str]
    port: int
    notifyOnNewElement: NotRequired[bool]
    notifyOnModificationOfAnElement: NotRequired[bool]
    notifyOnReservationChanges: NotRequired[bool]


SetElementNotificationClientResult: TypeAlias = ExecutionResult


class RemoveElementNotificationClientParameters(TypedDict, closed=True):
    host: NotRequired[str]
    port: int


RemoveElementNotificationClientResult: TypeAlias = ExecutionResult


class CreateGroupsResult(TypedDict, closed=True):
    groupGuids: list[GroupIdOrError]


class GetFavoritesByTypeParameters(TypedDict, closed=True):
    elementType: ElementType


GetFavoritesByTypeResult: TypeAlias = FavoritesOrError


class GetFavoritePreviewImageParameters(TypedDict, closed=True):
    favorite: str
    imageType: NotRequired[Literal["2D", "Section", "3D"]]
    format: NotRequired[Literal["png", "jpg"]]
    width: NotRequired[int]
    height: NotRequired[int]


class GetFavoritePreviewImageResult(TypedDict, closed=True):
    previewImage: str


class ApplyFavoritesToElementDefaultsParameters(TypedDict, closed=True):
    favorites: Favorites


class ApplyFavoritesToElementDefaultsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class CreateFavoritesFromElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetAllPropertiesResult(TypedDict, closed=True):
    properties: list[PropertyDetails]


class GetPropertyValuesOfElementsResult(TypedDict, closed=True):
    propertyValuesForElements: PropertyValuesOrErrorArray


class SetPropertyValuesOfElementsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetPropertyValuesOfAttributesResult(TypedDict, closed=True):
    propertyValuesForAttributes: PropertyValuesOrErrorArray


class SetPropertyValuesOfAttributesResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class CreatePropertyGroupsParameters(TypedDict, closed=True):
    propertyGroups: list[PropertyGroupArrayItem]


class CreatePropertyGroupsResult(TypedDict, closed=True):
    propertyGroupIds: list[PropertyGroupIdArrayItem]


class DeletePropertyGroupsParameters(TypedDict, closed=True):
    propertyGroupIds: list[PropertyGroupIdArrayItem]


class DeletePropertyGroupsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class CreatePropertyDefinitionsResult(TypedDict, closed=True):
    propertyIds: PropertyIdOrErrorArray


class DeletePropertyDefinitionsParameters(TypedDict, closed=True):
    propertyIds: list[PropertyIdArrayItem]


class DeletePropertyDefinitionsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetAttributesByTypeParameters(TypedDict, closed=True):
    attributeType: AttributeType


class GetLibrariesResult(TypedDict, closed=True):
    libraries: list[Library]


ReloadLibrariesResult: TypeAlias = ExecutionResult


class AddFilesToEmbeddedLibraryResult(TypedDict, closed=True):
    executionResults: ExecutionResults


TeamworkSendResult: TypeAlias = ExecutionResult
TeamworkReceiveResult: TypeAlias = ExecutionResult


class CreateDetailsParameters(TypedDict, closed=True):
    detailsData: list[DetailsDatum]


class CreateWorksheetsParameters(TypedDict, closed=True):
    worksheetsData: list[WorksheetsDatum]


class CreateLayoutsParameters(TypedDict, closed=True):
    layoutsData: list[LayoutsDatum]


class CreateSubsetsParameters(TypedDict, closed=True):
    subsetsData: list[SubsetsDatum]


class CreateSubsetsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class CreateDrawingsParameters(TypedDict, closed=True):
    drawingsData: list[DrawingsDatum]


class GetModelViewOptionsResult(TypedDict, closed=True):
    modelViewOptions: list[ModelViewOption]


class GetViewSettingsResult(TypedDict, closed=True):
    viewSettings: list[ViewSettingsOrError]


class SetViewSettingsParameters(TypedDict, closed=True):
    navigatorItemIdsWithViewSettings: list[NavigatorItemIdsWithViewSetting]


class SetViewSettingsResult(TypedDict, closed=True):
    executionResults: ExecutionResults


class GetView2DTransformationsResult(TypedDict, closed=True):
    transformations: list[ViewTransformationsOrError]


class Set3DCutPlanesParameters(TypedDict, closed=True):
    cutPlanes: NotRequired[list[CutPlane]]


Set3DCutPlanesResult: TypeAlias = ExecutionResult
FitInWindowResult: TypeAlias = ExecutionResult


class CreateIssueParameters(TypedDict, closed=True):
    name: str
    parentIssueId: NotRequired[IssueId]
    tagText: NotRequired[str]


class CreateIssueResult(TypedDict, closed=True):
    issueId: IssueId


class DeleteIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    acceptAllElements: NotRequired[bool]


DeleteIssueResult: TypeAlias = ExecutionResult


class AddCommentToIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    author: NotRequired[str]
    status: NotRequired[IssueCommentStatus]
    text: str


AddCommentToIssueResult: TypeAlias = ExecutionResult


class GetCommentsFromIssueParameters(TypedDict, closed=True):
    issueId: IssueId


class GetCommentsFromIssueResult(TypedDict, closed=True):
    comments: list[Comment]


AttachElementsToIssueResult: TypeAlias = ExecutionResult
DetachElementsFromIssueResult: TypeAlias = ExecutionResult


class GetElementsAttachedToIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    type: IssueElementType


class ExportIssuesToBCFParameters(TypedDict, closed=True):
    issues: NotRequired[Issues]
    exportPath: str
    useExternalId: bool
    alignBySurveyPoint: bool


ExportIssuesToBCFResult: TypeAlias = ExecutionResult


class ImportIssuesFromBCFParameters(TypedDict, closed=True):
    importPath: str
    alignBySurveyPoint: bool


ImportIssuesFromBCFResult: TypeAlias = ExecutionResult


class GetRevisionIssuesResult(TypedDict, closed=True):
    revisionIssues: list[RevisionIssue]


class GetRevisionChangesResult(TypedDict, closed=True):
    revisionChanges: list[RevisionChange]


class GetDocumentRevisionsResult(TypedDict, closed=True):
    documentRevisions: list[DocumentRevision]


class GetCurrentRevisionChangesOfLayoutsResult(TypedDict, closed=True):
    currentRevisionChangesOfLayouts: RevisionChangesOfEntities


class GetRevisionChangesOfElementsResult(TypedDict, closed=True):
    revisionChangesOfElements: RevisionChangesOfEntities


class GenerateDocumentationParameters(TypedDict, closed=True):
    destinationFolder: str


GenerateDocumentationResult: TypeAlias = ExecutionResult


class GetProjectInfoFieldsResult(TypedDict, closed=True):
    fields: ProjectInfoFields


class GetGeoLocationResult(TypedDict, closed=True):
    projectLocation: ProjectLocation
    surveyPoint: SurveyPoint


class SetGeoLocationParameters(TypedDict, closed=True):
    projectLocation: NotRequired[ProjectLocation]
    surveyPoint: NotRequired[SurveyPoint]


class SetDetailsOfElementsParameters(TypedDict, closed=True):
    elementsWithDetails: list[ElementsWithDetail]


class GetZoneBoundariesParameters(TypedDict, closed=True):
    zoneElementId: ElementId


GetZoneBoundariesResult: TypeAlias = ZoneBoundariesOrError


class GetCollisionsResult(TypedDict, closed=True):
    collisions: list[Collision]


class MoveElementsParameters(TypedDict, closed=True):
    elementsWithMoveVectors: list[ElementsWithMoveVector]


class GetGDLParametersOfElementsResult(TypedDict, closed=True):
    gdlParametersOfElements: list[GDLParameterList]


class SetGDLParametersOfElementsParameters(TypedDict, closed=True):
    elementsWithGDLParameters: list[ElementsWithGDLParameter]


class SetClassificationsOfElementsParameters(TypedDict, closed=True):
    elementClassifications: ElementClassifications


class CreateColumnsParameters(TypedDict, closed=True):
    columnsData: list[ColumnData]


class CreateBeamsParameters(TypedDict, closed=True):
    beamsData: list[BeamData]


class CreateSlabsParameters(TypedDict, closed=True):
    slabsData: list[SlabData]


class CreateWindowsParameters(TypedDict, closed=True):
    windowsData: list[WindowsDatum]


class CreateDoorsParameters(TypedDict, closed=True):
    doorsData: list[DoorsDatum]


class CreateOpeningsParameters(TypedDict, closed=True):
    openingsData: list[OpeningsDatum]


class CreateMorphsParameters(TypedDict, closed=True):
    morphsData: list[MorphsDatum]


class CreateRoofsParameters(TypedDict, closed=True):
    roofsData: list[RoofsDatum]


class CreateAssociativeDimensionsParameters(TypedDict, closed=True):
    dimensionsData: list[DimensionsDatum]


class CreateAssociativeDimensionsOnSectionParameters(TypedDict, closed=True):
    dimensionsData: list[DimensionsDatum1]


class CreateWallThicknessDimensionsParameters(TypedDict, closed=True):
    dimensionsData: list[DimensionsDatum2]


class CreatePolylinesParameters(TypedDict, closed=True):
    polylinesData: list[PolylineData]


class CreateObjectsParameters(TypedDict, closed=True):
    objectsData: list[ObjectData]


class CreateMeshesParameters(TypedDict, closed=True):
    meshesData: list[MeshData]


class ModifyWallsParameters(TypedDict, closed=True):
    wallsWithDetails: list[WallsWithDetail]


class ModifyBeamsParameters(TypedDict, closed=True):
    beamsWithDetails: list[BeamsWithDetail]


class ModifySlabsParameters(TypedDict, closed=True):
    slabsWithDetails: list[SlabsWithDetail]


class ModifyColumnsParameters(TypedDict, closed=True):
    columnsWithDetails: list[ColumnsWithDetail]


class ModifyWindowsParameters(TypedDict, closed=True):
    windowsWithDetails: list[WindowsWithDetail]


class ModifyDoorsParameters(TypedDict, closed=True):
    doorsWithDetails: list[DoorsWithDetail]


class ModifyMorphsParameters(TypedDict, closed=True):
    morphsWithDetails: list[MorphsWithDetail]


class ModifyRoofsParameters(TypedDict, closed=True):
    roofsWithDetails: list[RoofsWithDetail]


class GetElementPreviewImageParameters(TypedDict, closed=True):
    elementId: ElementId
    imageType: NotRequired[Literal["2D", "Section", "3D"]]
    format: NotRequired[Literal["png", "jpg"]]
    width: NotRequired[int]
    height: NotRequired[int]


class GetRoomImageParameters(TypedDict, closed=True):
    zoneId: ElementId
    format: NotRequired[Literal["png", "jpg"]]
    width: NotRequired[int]
    height: NotRequired[int]
    offset: NotRequired[float]
    scale: NotRequired[float]
    backgroundColor: NotRequired[ColorRGB]


class CreateFavoritesFromElementsParameters(TypedDict, closed=True):
    favoritesFromElements: list[FavoritesFromElement]


class SetPropertyValuesOfElementsParameters(TypedDict, closed=True):
    elementPropertyValues: ElementPropertyValues


class SetPropertyValuesOfAttributesParameters(TypedDict, closed=True):
    attributePropertyValues: AttributePropertyValues


class CreatePropertyDefinitionsParameters(TypedDict, closed=True):
    propertyDefinitions: list[PropertyDefinitionArrayItem]


GetAttributesByTypeResult: TypeAlias = AttributeHeadersOrError


class CreateLayersParameters(TypedDict, closed=True):
    layerDataArray: list[LayerDataArrayItem]
    overwriteExisting: NotRequired[bool]


class CreateLayerCombinationsParameters(TypedDict, closed=True):
    layerCombinationDataArray: list[LayerCombinationDataArrayItem]
    overwriteExisting: NotRequired[bool]


class CreateBuildingMaterialsParameters(TypedDict, closed=True):
    buildingMaterialDataArray: list[BuildingMaterialDataArrayItem]
    overwriteExisting: NotRequired[bool]


class GetLayerCombinationsResult(TypedDict, closed=True):
    layerCombinations: list[LayerCombinationAttributeOrError]


class ReserveElementsResult(TypedDict, closed=True):
    executionResult: ExecutionResult
    conflicts: NotRequired[list[Conflict]]


class GetIssuesResult(TypedDict, closed=True):
    issues: list[Issue]


class GetDesignOptionsResult(TypedDict, closed=True):
    designOptions: list[DesignOption]


class GetDesignOptionSetsResult(TypedDict, closed=True):
    designOptionSets: list[DesignOptionSet]


class GetDesignOptionCombinationsResult(TypedDict, closed=True):
    designOptionCombinations: list[DesignOptionCombination]


class GetElementsByTypeParameters(TypedDict, closed=True):
    elementType: ElementType
    filters: NotRequired[list[ElementFilter]]
    databases: NotRequired[Databases]


class GetAllElementsParameters(TypedDict, closed=True):
    filters: NotRequired[list[ElementFilter]]
    databases: NotRequired[Databases]


class GetDetailsOfElementsResult(TypedDict, closed=True):
    detailsOfElements: list[DetailsOfElement]


class CreateWallsParameters(TypedDict, closed=True):
    wallsData: list[WallData]


class CreateZonesParameters(TypedDict, closed=True):
    zonesData: list[ZoneData]


class CreateLabelsParameters(TypedDict, closed=True):
    labelsData: list[LabelData]


class CreateGroupsParameters(TypedDict, closed=True):
    elementGroups: list[ElementGroupParameters]


class CreateCompositesParameters(TypedDict, closed=True):
    compositeDataArray: list[CompositeDataArrayItem]
    overwriteExisting: NotRequired[bool]


class CreateSurfacesParameters(TypedDict, closed=True):
    surfaceDataArray: list[SurfaceDataArrayItem]
    overwriteExisting: NotRequired[bool]


class GetBuildingMaterialPhysicalPropertiesResult(TypedDict, closed=True):
    properties: BuildingMaterialPhysicalPropertiesList


class AddFilesToEmbeddedLibraryParameters(TypedDict, closed=True):
    files: LibraryFileAdditions


class PublishPublisherSetParameters(TypedDict, closed=True):
    publisherSetName: str
    outputPath: NotRequired[str]
    selectedNavigatorItemIds: NotRequired[NavigatorItemIds]


class GetDatabaseIdFromNavigatorItemIdParameters(TypedDict, closed=True):
    navigatorItemIds: NavigatorItemIds


class GetDatabaseIdFromNavigatorItemIdResult(TypedDict, closed=True):
    databases: Databases


class CreateDetailsResult(TypedDict, closed=True):
    databases: Databases


class CreateWorksheetsResult(TypedDict, closed=True):
    databases: Databases


class CreateLayoutsResult(TypedDict, closed=True):
    databases: Databases


class GetViewSettingsParameters(TypedDict, closed=True):
    navigatorItemIds: NavigatorItemIds


class GetView2DTransformationsParameters(TypedDict, closed=True):
    databases: NotRequired[Databases]


class GetCurrentRevisionChangesOfLayoutsParameters(TypedDict, closed=True):
    layoutDatabaseIds: Databases


Elements: TypeAlias = list[ElementIdArrayItem]
AttributeIds: TypeAlias = list[AttributeIdArrayItem]


class GetSelectedElementsResult(TypedDict, closed=True):
    elements: Elements


GetElementsByTypeResult: TypeAlias = ElementsWithExecutionResultsOrError
GetAllElementsResult: TypeAlias = ElementsWithExecutionResultsOrError


class ChangeSelectionOfElementsParameters(TypedDict, closed=True):
    addElementsToSelection: NotRequired[Elements]
    removeElementsFromSelection: NotRequired[Elements]


class FilterElementsParameters(TypedDict, closed=True):
    elements: Elements
    filters: NotRequired[list[ElementFilter]]


class FilterElementsResult(TypedDict, closed=True):
    elements: Elements


class GetDetailsOfElementsParameters(TypedDict, closed=True):
    elements: Elements


class Get3DBoundingBoxesParameters(TypedDict, closed=True):
    elements: Elements


class GetSubelementsOfHierarchicalElementsParameters(TypedDict, closed=True):
    elements: Elements


class GetSubelementsOfHierarchicalElementsResult(TypedDict, closed=True):
    subelements: list[Subelement]


class GetConnectedElementsParameters(TypedDict, closed=True):
    elements: Elements
    connectedElementType: ElementType


GetConnectedElementsResult: TypeAlias = ConnectedElementsOrError


class GetCollisionsParameters(TypedDict, closed=True):
    elementsGroup1: Elements
    elementsGroup2: Elements
    settings: NotRequired[Settings]


class HighlightElementsParameters(TypedDict, closed=True):
    elements: Elements
    highlightedColors: list[list[int]]
    wireframe3D: NotRequired[bool]
    nonHighlightedColor: NotRequired[list[int]]


class DeleteElementsParameters(TypedDict, closed=True):
    elements: Elements


class GetGDLParametersOfElementsParameters(TypedDict, closed=True):
    elements: Elements


class GetClassificationsOfElementsParameters(TypedDict, closed=True):
    elements: Elements
    classificationSystemIds: ClassificationSystemIds


class CreateColumnsResult(TypedDict, closed=True):
    elements: Elements


class CreateWallsResult(TypedDict, closed=True):
    elements: Elements


class CreateBeamsResult(TypedDict, closed=True):
    elements: Elements


class CreateSlabsResult(TypedDict, closed=True):
    elements: Elements


class CreateWindowsResult(TypedDict, closed=True):
    elements: Elements


class CreateDoorsResult(TypedDict, closed=True):
    elements: Elements


class CreateOpeningsResult(TypedDict, closed=True):
    elements: Elements


class CreateMorphsResult(TypedDict, closed=True):
    elements: Elements


class CreateRoofsResult(TypedDict, closed=True):
    elements: Elements


class CreateAssociativeDimensionsResult(TypedDict, closed=True):
    elements: Elements


class CreateAssociativeDimensionsOnSectionResult(TypedDict, closed=True):
    elements: Elements


class CreateWallThicknessDimensionsResult(TypedDict, closed=True):
    elements: Elements


class CreateZonesResult(TypedDict, closed=True):
    elements: Elements


class CreatePolylinesResult(TypedDict, closed=True):
    elements: Elements


class CreateObjectsResult(TypedDict, closed=True):
    elements: Elements


class CreateMeshesResult(TypedDict, closed=True):
    elements: Elements


class CreateLabelsResult(TypedDict, closed=True):
    elements: Elements


class GetPropertyValuesOfElementsParameters(TypedDict, closed=True):
    elements: Elements
    properties: PropertyIds


class GetPropertyValuesOfAttributesParameters(TypedDict, closed=True):
    attributeIds: AttributeIds
    properties: PropertyIds


class CreateLayersResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateLayerCombinationsResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateBuildingMaterialsResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateCompositesResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class CreateSurfacesResult(TypedDict, closed=True):
    attributeIds: AttributeIds


class GetBuildingMaterialPhysicalPropertiesParameters(TypedDict, closed=True):
    attributeIds: AttributeIds


class GetLayerCombinationsParameters(TypedDict, closed=True):
    attributes: AttributeIds


class ReserveElementsParameters(TypedDict, closed=True):
    elements: Elements


class ReleaseElementsParameters(TypedDict, closed=True):
    elements: Elements


class UpdateDrawingsParameters(TypedDict, closed=True):
    elements: Elements


class CreateDrawingsResult(TypedDict, closed=True):
    elements: Elements


class FitInWindowParameters(TypedDict, closed=True):
    elements: NotRequired[Elements]


class AttachElementsToIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    elements: Elements
    type: IssueElementType


class DetachElementsFromIssueParameters(TypedDict, closed=True):
    issueId: IssueId
    elements: Elements


class GetElementsAttachedToIssueResult(TypedDict, closed=True):
    elements: Elements


class GetRevisionChangesOfElementsParameters(TypedDict, closed=True):
    elements: Elements


Hotlinks: TypeAlias = list["Hotlink"]


class GetHotlinksResult(TypedDict, closed=True):
    hotlinks: Hotlinks
