from __future__ import annotations
from typing import Any, List, Literal, TypedDict
from typing_extensions import NotRequired

### This file is automatically generated and split. Do not edit directly. ###


class PossibleNumericValue(TypedDict, closed=True):
    value: float
    flag: NotRequired[str]
    description: NotRequired[str]


PossibleNumericValues: TypeAlias = list[PossibleNumericValue]


class GDLParameterDetails(TypedDict, closed=True):
    name: str
    displayName: str
    index: int
    type: str
    dimension1: int
    dimension2: int
    value: Any
    valueDescription: NotRequired[str]
    isLocked: bool
    flags: list[Literal["Hidden", "HiddenFromScript", "Disabled", "Child", "Unique", "Fixed"]]
    possibleValues: NotRequired[PossibleStringValues | PossibleNumericValues]
    canHaveCustomValue: NotRequired[bool]


class SetGDLParameterByNameDetails(TypedDict, closed=True):
    name: str
    value: Any


class SetGDLParameterByIndexDetails(TypedDict, closed=True):
    index: int
    value: Any


SetGDLParameterDetails: TypeAlias = SetGDLParameterByNameDetails | SetGDLParameterByIndexDetails


class PolyArc(TypedDict, closed=True):
    begIndex: int
    endIndex: int
    arcAngle: float


class Coordinate2D(TypedDict, closed=True):
    x: float
    y: float


class Coordinate3D(TypedDict, closed=True):
    x: float
    y: float
    z: float


class Dimensions3D(TypedDict, closed=True):
    x: float
    y: float
    z: float


class ColorRGB(TypedDict, closed=True):
    red: float
    green: float
    blue: float


class Texture(TypedDict, closed=True):
    name: str
    rotationAngle: NotRequired[float]
    xSize: NotRequired[float]
    ySize: NotRequired[float]
    FillRectangle: NotRequired[bool]
    FitPicture: NotRequired[bool]
    mirrorX: NotRequired[bool]
    mirrorY: NotRequired[bool]
    useAlphaChannel: NotRequired[bool]
    alphaChannelChangesTransparency: NotRequired[bool]
    alphaChannelChangesSurfaceColor: NotRequired[bool]
    alphaChannelChangesAmbientColor: NotRequired[bool]
    alphaChannelChangesSpecularColor: NotRequired[bool]
    alphaChannelChangesDiffuseColor: NotRequired[bool]


class Error(TypedDict, closed=True):
    code: int
    message: str


class ErrorItem(TypedDict, closed=True):
    error: Error


class SuccessfulExecutionResult(TypedDict, closed=True):
    success: Literal[True]


class FailedExecutionResult(TypedDict, closed=True):
    success: Literal[False]
    error: Error


ExecutionResult: TypeAlias = SuccessfulExecutionResult | FailedExecutionResult
ExecutionResults: TypeAlias = list[ExecutionResult]
ElementType: TypeAlias = Literal[
    "Wall",
    "Column",
    "Beam",
    "Window",
    "Door",
    "Object",
    "Lamp",
    "Slab",
    "Roof",
    "Mesh",
    "Dimension",
    "RadialDimension",
    "LevelDimension",
    "AngleDimension",
    "Text",
    "Label",
    "Zone",
    "Hatch",
    "Line",
    "PolyLine",
    "Arc",
    "Circle",
    "Spline",
    "Hotspot",
    "CutPlane",
    "Camera",
    "CamSet",
    "Group",
    "SectElem",
    "Drawing",
    "Picture",
    "Detail",
    "Elevation",
    "InteriorElevation",
    "Worksheet",
    "Hotlink",
    "CurtainWall",
    "CurtainWallSegment",
    "CurtainWallFrame",
    "CurtainWallPanel",
    "CurtainWallJunction",
    "CurtainWallAccessory",
    "Shell",
    "Skylight",
    "Morph",
    "ChangeMarker",
    "Stair",
    "Riser",
    "Tread",
    "StairStructure",
    "Railing",
    "RailingToprail",
    "RailingHandrail",
    "RailingRail",
    "RailingPost",
    "RailingInnerPost",
    "RailingBaluster",
    "RailingPanel",
    "RailingSegment",
    "RailingNode",
    "RailingBalusterSet",
    "RailingPattern",
    "RailingToprailEnd",
    "RailingHandrailEnd",
    "RailingRailEnd",
    "RailingToprailConnection",
    "RailingHandrailConnection",
    "RailingRailConnection",
    "RailingEndFinish",
    "BeamSegment",
    "ColumnSegment",
    "Opening",
    "Unknown",
]
ElementFilter: TypeAlias = Literal[
    "IsEditable",
    "IsVisibleByLayer",
    "IsVisibleByRenovation",
    "IsVisibleByStructureDisplay",
    "IsVisibleIn3D",
    "OnActualFloor",
    "OnActualLayout",
    "InMyWorkspace",
    "IsIndependent",
    "InCroppedView",
    "HasAccessRight",
    "IsOverriddenByRenovation",
]
WindowType: TypeAlias = Literal[
    "FloorPlan",
    "Section",
    "Details",
    "3DModel",
    "Layout",
    "Drawing",
    "CustomText",
    "CustomDraw",
    "MasterLayout",
    "Elevation",
    "InteriorElevation",
    "Worksheet",
    "Report",
    "3DDocument",
    "External3D",
    "Movie3D",
    "MovieRendering",
    "Rendering",
    "ModelCompare",
    "Interactive Schedule",
    "Unknown",
]
LengthType: TypeAlias = Literal[
    "Meter",
    "Decimeter",
    "Centimeter",
    "Millimeter",
    "FootFracInch",
    "FootDecInch",
    "DecFoot",
    "FracInch",
    "DecInch",
]
AreaType: TypeAlias = Literal["SquareMeter", "SquareCentimeter", "SquareMillimeter", "SquareFoot", "SquareInch"]
VolumeType: TypeAlias = Literal[
    "CubicMeter",
    "Liter",
    "CubicCentimeter",
    "CubicMillimeter",
    "CubicFoot",
    "CubicInch",
    "CubicYard",
    "Gallon",
]
AngleType: TypeAlias = Literal["DecimalDegree", "DegreeMinSec", "Grad", "Radian", "Surveyors"]
AccuracyType: TypeAlias = Literal["Off", "ShowSmall5", "ShowSmall25", "ShowSmall1", "ShowSmall01", "InchCaseFractions"]


class IssueId(TypedDict, closed=True):
    guid: Guid


class IssueIdArrayItem(TypedDict, closed=True):
    issueId: IssueId


Issues: TypeAlias = list[IssueIdArrayItem]
IssueElementType: TypeAlias = Literal["Creation", "Highlight", "Deletion", "Modification"]
IssueCommentStatus: TypeAlias = Literal["Error", "Warning", "Info", "Unknown"]


class PropertyGroupId(TypedDict, closed=True):
    guid: Guid


class PropertyGroupIdArrayItem(TypedDict, closed=True):
    propertyGroupId: PropertyGroupId


class PropertyId(TypedDict, closed=True):
    guid: Guid


class PropertyIdArrayItem(TypedDict, closed=True):
    propertyId: PropertyId


PropertyIds: TypeAlias = list[PropertyIdArrayItem]


class PropertyDetails(TypedDict, closed=True):
    propertyId: PropertyId
    propertyType: Literal["StaticBuiltIn", "DynamicBuiltIn", "Custom"]
    propertyGroupName: str
    propertyName: str
    propertyCollectionType: Literal[
        "Undefined",
        "Single",
        "List",
        "SingleChoiceEnumeration",
        "MultipleChoiceEnumeration",
    ]
    propertyValueType: Literal["Undefined", "Integer", "Real", "String", "Boolean", "Guid"]
    propertyMeasureType: Literal["Undefined", "Default", "Length", "Area", "Volume", "Angle"]
    propertyIsEditable: bool


class PropertyValue(TypedDict, closed=True):
    value: str


class PropertyValueArrayItem(TypedDict, closed=True):
    propertyValue: PropertyValue


PropertyValueOrErrorItem: TypeAlias = PropertyValueArrayItem | ErrorItem
PropertyValues: TypeAlias = list[PropertyValueOrErrorItem]


class PropertyValuesArrayItem(TypedDict, closed=True):
    propertyValues: PropertyValues


PropertyValuesOrError: TypeAlias = PropertyValuesArrayItem | ErrorItem
PropertyValuesOrErrorArray: TypeAlias = list[PropertyValuesOrError]
PropertyIdOrError: TypeAlias = PropertyIdArrayItem | ErrorItem
PropertyIdOrErrorArray: TypeAlias = list[PropertyIdOrError]
PropertyDataType: TypeAlias = Literal[
    "number",
    "integer",
    "string",
    "boolean",
    "length",
    "area",
    "volume",
    "angle",
    "numberList",
    "integerList",
    "stringList",
    "booleanList",
    "lengthList",
    "areaList",
    "volumeList",
    "angleList",
    "singleEnum",
    "multiEnum",
]


class DisplayValueEnumId(TypedDict, closed=True):
    type: Literal["displayValue"]
    displayValue: str


class NonLocalizedValueEnumId(TypedDict, closed=True):
    type: Literal["nonLocalizedValue"]
    nonLocalizedValue: str


EnumValueId: TypeAlias = DisplayValueEnumId | NonLocalizedValueEnumId


class EnumValueIdArrayItem(TypedDict, closed=True):
    enumValueId: EnumValueId


EnumValueIds: TypeAlias = list[EnumValueIdArrayItem]


class UserUndefinedPropertyValue(TypedDict, closed=True):
    type: PropertyDataType
    status: Literal["userUndefined"]


class NotAvailablePropertyValue(TypedDict, closed=True):
    type: PropertyDataType
    status: Literal["notAvailable"]


class NormalNumberPropertyValue(TypedDict, closed=True):
    type: Literal["number"]
    status: Literal["normal"]
    value: float


class NormalIntegerPropertyValue(TypedDict, closed=True):
    type: Literal["integer"]
    status: Literal["normal"]
    value: int


class NormalStringPropertyValue(TypedDict, closed=True):
    type: Literal["string"]
    status: Literal["normal"]
    value: str


class NormalBooleanPropertyValue(TypedDict, closed=True):
    type: Literal["boolean"]
    status: Literal["normal"]
    value: bool


class NormalLengthPropertyValue(TypedDict, closed=True):
    type: Literal["length"]
    status: Literal["normal"]
    value: float


class NormalAreaPropertyValue(TypedDict, closed=True):
    type: Literal["area"]
    status: Literal["normal"]
    value: float


class NormalVolumePropertyValue(TypedDict, closed=True):
    type: Literal["volume"]
    status: Literal["normal"]
    value: float


class NormalAnglePropertyValue(TypedDict, closed=True):
    type: Literal["angle"]
    status: Literal["normal"]
    value: float


class NormalNumberListPropertyValue(TypedDict, closed=True):
    type: Literal["numberList"]
    status: Literal["normal"]
    value: list[float]


class NormalIntegerListPropertyValue(TypedDict, closed=True):
    type: Literal["integerList"]
    status: Literal["normal"]
    value: list[int]


class NormalStringListPropertyValue(TypedDict, closed=True):
    type: Literal["stringList"]
    status: Literal["normal"]
    value: list[str]


class NormalBooleanListPropertyValue(TypedDict, closed=True):
    type: Literal["booleanList"]
    status: Literal["normal"]
    value: list[bool]


class NormalLengthListPropertyValue(TypedDict, closed=True):
    type: Literal["lengthList"]
    status: Literal["normal"]
    value: list[float]


class NormalAreaListPropertyValue(TypedDict, closed=True):
    type: Literal["areaList"]
    status: Literal["normal"]
    value: list[float]


class NormalVolumeListPropertyValue(TypedDict, closed=True):
    type: Literal["volumeList"]
    status: Literal["normal"]
    value: list[float]


class NormalAngleListPropertyValue(TypedDict, closed=True):
    type: Literal["angleList"]
    status: Literal["normal"]
    value: list[float]


class NormalSingleEnumPropertyValue(TypedDict, closed=True):
    type: Literal["singleEnum"]
    status: Literal["normal"]
    value: EnumValueId


class NormalMultiEnumPropertyValue(TypedDict, closed=True):
    type: Literal["multiEnum"]
    status: Literal["normal"]
    value: EnumValueIds


class ExpressionDefaultValue(TypedDict, closed=True):
    expressions: list[str]


class ClassificationSystemId(TypedDict, closed=True):
    guid: Guid


class ClassificationSystemIdArrayItem(TypedDict, closed=True):
    classificationSystemId: ClassificationSystemId


ClassificationSystemIds: TypeAlias = list[ClassificationSystemIdArrayItem]


class ClassificationItemId(TypedDict, closed=True):
    guid: Guid


class ClassificationItemIdArrayItem(TypedDict, closed=True):
    classificationItemId: ClassificationItemId


class ClassificationId(TypedDict, closed=True):
    classificationSystemId: ClassificationSystemId
    classificationItemId: NotRequired[ClassificationItemId]


class ClassificationIdArrayItem(TypedDict, closed=True):
    classificationId: ClassificationId


ClassificationIdOrError: TypeAlias = ClassificationIdArrayItem | ErrorItem
ClassificationIdsOrErrors: TypeAlias = list[ClassificationIdOrError]


class ElementClassificationItemArray(TypedDict, closed=True):
    classificationIds: ClassificationIdsOrErrors


ElementClassificationOrError: TypeAlias = ElementClassificationItemArray | ErrorItem
ElementClassificationsOrErrors: TypeAlias = list[ElementClassificationOrError]


class BoundingBox3D(TypedDict, closed=True):
    xMin: float
    yMin: float
    zMin: float
    xMax: float
    yMax: float
    zMax: float


class BoundingBox3DArrayItem(TypedDict, closed=True):
    boundingBox3D: BoundingBox3D


BoundingBox3DOrError: TypeAlias = BoundingBox3DArrayItem | ErrorItem
BoundingBoxes3D: TypeAlias = list[BoundingBox3DOrError]


class LibPartUnId(TypedDict, closed=True):
    guid: Guid


class LibPartDetails(TypedDict, closed=True):
    name: str
    parentUnID: LibPartUnId
    ownUnID: LibPartUnId


class NavigatorItemId(TypedDict, closed=True):
    guid: Guid


class DatabaseId(TypedDict, closed=True):
    guid: Guid


class Zoom(TypedDict, closed=True):
    xMin: float
    yMin: float
    xMax: float
    yMax: float


class ViewSettings(TypedDict, closed=True):
    modelViewOptions: NotRequired[str]
    layerCombination: NotRequired[str]
    dimensionStyle: NotRequired[str]
    penSetName: NotRequired[str]
    graphicOverrideCombination: NotRequired[str]
    drawingScale: NotRequired[int]
    saveZoom: NotRequired[bool]
    ignoreSavedZoom: NotRequired[bool]
    zoom: NotRequired[Zoom]


ViewSettingsOrError: TypeAlias = ViewSettings | ErrorItem


class ViewTransformations(TypedDict, closed=True):
    zoom: Zoom
    rotation: float


ViewTransformationsOrError: TypeAlias = ViewTransformations | ErrorItem


class Hole2D(TypedDict, closed=True):
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]


Holes2D: TypeAlias = list[Hole2D]


class Hole3D(TypedDict, closed=True):
    polygonCoordinates: list[Coordinate3D]
    polygonArcs: NotRequired[list[PolyArc]]


Holes3D: TypeAlias = list[Hole3D]


class BeamDetails(TypedDict, closed=True):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    level: float
    offset: float
    slantAngle: float
    arcAngle: float
    verticalCurveHeight: float


class ColumnDetails(TypedDict, closed=True):
    origin: Coordinate2D
    zCoordinate: float
    height: float
    bottomOffset: float


class PolylineDetails(TypedDict, closed=True):
    coordinates: list[Coordinate2D]
    arcs: NotRequired[list[PolyArc]]
    zCoordinate: float


class CurtainWallDetails(TypedDict, closed=True):
    height: NotRequired[float]
    angle: NotRequired[float]


class CurtainWallSegmentDetails(TypedDict, closed=True):
    begCoordinate: Coordinate3D
    endCoordinate: Coordinate3D
    extrusionVector: Coordinate3D
    gridOrigin: Coordinate3D
    gridAngle: float
    arcOrigin: NotRequired[Coordinate3D]
    isNegativeArc: NotRequired[bool]


CurtainWallFrameType: TypeAlias = Literal["Deleted", "Division", "Corner", "Boundary", "Custom"]


class PanelConnectionHole(TypedDict, closed=True):
    d: float
    w: float


class FrameContour(TypedDict, closed=True):
    a1: float
    a2: float
    b1: float
    b2: float


class CurtainWallFrameDetails(TypedDict, closed=True):
    begCoordinate: Coordinate3D
    endCoordinate: Coordinate3D
    orientationVector: Coordinate3D
    panelConnectionHole: PanelConnectionHole
    frameContour: FrameContour
    segmentIndex: float
    className: str
    type: CurtainWallFrameType


MeshSkirtType: TypeAlias = Literal["SurfaceOnlyWithoutSkirt", "WithSkirt", "SolidBodyWithSkirt"]


class Subline(TypedDict, closed=True):
    coordinates: list[Coordinate3D]


class MeshDetails(TypedDict, closed=True):
    level: float
    skirtType: MeshSkirtType
    skirtLevel: float
    polygonCoordinates: list[Coordinate3D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes3D]
    sublines: NotRequired[list[Subline]]


class NotYetSupportedElementTypeDetails(TypedDict, closed=True):
    error: str


class RevisionIssueId(TypedDict, closed=True):
    guid: Guid


class DocumentRevisionId(TypedDict, closed=True):
    guid: Guid


class RevisionCustomSchemeDatum(TypedDict, closed=True):
    customSchemeKey: Guid
    customSchemeValue: str


RevisionCustomSchemeData: TypeAlias = list[RevisionCustomSchemeDatum]


class DocumentRevisionReference(TypedDict, closed=True):
    revisionId: DocumentRevisionId


DocumentRevisionReferences: TypeAlias = list[DocumentRevisionReference]


class RevisionIssue(TypedDict, closed=True):
    revisionIssueId: RevisionIssueId
    id: str
    description: str
    issueTime: str
    issuedByUser: str
    overrideRevisionIDOfAllIncludedLayouts: bool
    createNewRevisionInAllIncludedLayouts: bool
    markersVisibleSinceIndex: NotRequired[int]
    isIssued: bool
    documentRevisions: NotRequired[DocumentRevisionReferences]
    customSchemeData: NotRequired[RevisionCustomSchemeData]


class RevisionChange(TypedDict, closed=True):
    id: str
    description: str
    lastModifiedTime: str
    modifiedByUser: str
    isIssued: bool
    firstRevisionIssueId: NotRequired[RevisionIssueId]
    isArchived: bool
    customSchemeData: NotRequired[RevisionCustomSchemeData]


class LayoutInfo(TypedDict, closed=True):
    id: str
    databaseId: DatabaseId
    name: str
    masterLayoutName: str
    width: float
    height: float
    subsetId: str
    subsetName: str
    ownerUser: str
    customSchemeData: NotRequired[RevisionCustomSchemeData]


class Change(TypedDict, closed=True):
    id: str


class DocumentRevision(TypedDict, closed=True):
    revisionId: DocumentRevisionId
    id: str
    finalId: str
    ownerUser: str
    status: Literal["Actual", "Issued"]
    changes: NotRequired[list[Change]]
    layoutInfo: LayoutInfo


class RevisionChangesArrayItem(TypedDict, closed=True):
    revisionChanges: NotRequired[list[RevisionChange]]


RevisionChangesOfEntities: TypeAlias = RevisionChangesArrayItem | ErrorItem


class StoryParameters(TypedDict, closed=True):
    index: int
    floorId: int
    dispOnSections: bool
    level: float
    name: str


StoriesParameters: TypeAlias = list[StoryParameters]


class StorySettings(TypedDict, closed=True):
    dispOnSections: bool
    level: float
    name: str


StoriesSettings: TypeAlias = list[StorySettings]


class AutomaticZoneGeometry(TypedDict, closed=True):
    referencePosition: Coordinate2D


class ManualZoneGeometry(TypedDict, closed=True):
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]


ZoneCreationGeometry: TypeAlias = AutomaticZoneGeometry | ManualZoneGeometry


class WallSettings(TypedDict, closed=True):
    begCoordinate: NotRequired[Coordinate2D]
    endCoordinate: NotRequired[Coordinate2D]
    height: NotRequired[float]
    bottomOffset: NotRequired[float]
    offset: NotRequired[float]
    begThickness: NotRequired[float]
    endThickness: NotRequired[float]


TypeSpecificSettings: TypeAlias = WallSettings


class PropertyGroup(TypedDict, closed=True):
    name: str
    description: NotRequired[str]


class PropertyGroupArrayItem(TypedDict, closed=True):
    propertyGroup: PropertyGroup


class EnumValue(TypedDict, closed=True):
    enumValueId: NotRequired[EnumValueId]
    displayValue: str
    nonLocalizedValue: NotRequired[str]


class PossibleEnumValue(TypedDict, closed=True):
    enumValue: EnumValue


class Group(TypedDict, closed=True):
    propertyGroupId: NotRequired[PropertyGroupId]
    name: NotRequired[str]


Favorites: TypeAlias = list[str]


class BuildingMaterialPhysicalProperties(TypedDict, closed=True):
    thermalConductivity: float
    density: float
    heatCapacity: float
    embodiedEnergy: float
    embodiedCarbon: float


class ProjectInfoField(TypedDict, closed=True):
    projectInfoId: str
    projectInfoName: str
    projectInfoValue: str


LibraryPartType: TypeAlias = Literal[
    "Window",
    "Door",
    "Object",
    "Lamp",
    "Room",
    "Property",
    "PlanSign",
    "Label",
    "Macro",
    "Pict",
    "ListScheme",
    "Skylight",
    "OpeningSymbol",
]


class FavoritesWrapper(TypedDict, closed=True):
    favorites: Favorites


FavoritesOrError: TypeAlias = FavoritesWrapper | ErrorItem


class GroupId(TypedDict, closed=True):
    guid: Guid


class GroupIdArrayItem(TypedDict, closed=True):
    groupId: GroupId


GroupIdOrError: TypeAlias = GroupIdArrayItem | ErrorItem


class Length(TypedDict, closed=True):
    unit: LengthType
    accuracy: AccuracyType
    decimals: int
    roundInch: NotRequired[int]


class Area(TypedDict, closed=True):
    unit: AreaType
    accuracy: AccuracyType
    decimals: int


class Volume(TypedDict, closed=True):
    unit: VolumeType
    accuracy: AccuracyType
    decimals: int


class Angle(TypedDict, closed=True):
    unit: AngleType
    decimals: int
    accuracy: int


class Details(TypedDict, closed=True):
    floorIndex: NotRequired[float]
    layerIndex: NotRequired[float]
    drawIndex: NotRequired[float]
    typeSpecificDetails: NotRequired[TypeSpecificSettings]


class Settings(TypedDict, closed=True):
    volumeTolerance: float
    performSurfaceCheck: bool
    surfaceTolerance: float


HighlightElementsResult: TypeAlias = ExecutionResult


class MoveVector(TypedDict, closed=True):
    x: float
    y: float
    z: float


class Level(TypedDict, closed=True):
    levelHeight: float
    levelAngle: float


class Library(TypedDict, closed=True):
    name: str
    path: str
    type: str
    available: NotRequired[bool]
    readOnly: NotRequired[bool]
    twServerUrl: NotRequired[str]
    urlWebLibrary: NotRequired[str]


class User(TypedDict, closed=True):
    userId: float
    userName: str


ReleaseElementsResult: TypeAlias = ExecutionResult
UpdateDrawingsResult: TypeAlias = ExecutionResult


class DetailsDatum(TypedDict, closed=True):
    name: str
    referenceId: str


class WorksheetsDatum(TypedDict, closed=True):
    name: str
    referenceId: str


class LayoutsDatum(TypedDict, closed=True):
    masterLayoutName: str
    layoutName: str


class SubsetsDatum(TypedDict, closed=True):
    name: str
    parentNavigatorItemId: NotRequired[NavigatorItemId]
    ownPrefix: NotRequired[str]
    customNumber: NotRequired[str]


class DrawingsDatum(TypedDict, closed=True):
    navigatorItemId: NavigatorItemId
    layoutDatabaseId: NotRequired[DatabaseId]
    name: str
    position: Coordinate2D
    scale: NotRequired[float]


class ModelViewOption(TypedDict, closed=True):
    name: str


class NavigatorItemIdsWithViewSetting(TypedDict, closed=True):
    navigatorItemId: NavigatorItemId
    viewSettings: ViewSettings


class CutPlane(TypedDict, closed=True):
    pa: float
    pb: float
    pc: float
    pd: float


class Comment(TypedDict, closed=True):
    guid: Guid
    author: str
    text: str
    status: IssueCommentStatus
    creaTime: int


class Coordinates(TypedDict, closed=True):
    x: float
    y: float
    z: float


class ColumnData(TypedDict, closed=True):
    coordinates: Coordinates
    height: NotRequired[float]
    axisRotationAngle: NotRequired[float]


class SlabData(TypedDict, closed=True):
    level: float
    thickness: NotRequired[float]
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]


class PolylineData(TypedDict, closed=True):
    floorInd: NotRequired[float]
    layerIndex: NotRequired[int]
    linePenIndex: NotRequired[int]
    lineTypeIndex: NotRequired[int]
    penWeightMm: NotRequired[float]
    coordinates: list[Coordinate2D]
    arcs: NotRequired[list[PolyArc]]


class ObjectData(TypedDict, closed=True):
    libraryPartName: str
    coordinates: Coordinate3D
    dimensions: NotRequired[Dimensions3D]


class MeshData(TypedDict, closed=True):
    floorIndex: NotRequired[int]
    level: NotRequired[float]
    skirtType: NotRequired[MeshSkirtType]
    skirtLevel: NotRequired[float]
    polygonCoordinates: list[Coordinate3D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes3D]
    sublines: NotRequired[list[Subline]]


class BeamData(TypedDict, closed=True):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    offset: NotRequired[float]
    slantAngle: NotRequired[float]
    arcAngle: NotRequired[float]
    verticalCurveHeight: NotRequired[float]


class ProjectLocation(TypedDict, closed=True):
    longitude: float
    latitude: float
    altitude: float
    north: float


class SurveyPointPosition(TypedDict, closed=True):
    eastings: float
    northings: float
    elevation: float


class GeoReferencingParameters(TypedDict, closed=True):
    crsName: str
    description: str
    geodeticDatum: str
    verticalDatum: str
    mapProjection: str
    mapZone: str


class SurveyPoint(TypedDict, closed=True):
    position: SurveyPointPosition
    geoReferencingParameters: GeoReferencingParameters


class ElementId(TypedDict, closed=True):
    guid: Guid


class AttributeId(TypedDict, closed=True):
    guid: Guid


class GuidId(TypedDict, closed=True):
    guid: Guid


class DesignOptionIdArrayItem(TypedDict, closed=True):
    designOptionId: GuidId


class LayersOfLayerCombinationItem(TypedDict, closed=True):
    attributeId: AttributeId
    isHidden: bool
    isLocked: bool
    isWireframe: bool
    intersectionGroupNr: int


LayersOfLayerCombination: TypeAlias = list[LayersOfLayerCombinationItem]


class LayerCombinationAttributeDetails(TypedDict, closed=True):
    attributeId: AttributeId
    attributeIndex: NotRequired[int]
    name: str
    layers: LayersOfLayerCombination


class LayerCombinationAttribute(TypedDict, closed=True):
    layerCombination: LayerCombinationAttributeDetails


LayerCombinationAttributeOrError: TypeAlias = LayerCombinationAttribute | ErrorItem
SetGDLParameterArray: TypeAlias = list[SetGDLParameterDetails]
GDLParameterArray: TypeAlias = list[GDLParameterDetails]


class GDLParameterList(TypedDict, closed=True):
    parameters: GDLParameterArray


class ElementPropertyValue(TypedDict, closed=True):
    elementId: ElementId
    propertyId: PropertyId
    propertyValue: PropertyValue


ElementPropertyValues: TypeAlias = list[ElementPropertyValue]


class AttributePropertyValue(TypedDict, closed=True):
    attributeId: AttributeId
    propertyId: PropertyId
    propertyValue: PropertyValue


AttributePropertyValues: TypeAlias = list[AttributePropertyValue]
NormalOrUserUndefinedPropertyValue: TypeAlias = (
    NormalNumberPropertyValue
    | NormalIntegerPropertyValue
    | NormalStringPropertyValue
    | NormalBooleanPropertyValue
    | NormalLengthPropertyValue
    | NormalAreaPropertyValue
    | NormalVolumePropertyValue
    | NormalAnglePropertyValue
    | NormalNumberListPropertyValue
    | NormalIntegerListPropertyValue
    | NormalStringListPropertyValue
    | NormalBooleanListPropertyValue
    | NormalLengthListPropertyValue
    | NormalAreaListPropertyValue
    | NormalVolumeListPropertyValue
    | NormalAngleListPropertyValue
    | NormalSingleEnumPropertyValue
    | NormalMultiEnumPropertyValue
    | UserUndefinedPropertyValue
)
PropertyValueDetails: TypeAlias = NormalOrUserUndefinedPropertyValue | NotAvailablePropertyValue


class BasicDefaultValue(TypedDict, closed=True):
    basicDefaultValue: PropertyValueDetails


PropertyDefaultValue: TypeAlias = BasicDefaultValue | ExpressionDefaultValue


class ElementClassification(TypedDict, closed=True):
    elementId: ElementId
    classificationId: ClassificationId


ElementClassifications: TypeAlias = list[ElementClassification]


class NavigatorItemIdArrayItem(TypedDict, closed=True):
    navigatorItemId: NavigatorItemId


class DatabaseIdArrayItem(TypedDict, closed=True):
    databaseId: DatabaseId


class WallDetails(TypedDict, closed=True):
    geometryType: Literal["Straight", "Trapezoid", "Polygonal"]
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    height: float
    bottomOffset: float
    offset: float
    arcAngle: NotRequired[float]
    begThickness: NotRequired[float]
    endThickness: NotRequired[float]
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]
    structureType: NotRequired[Literal["Basic", "Composite", "Profile"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    profileId: NotRequired[AttributeId]


class SlabDetails(TypedDict, closed=True):
    thickness: float
    level: float
    offsetFromTop: float
    zCoordinate: float
    polygonOutline: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: Holes2D
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]


class LinkData(TypedDict, closed=True):
    referredView: NotRequired[ElementId]
    referredDrawing: NotRequired[ElementId]
    referredPMViewPoint: NotRequired[ElementId]


class DetailWorksheetDetails(TypedDict, closed=True):
    basePoint: Coordinate2D
    angle: float
    markerId: ElementId
    detailName: str
    detailIdStr: str
    isHorizontalMarker: bool
    isWindowOpened: bool
    clipPolygon: list[Coordinate2D]
    linkData: LinkData


class LibPartBasedElementDetails(TypedDict, closed=True):
    libPart: LibPartDetails
    ownerElementId: NotRequired[ElementId]
    ownerElementType: NotRequired[ElementType]


class ObjectDetails(TypedDict, closed=True):
    libPart: LibPartDetails
    ownerElementId: NotRequired[ElementId]
    ownerElementType: NotRequired[ElementType]
    origin: Coordinate3D
    dimensions: Coordinate3D
    angle: float


class ZoneDetails(TypedDict, closed=True):
    name: str
    numberStr: str
    categoryAttributeId: AttributeId
    stampPosition: Coordinate2D
    isManual: bool
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]
    zCoordinate: float


class PropertyDefinition(TypedDict, closed=True):
    name: str
    description: str
    type: PropertyDataType
    isEditable: bool
    defaultValue: NotRequired[PropertyDefaultValue]
    possibleEnumValues: NotRequired[list[PossibleEnumValue]]
    availability: list[ClassificationItemIdArrayItem]
    group: Group


class PropertyDefinitionArrayItem(TypedDict, closed=True):
    propertyDefinition: PropertyDefinition


class ZoneBoundary(TypedDict, closed=True):
    connectedElementId: ElementId
    isExternal: bool
    neighbouringZoneElementId: ElementId
    area: float
    polygonOutline: list[Coordinate3D]


class ZoneBoundariesWrapper(TypedDict, closed=True):
    zoneBoundaries: list[ZoneBoundary]


ZoneBoundariesOrError: TypeAlias = ZoneBoundariesWrapper | ErrorItem


class BuildingMaterialPhysicalPropertiesArrayItem(TypedDict, closed=True):
    properties: BuildingMaterialPhysicalProperties


ProjectInfoFields: TypeAlias = list[ProjectInfoField]


class LibraryFileAddition(TypedDict, closed=True):
    inputPath: str
    outputPath: str
    type: NotRequired[LibraryPartType]


class AttributeHeader(TypedDict, closed=True):
    attributeId: AttributeId
    index: float
    name: str


AttributeHeaders: TypeAlias = list[AttributeHeader]


class AttributeHeadersWrapper(TypedDict, closed=True):
    attributes: AttributeHeaders


AttributeHeadersOrError: TypeAlias = AttributeHeadersWrapper | ErrorItem


class ElementsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    details: Details


class Collision(TypedDict, closed=True):
    elementId1: ElementId
    elementId2: ElementId
    hasBodyCollision: bool
    hasClearenceCollision: bool


class ElementsWithMoveVector(TypedDict, closed=True):
    elementId: ElementId
    moveVector: MoveVector
    copy: NotRequired[bool]


class ElementsWithGDLParameter(TypedDict, closed=True):
    elementId: ElementId
    gdlParameters: SetGDLParameterArray


class WindowsDatum(TypedDict, closed=True):
    ownerWallId: ElementId
    centerOffset: float
    sillHeight: NotRequired[float]
    width: NotRequired[float]
    height: NotRequired[float]


class DoorsDatum(TypedDict, closed=True):
    ownerWallId: ElementId
    centerOffset: float
    sillHeight: NotRequired[float]
    width: NotRequired[float]
    height: NotRequired[float]


class OpeningsDatum(TypedDict, closed=True):
    ownerElementId: ElementId
    basePoint: Coordinate3D
    width: NotRequired[float]
    height: NotRequired[float]


class MorphsDatum(TypedDict, closed=True):
    basePoint: Coordinate3D
    size: Dimensions3D
    buildingMaterialId: NotRequired[AttributeId]


class RoofsDatum(TypedDict, closed=True):
    level: float
    thickness: NotRequired[float]
    polygonCoordinates: list[Coordinate2D]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]
    eavesOverhang: NotRequired[float]
    levels: NotRequired[list[Level]]
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]


class WitnessPoint(TypedDict, closed=True):
    elementId: ElementId
    line: NotRequired[bool]
    inIndex: NotRequired[int]
    special: NotRequired[int]
    nodeType: NotRequired[int]
    nodeStatus: NotRequired[int]
    nodeId: NotRequired[float]


class DimensionsDatum(TypedDict, closed=True):
    referencePoint: Coordinate2D
    direction: Coordinate2D
    floorIndex: NotRequired[float]
    witnessPoints: list[WitnessPoint]


class DimensionsDatum1(TypedDict, closed=True):
    sectionElementId: ElementId
    referencePoint: Coordinate2D
    preset: Literal[
        "WallCompositeFaces",
        "WallSkinBorders",
        "SlabCompositeFaces",
        "SlabSkinBorders",
        "BeamOrColumnRefLineEndPoints",
        "BeamOrColumnBoundingBoxCorners",
        "DoorWindowWallHoleCorners",
        "DoorWindowModelHotspots",
    ]
    direction: NotRequired[Coordinate2D]
    skinBorderIndices: NotRequired[list[int]]
    beginPlane: NotRequired[bool]
    totalSizePlane: NotRequired[bool]
    placeOnTop: NotRequired[bool]


class DimensionsDatum2(TypedDict, closed=True):
    wallId: ElementId
    referencePoint: Coordinate2D
    direction: Coordinate2D


class WallsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    begCoordinate: NotRequired[Coordinate2D]
    endCoordinate: NotRequired[Coordinate2D]
    height: NotRequired[float]
    thickness: NotRequired[float]
    bottomOffset: NotRequired[float]
    offset: NotRequired[float]
    structureType: NotRequired[Literal["Basic", "Composite", "Profile"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    profileId: NotRequired[AttributeId]


class BeamsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    begCoordinate: NotRequired[Coordinate2D]
    endCoordinate: NotRequired[Coordinate2D]
    level: NotRequired[float]
    offset: NotRequired[float]
    slantAngle: NotRequired[float]
    arcAngle: NotRequired[float]
    verticalCurveHeight: NotRequired[float]


class SlabsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    zCoordinate: NotRequired[float]
    thickness: NotRequired[float]
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]


class ColumnsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    origin: NotRequired[Coordinate2D]
    zCoordinate: NotRequired[float]
    height: NotRequired[float]
    bottomOffset: NotRequired[float]
    axisRotationAngle: NotRequired[float]


class WindowsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    width: NotRequired[float]
    height: NotRequired[float]
    sillHeight: NotRequired[float]
    centerOffset: NotRequired[float]


class DoorsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    width: NotRequired[float]
    height: NotRequired[float]
    sillHeight: NotRequired[float]
    centerOffset: NotRequired[float]


class MorphsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    translation: NotRequired[Coordinate3D]
    rotationDegreesZ: NotRequired[float]
    buildingMaterialId: NotRequired[AttributeId]


class RoofsWithDetail(TypedDict, closed=True):
    elementId: ElementId
    level: NotRequired[float]
    thickness: NotRequired[float]
    eavesOverhang: NotRequired[float]
    levels: NotRequired[list[Level]]
    structureType: NotRequired[Literal["Basic", "Composite"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    polygonOutline: NotRequired[list[Coordinate2D]]
    polygonArcs: NotRequired[list[PolyArc]]
    holes: NotRequired[Holes2D]


class FavoritesFromElement(TypedDict, closed=True):
    elementId: ElementId
    favorite: str


class LayerDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    isHidden: NotRequired[bool]
    isLocked: NotRequired[bool]
    isWireframe: NotRequired[bool]
    intersectionGroupNr: NotRequired[int]


class LayerCombinationDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    layers: LayersOfLayerCombination


class BuildingMaterialDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    id: NotRequired[str]
    manufacturer: NotRequired[str]
    description: NotRequired[str]
    connPriority: NotRequired[int]
    cutFillIndex: NotRequired[int]
    cutFillPen: NotRequired[int]
    cutFillBackgroundPen: NotRequired[int]
    cutSurfaceIndex: NotRequired[int]
    thermalConductivity: NotRequired[float]
    density: NotRequired[float]
    heatCapacity: NotRequired[float]
    embodiedEnergy: NotRequired[float]
    embodiedCarbon: NotRequired[float]


class Conflict(TypedDict, closed=True):
    elementId: ElementId
    user: User


class Issue(TypedDict, closed=True):
    issueId: IssueId
    name: str
    parentIssueId: IssueId
    creaTime: int
    modiTime: int
    tagText: str
    tagTextElementId: ElementId
    isTagTextElemVisible: bool


class DesignOption(TypedDict, closed=True):
    designOptionId: GuidId
    name: str
    id: str
    ownerSetName: str


class DesignOptionSet(TypedDict, closed=True):
    designOptionSetId: GuidId
    name: str
    designOptions: list[DesignOptionIdArrayItem]


class DesignOptionCombination(TypedDict, closed=True):
    designOptionCombinationId: GuidId
    name: str
    activeDesignOptions: NotRequired[list[DesignOptionIdArrayItem]]


class ZoneData(TypedDict, closed=True):
    floorIndex: NotRequired[float]
    name: str
    numberStr: str
    categoryAttributeId: NotRequired[AttributeId]
    stampPosition: NotRequired[Coordinate2D]
    geometry: ZoneCreationGeometry


class WallData(TypedDict, closed=True):
    begCoordinate: Coordinate2D
    endCoordinate: Coordinate2D
    zCoordinate: float
    height: float
    thickness: float
    offset: NotRequired[float]
    structureType: NotRequired[Literal["Basic", "Composite", "Profile"]]
    buildingMaterialId: NotRequired[AttributeId]
    compositeId: NotRequired[AttributeId]
    profileId: NotRequired[AttributeId]


class LabelData(TypedDict, closed=True):
    parentElementId: NotRequired[ElementId]
    text: NotRequired[str]
    begCoordinate: NotRequired[Coordinate2D]
    floorInd: NotRequired[float]


class ElementIdArrayItem(TypedDict, closed=True):
    elementId: ElementId


class AttributeIdArrayItem(TypedDict, closed=True):
    attributeId: AttributeId


NavigatorItemIds: TypeAlias = list[NavigatorItemIdArrayItem]
Databases: TypeAlias = list[DatabaseIdArrayItem]


class CurtainWallPanelDetails(TypedDict, closed=True):
    polygonCoordinates: list[Coordinate3D]
    isHidden: bool
    segmentIndex: float
    className: str
    frames: list[ElementIdArrayItem]


TypeSpecificDetails: TypeAlias = (
    WallDetails
    | BeamDetails
    | SlabDetails
    | ColumnDetails
    | DetailWorksheetDetails
    | LibPartBasedElementDetails
    | PolylineDetails
    | ZoneDetails
    | CurtainWallDetails
    | CurtainWallSegmentDetails
    | CurtainWallPanelDetails
    | CurtainWallFrameDetails
    | MeshDetails
    | NotYetSupportedElementTypeDetails
)
BuildingMaterialPhysicalPropertiesList: TypeAlias = list[BuildingMaterialPhysicalPropertiesArrayItem]
LibraryFileAdditions: TypeAlias = list[LibraryFileAddition]
ElementOrGroupId: TypeAlias = ElementIdArrayItem | GroupIdArrayItem
ElementOrGroupIds: TypeAlias = list[ElementOrGroupId]


class ElementGroupParameters(TypedDict, closed=True):
    elements: ElementOrGroupIds
    parentGroupId: NotRequired[GroupId]


class DetailsOfElement(TypedDict, closed=True):
    type: ElementType
    id: str
    floorIndex: float
    layerIndex: float
    drawIndex: float
    details: TypeSpecificDetails


class Skin(TypedDict, closed=True):
    type: str
    buildingMaterialId: AttributeIdArrayItem
    framePen: int
    thickness: float


class Separator(TypedDict, closed=True):
    lineTypeId: AttributeIdArrayItem
    linePen: int


class CompositeDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    useWith: NotRequired[list[str]]
    skins: list[Skin]
    separators: list[Separator]


class SurfaceDataArrayItem(TypedDict, closed=True):
    attributeId: NotRequired[AttributeId]
    index: NotRequired[str]
    name: str
    materialType: SurfaceType
    ambientReflection: float
    diffuseReflection: float
    specularReflection: float
    transparency: float
    shine: float
    transparencyAttenuation: float
    emissionAttenuation: float
    surfaceColor: ColorRGB
    specularColor: ColorRGB
    emissionColor: ColorRGB
    fillId: NotRequired[AttributeIdArrayItem]
    texture: NotRequired[Texture]


class ElementsWithExecutionResults(TypedDict, closed=True):
    elements: Elements
    executionResultForDatabases: NotRequired[ExecutionResults]


ElementsWithExecutionResultsOrError: TypeAlias = ElementsWithExecutionResults | ErrorItem


class ConnectedElement(TypedDict, closed=True):
    elements: Elements


class ConnectedElementsWrapper(TypedDict, closed=True):
    connectedElements: list[ConnectedElement]


ConnectedElementsOrError: TypeAlias = ConnectedElementsWrapper | ErrorItem


class Subelement(TypedDict, closed=True):
    cWallSegments: NotRequired[Elements]
    cWallFrames: NotRequired[Elements]
    cWallPanels: NotRequired[Elements]
    cWallJunctions: NotRequired[Elements]
    cWallAccessories: NotRequired[Elements]
    stairRisers: NotRequired[Elements]
    stairTreads: NotRequired[Elements]
    stairStructures: NotRequired[Elements]
    railingNodes: NotRequired[Elements]
    railingSegments: NotRequired[Elements]
    railingPosts: NotRequired[Elements]
    railingRailEnds: NotRequired[Elements]
    railingRailConnections: NotRequired[Elements]
    railingHandrailEnds: NotRequired[Elements]
    railingHandrailConnections: NotRequired[Elements]
    railingToprailEnds: NotRequired[Elements]
    railingToprailConnections: NotRequired[Elements]
    railingRails: NotRequired[Elements]
    railingToprails: NotRequired[Elements]
    railingHandrails: NotRequired[Elements]
    railingPatterns: NotRequired[Elements]
    railingInnerPosts: NotRequired[Elements]
    railingPanels: NotRequired[Elements]
    railingBalusterSets: NotRequired[Elements]
    railingBalusters: NotRequired[Elements]
    beamSegments: NotRequired[Elements]
    columnSegments: NotRequired[Elements]


class Hotlink(TypedDict, closed=True):
    location: str
    children: NotRequired[Hotlinks]
